Repository ceph/ceph-ansible, pull requests merged in 2018-07, with the labels that each got.

#2830 ceph-client: do not kill the dummy container
  roles/ceph-client/tasks/create_users_keys.yml
Labels: backport-stable-3.1

#2784 mgr: fix enabling of mgr module on mimic
  roles/ceph-mgr/tasks/main.yml
Labels: backport-stable-3.0, backport-stable-3.1

#2847 ceph-common: fix rhcs condition
  roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install.yml
Labels: backport-stable-3.0, backport-stable-3.1

#2850 ceph-config: do not log cluster log on container
  roles/ceph-config/templates/ceph.conf.j2
Labels: backport-stable-3.1

#2862 tests: fix `_get_osd_id_from_host()` in TestOSDs()
  tests/functional/tests/osd/test_osds.py
Labels: backport-stable-3.0, backport-stable-3.1

#2875 mgr: fix condition to add modules to ceph-mgr
  roles/ceph-mgr/tasks/main.yml
Labels: backport-stable-3.0, backport-stable-3.1

#2874 client: do not rely on copy_admin_key to import keys
  roles/ceph-client/tasks/create_users_keys.yml
Labels: backport-stable-3.0, backport-stable-3.1

#2885 nfs: change default stable branch for nfs-ganesha repo
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-3.1

#2887 ceph-iscsi: rename group iscsi_gws
  Vagrantfile
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  infrastructure-playbooks/purge-iscsi-gateways.yml
  infrastructure-playbooks/rolling_update.yml
  roles/ceph-defaults/defaults/main.yml
  site.yml.sample
  tests/functional/centos/7/cluster/group_vars/iscsigws
  tests/functional/centos/7/cluster/hosts
  tests/functional/centos/7/docker/group_vars/iscsigws
Labels: backport

#2890 tests: add latest-bis-jewel for jewel tests
  tox.ini
Labels: backport-stable-3.0, backport-stable-3.1

#2897 validate: only run osd test on osd node
  roles/ceph-validate/tasks/check_devices.yml
  roles/ceph-validate/tasks/main.yml
Labels: backport-stable-3.0, backport-stable-3.1

#2917 tests: do not deploy all daemons for shrink osds scenarios
  tests/functional/centos/7/shrink_osd/Vagrantfile
  tests/functional/centos/7/shrink_osd/ceph-override.json
  tests/functional/centos/7/shrink_osd/group_vars/all
  tests/functional/centos/7/shrink_osd/group_vars/mons
  tests/functional/centos/7/shrink_osd/group_vars/osds
  tests/functional/centos/7/shrink_osd/hosts
  tests/functional/centos/7/shrink_osd/vagrant_variables.yml
  tests/functional/centos/7/shrink_osd_container/Vagrantfile
  tests/functional/centos/7/shrink_osd_container/ceph-override.json
  tests/functional/centos/7/shrink_osd_container/group_vars/all
  tests/functional/centos/7/shrink_osd_container/group_vars/mons
  tests/functional/centos/7/shrink_osd_container/group_vars/osds
  tests/functional/centos/7/shrink_osd_container/hosts
  tests/functional/centos/7/shrink_osd_container/vagrant_variables.yml
  tox.ini
Labels: backport-stable-3.0, backport-stable-3.1

#2914 Osd sortbitwise
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-3.0, backport-stable-3.1

#2928 Run creation of empty rados index object to first monitor
  roles/ceph-nfs/tasks/start_nfs.yml
Labels: backport-stable-3.1

#2929 rgw: add more config option for civetweb frontend
  roles/ceph-rgw/tasks/docker/container_env_facts.yml
Labels: backport-stable-3.0, backport-stable-3.1

#2944 ceph ansible 3.1 igw: fix rbd-target-gw startup
  roles/ceph-iscsi-gw/tasks/configure_iscsi.yml
  roles/ceph-iscsi-gw/tasks/prerequisites.yml
Labels: backport

#2948 osd: do not remove expose_partition container
  roles/ceph-osd/templates/ceph-osd-run.sh.j2
Labels: backport-stable-3.0, backport-stable-3.1

#2938 igw: fix image removal during purge
  library/igw_purge.py
  roles/ceph-iscsi-gw/library/igw_purge.py
Labels: backport-stable-3.1

#2954 [skip ci] config: enforce socket name
  roles/ceph-config/templates/ceph.conf.j2
Labels: backport-stable-3.1
