Repository ceph/ceph-ansible, pull requests merged in 2018-03, with the labels that each got.

#2454 Fix config_template to consistently order sections
  plugins/actions/_v1_config_template.py
  plugins/actions/_v2_config_template.py
Labels: backport

#2455 ceph-defaults: set is_atomic variable
  roles/ceph-defaults/tasks/facts.yml
Labels: backport-stable-3.0

#2460 ceph-defaults: set is_atomic variable
  roles/ceph-defaults/tasks/facts.yml
Labels: backport

#2438 setup keys properly when not nfs_obj_gw
  roles/ceph-nfs/tasks/pre_requisite_non_container.yml
Labels: backport-stable-3.0, bug

#2469 cleanup osd.conf.j2
  roles/ceph-osd/templates/osd.conf.j2
Labels: backport-stable-3.0

#2471 Refer to expected-num-ojects as expected_num_objects, not size
  group_vars/clients.yml.sample
  group_vars/mons.yml.sample
  roles/ceph-client/defaults/main.yml
  roles/ceph-client/tasks/create_users_keys.yml
  roles/ceph-mon/defaults/main.yml
  roles/ceph-mon/tasks/openstack_config.yml
  tests/functional/centos/7/cluster/group_vars/clients
  tests/functional/centos/7/cluster/group_vars/mons
  tests/functional/centos/7/docker-collocation/group_vars/clients
  tests/functional/centos/7/docker/group_vars/clients
  tests/functional/centos/7/docker/group_vars/mons
Labels: backport-stable-3.0

#2477 ceph-osd note that some scenarios use ceph-disk vs. ceph-volume
  group_vars/osds.yml.sample
  roles/ceph-osd/defaults/main.yml
Labels: backport-stable-3.0

#2479 ceph-mds: delete duplicate multimds container tasks
  roles/ceph-mds/tasks/containerized.yml
Labels: backport-stable-3.0
