Repository ceph/ceph-ansible, pull requests merged in 2018-05, with the labels that each got.

#2558 common: copy iso files if rolling_update
  roles/ceph-common/tasks/installs/prerequisite_rhcs_iso_install.yml
Labels: backport-stable-3.0

#2559 Backport of 2558
  roles/ceph-common/tasks/installs/prerequisite_rhcs_iso_install.yml
Labels: backport

#2560 playbook: improve facts gathering
  site-docker.yml.sample
  site.yml.sample
Labels: backport-stable-3.0

#2569 mon: fix mgr keyring creation when upgrading from jewel
  roles/ceph-mon/tasks/docker/main.yml
Labels: backport-stable-3.0

#2570 adds missing state needed to upgrade nfs-ganesha
  roles/ceph-nfs/tasks/pre_requisite_non_container.yml
Labels: backport-stable-3.0

#2566 Backport of 2498
  roles/ceph-defaults/templates/restart_mds_daemon.sh.j2
Labels: backport

#2584 Iscsi fixes
  roles/ceph-iscsi-gw/tasks/prerequisites.yml
Labels: backport-stable-3.1

#2594 rolling_update: move osd flag section
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-3.0, backport-stable-3.1

#2596 fix purge, wipe partitions properly
  infrastructure-playbooks/purge-cluster.yml
Labels: backport-stable-3.0, backport-stable-3.1

#2595 [skip ci] switch: disable ceph-disk units
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Labels: backport-stable-3.0, backport-stable-3.1

#2601 Backport 3.0 : rolling_update: move osd flag section
  infrastructure-playbooks/rolling_update.yml
Labels: backport

#2608 [skip ci] take-over: fix bug when trying to override variable
  infrastructure-playbooks/take-over-existing-cluster.yml
Labels: backport-stable-3.0, backport-stable-3.1

#2613 [skip ci] defaults: restart_osd_daemon unit spaces
  roles/ceph-defaults/templates/restart_osd_daemon.sh.j2
Labels: backport-stable-3.1

#2615 Backport of 2613 in stable-3.1
  roles/ceph-defaults/templates/restart_osd_daemon.sh.j2
Labels: backport

#2602 [skip ci] backport of 2596 in stable-3.0
  infrastructure-playbooks/purge-cluster.yml
Labels: backport

#2604 Backport of 2595 in stable-3.1
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Labels: backport

#2627 rolling_update: fix get fsid for containers
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-3.1

#2626 Backport of 2613 in stable-3.0
  roles/ceph-defaults/templates/restart_osd_daemon.sh.j2
Labels: backport

#2624 Backport of 2451 in stable-3.0
  roles/ceph-defaults/handlers/main.yml
Labels: backport

#2593 Skip GPT header creation for lvm osd scenario
  roles/ceph-osd/tasks/main.yml
Labels: backport-stable-3.0, backport-stable-3.1

#2563 [skip ci] rhcs: bump version to 3.0 for stable 3.1
  rhcs_edits.txt
Labels: backport-stable-3.1

#2635 [skip ci] Backport of 2563 in stable-3.1
  rhcs_edits.txt
Labels: backport

#2637 Backport of 2620 in stable-3.1
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-rgw/tasks/main.yml
  tests/functional/centos/7/ooo-collocation/hosts
Labels: backport

#2636 Backport of 2620 in stable-3.0
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-rgw/tasks/main.yml
  tests/functional/centos/7/ooo-collocation/hosts
Labels: backport

#2638 playbook: follow up on #2553
  site-docker.yml.sample
Labels: backport-stable-3.1

#2525 rgw: container add option to configure multi-site zone
  group_vars/rgws.yml.sample
  roles/ceph-rgw/defaults/main.yml
  roles/ceph-rgw/tasks/docker/container_env_facts.yml
  roles/ceph-rgw/tasks/docker/main.yml
  roles/ceph-rgw/tasks/main.yml
Labels: backport-stable-3.0, backport-stable-3.1

#2640 Backport of 2638 in stable-3.1
  site-docker.yml.sample
Labels: backport

#2645 mds: move mds fs pools creation
  roles/ceph-mds/tasks/main.yml
Labels: backport-stable-3.1

#2644 [skip ci] iscsi purge process needed sudo privileges
  infrastructure-playbooks/purge-iscsi-gateways.yml
Labels: backport-stable-3.0, backport-stable-3.1

#2646 Backport of 2645 in stable-3.1
  roles/ceph-mds/tasks/main.yml
Labels: backport

#2651 tests: fix broken symlink
  tests/requirements2.5.txt
Labels: backport-stable-3.0, backport-stable-3.1

#2661 osds: do not set docker_exec_cmd fact
  roles/ceph-osd/tasks/main.yml
Labels: backport-stable-3.1

#2654 mdss: do not make pg_num a mandatory params
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-validate/tasks/main.yml
  tests/functional/centos/7/cluster/group_vars/all
  tests/functional/centos/7/docker-collocation/group_vars/all
  tests/functional/centos/7/docker/group_vars/all
  tests/functional/ubuntu/16.04/cluster/group_vars/all
Labels: backport-stable-3.1

#2663 osds: do not set docker_exec_cmd fact
  roles/ceph-osd/tasks/main.yml
Labels: backport

#2662 Backport of 2651 in stable-3.1
  tests/requirements2.5.txt
Labels: backport

#2643 Backport of 2525 in stable-3.0
  group_vars/rgws.yml.sample
  roles/ceph-rgw/defaults/main.yml
  roles/ceph-rgw/tasks/docker/container_env_facts.yml
  roles/ceph-rgw/tasks/docker/main.yml
  roles/ceph-rgw/tasks/main.yml
Labels: backport

#2642 Backport of 2525 in stable-3.1
  group_vars/rgws.yml.sample
  roles/ceph-rgw/defaults/main.yml
  roles/ceph-rgw/tasks/docker/container_env_facts.yml
  roles/ceph-rgw/tasks/docker/main.yml
  roles/ceph-rgw/tasks/main.yml
Labels: backport
