Repository ceph/ceph-ansible, pull requests merged in 2018-06, with the labels that each got.

#2669 Makefile: followup on #2585
  Makefile
Labels: backport-stable-3.0, backport-stable-3.1

#2676 [skip ci] Backport of 2669 in stable-3.1
  Makefile
Labels: backport

#2677 Backport of 2669 in stable-3.0
  Makefile
Labels: backport

#2675 osds: wait for osds to be up before creating pools
  roles/ceph-osd/tasks/openstack_config.yml
Labels: backport-stable-3.0, backport-stable-3.1

#2673 ceph-defaults: add the 14.x entry to ceph_release_num
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-common/tasks/release-rhcs.yml
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-docker-common/tasks/release.yml
Labels: backport-stable-3.1

#2680 Backport of 2675 in stable-3.1
  roles/ceph-osd/tasks/openstack_config.yml
Labels: backport

#2679 mons: move set_fact of openstack_keys in ceph-osd
  roles/ceph-mon/tasks/main.yml
  roles/ceph-osd/tasks/main.yml
Labels: backport-stable-3.1

#2683 Backport of 2679 in stable-3.1
  roles/ceph-mon/tasks/main.yml
  roles/ceph-osd/tasks/main.yml
Labels: backport

#2682 Backport of 2673 in stable-3.1
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-common/tasks/release-rhcs.yml
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-docker-common/tasks/release.yml
Labels: backport

#2678 Backport "Fix template reference for ganesha.conf"
  roles/ceph-nfs/tasks/start_nfs.yml
Labels: backport

#2658 Rolling upgrades should use norebalance flag for OSDs
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-3.0, backport-stable-3.1

#2684 refact rgw pools creation on containerized deployment
  roles/ceph-rgw/tasks/docker/main.yml
  roles/ceph-rgw/tasks/docker/rgw_pool_pgs.yml
  roles/ceph-rgw/tasks/main.yml
  roles/ceph-rgw/tasks/rgw_pool_pgs.yml
  tests/functional/centos/7/docker-collocation/group_vars/rgws
  tests/functional/centos/7/ooo-collocation/hosts
Labels: backport-stable-3.0, backport-stable-3.1

#2689 Backport of 2424 in stable-3.1
  group_vars/rgws.yml.sample
  roles/ceph-rgw/defaults/main.yml
  roles/ceph-rgw/tasks/docker/main.yml
  roles/ceph-rgw/tasks/docker/rgw_pool_pgs.yml
  roles/ceph-rgw/tasks/main.yml
  roles/ceph-rgw/tasks/rgw_pool_pgs.yml
  tests/functional/centos/7/bs-osds-container/group_vars/rgws.yml
  tests/functional/centos/7/bs-osds-non-container/group_vars/rgws.yml
  tests/functional/centos/7/cluster/group_vars/rgws
  tests/functional/centos/7/docker-collocation/group_vars/rgws
  tests/functional/centos/7/docker/group_vars/rgws
  tests/functional/centos/7/fs-osds-container/group_vars/rgws.yml
  tests/functional/centos/7/fs-osds-non-container/group_vars/rgws.yml
  tests/functional/tests/rgw/test_rgw_tuning.py
  tests/functional/ubuntu/16.04/cluster/group_vars/rgws
Labels: backport

#2690 Backport of 2424 in stable-3.0
  group_vars/rgws.yml.sample
  roles/ceph-rgw/defaults/main.yml
  roles/ceph-rgw/tasks/docker/main.yml
  roles/ceph-rgw/tasks/docker/rgw_pool_pgs.yml
  roles/ceph-rgw/tasks/main.yml
  roles/ceph-rgw/tasks/rgw_pool_pgs.yml
  tests/functional/centos/7/bs-osds-container/group_vars/rgws.yml
  tests/functional/centos/7/bs-osds-non-container/group_vars/rgws.yml
  tests/functional/centos/7/cluster/group_vars/rgws
  tests/functional/centos/7/docker-collocation/group_vars/rgws
  tests/functional/centos/7/docker/group_vars/rgws
  tests/functional/centos/7/fs-osds-container/group_vars/rgws.yml
  tests/functional/centos/7/fs-osds-non-container/group_vars/rgws.yml
  tests/functional/tests/rgw/test_rgw_tuning.py
  tests/functional/ubuntu/16.04/cluster/group_vars/rgws
Labels: backport

#2699 Backport rgw: refact rgw pools creation in stable-3.1
  roles/ceph-rgw/tasks/docker/main.yml
  roles/ceph-rgw/tasks/docker/rgw_pool_pgs.yml
  roles/ceph-rgw/tasks/main.yml
  roles/ceph-rgw/tasks/rgw_pool_pgs.yml
  tests/functional/centos/7/docker-collocation/group_vars/rgws
  tests/functional/centos/7/ooo-collocation/hosts
Labels: backport

#2695 change max_mds default to 1
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: bug

#2713 Backport: playbook: follow up on #2553 in stable-3.0
  site-docker.yml.sample
Labels: backport

#2714 Backport of 2706 in stable-3.1
  tests/functional/tests/rgw/test_rgw_tuning.py
Labels: backport

#2712 rolling_update: fix facts gathering delegation
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-3.0, backport-stable-3.1

#2701 Backport of 2696 in stable-3.1
  tests/functional/centos/7/cluster/group_vars/osds
  tox.ini
Labels: backport

#2724 osd: copy openstack keys over to all mon
  roles/ceph-osd/tasks/openstack_config.yml
Labels: backport-stable-3.0, backport-stable-3.1

#2725 tests: improve mds tests
  tests/functional/tests/mds/test_mds.py
Labels: backport-stable-3.0, backport-stable-3.1

#2723 client: use dummy created container when there is no mon in inventory
  roles/ceph-client/tasks/create_users_keys.yml
Labels: backport-stable-3.0, backport-stable-3.1

#2727 Backport: mon: copy openstack keys over to all mon in stable-3.0
  roles/ceph-mon/tasks/openstack_config.yml
Labels: backport

#2729 Backport of 2725 in stable-3.0
  tests/functional/tests/mds/test_mds.py
Labels: backport

#2728 Backport of 2725 in stable-3.1
  tests/functional/tests/mds/test_mds.py
Labels: backport

#2730 Backport of 2723 in stable-3.1
  roles/ceph-client/tasks/create_users_keys.yml
Labels: backport

#2632 pin version of ansible to 2.4.2 in requirements.txt
  requirements.txt
Labels: backport-stable-3.0, backport-stable-3.1

#2739 client: keyrings aren't created when single client node
  roles/ceph-client/tasks/create_users_keys.yml
Labels: backport-stable-3.1

#2741 Backport of 2739 in stable-3.1
  roles/ceph-client/tasks/create_users_keys.yml
Labels: backport

#2752 tests: set CEPH_DOCKER_IMAGE_TAG when ceph release is luminous
  tox.ini
Labels: backport-stable-3.1

#2748 tests: increase memory to 1024Mb for centos7_cluster scenario
  tests/functional/centos/7/cluster/vagrant_variables.yml
Labels: backport-stable-3.0, backport-stable-3.1

#2755 [skip ci] Backport of 2748 in stable-3.0
  tests/functional/centos/7/cluster/vagrant_variables.yml
Labels: backport

#2754 [skip ci] Backport of 2748 in stable-3.1
  tests/functional/centos/7/cluster/vagrant_variables.yml
Labels: backport

#2753 Backport of 2752 in stable-3.1
  tox.ini
Labels: backport

#2751 common: ability to enable/disable fw configuration
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-common/tasks/main.yml
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-3.1

#2756 Backport: common: ability to enable/disable fw configuration in stable-3.1
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-common/tasks/main.yml
  roles/ceph-defaults/defaults/main.yml
Labels: backport

#2694 ceph-mds: do not enable multimds on jewel
  roles/ceph-mds/tasks/create_mds_filesystems.yml
Labels: bug

#2760 client: try to kill dummy container only on first client node
  roles/ceph-client/tasks/create_users_keys.yml
Labels: backport-stable-3.1

#2763 Backport of 2760 in stable-3.1
  roles/ceph-client/tasks/create_users_keys.yml
Labels: backport

#2761 Backport of 2694 in stable-3.1
  roles/ceph-mds/tasks/create_mds_filesystems.yml
Labels: backport

#2771 tests: keep same ceph release during handlers/idempotency test
  tests/functional/centos/7/cluster/ceph-override.json
  tox.ini
Labels: backport-stable-3.0, backport-stable-3.1

#2775 mon/osd: bump container memory limit
  group_vars/mons.yml.sample
  group_vars/osds.yml.sample
  roles/ceph-mon/defaults/main.yml
  roles/ceph-osd/defaults/main.yml
Labels: backport-stable-3.0, backport-stable-3.1

#2776 common: start firewalld if configure_firewall
  roles/ceph-common/tasks/misc/configure_firewall_rpm.yml
Labels: backport-stable-3.1

#2772 backport: tests: keep same ceph release during handlers/idempotency test in stable-3.1
  tests/functional/centos/7/cluster/ceph-override.json
  tox.ini
Labels: backport

#2779 Backport of 2775 in stable-3.1
  group_vars/mons.yml.sample
  group_vars/osds.yml.sample
  roles/ceph-mon/defaults/main.yml
  roles/ceph-osd/defaults/main.yml
Labels: backport

#2765 tests: add more nodes in ooo testing scenario
  tests/functional/centos/7/ooo-collocation/hosts
  tests/functional/centos/7/ooo-collocation/vagrant_variables.yml
Labels: backport-stable-3.0, backport-stable-3.1

#2789 tests: fix *_has_correct_value tests
  tests/functional/tests/mon/test_mons.py
  tests/functional/tests/test_install.py
Labels: backport-stable-3.0, backport-stable-3.1

#2790 Backport: tests: fix *_has_correct_value tests in stable-3.1
  tests/functional/tests/mon/test_mons.py
  tests/functional/tests/test_install.py
Labels: backport

#2788 tests: add more verbosity in testinfra
  tox.ini
Labels: backport-stable-3.0, backport-stable-3.1

#2782 Backport: tests: add more nodes in ooo testing scenario in stable-3.1
  tests/functional/centos/7/ooo-collocation/hosts
  tests/functional/centos/7/ooo-collocation/vagrant_variables.yml
Labels: backport

#2778 Backport: mon/osd: bump container memory limit in stable-3.0
  group_vars/mons.yml.sample
  group_vars/osds.yml.sample
  roles/ceph-mon/defaults/main.yml
  roles/ceph-osd/defaults/main.yml
Labels: backport

#2783 Backport: tests: add more nodes in ooo testing scenario in stable-3.0
  tests/functional/centos/7/ooo-collocation/hosts
  tests/functional/centos/7/ooo-collocation/vagrant_variables.yml
Labels: backport

#2808 tests: reduce the amount of time we wait
  tox.ini
Labels: backport-stable-3.0, backport-stable-3.1

#2815 mon: honour mon_docker_net_host option
  roles/ceph-mon/templates/ceph-mon.service.j2
Labels: backport-stable-3.0, backport-stable-3.1

#2797 ceph-mon: Generate initial keyring
  roles/ceph-mon/tasks/deploy_monitors.yml
Labels: backport-stable-3.0, backport-stable-3.1

#2814 setup mon repo on mgr nodes when rhcs cdn debian config is set
  roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install.yml
  roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install_debian.yml
Labels: backport-stable-3.0, backport-stable-3.1
