Repository ceph/ceph-ansible, pull requests merged in 2018-10, with the labels that each got.

#3150 doc: redo lvm scenario documentation, improved wording and config descriptions
  docs/source/osds/scenarios.rst
Labels: documentation

#3183 config: look up for monitor_address_block in hostvars
  roles/ceph-config/templates/ceph.conf.j2
Labels: backport-stable-3.1

#3184 switch: support migration when cluster is scrubbing
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Labels: backport-stable-3.1

#3188 handler osd
  roles/ceph-defaults/handlers/main.yml
Labels: backport-stable-3.1

#3171 switch: allow switch big clusters (more than 99 osds)
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Labels: backport-stable-3.0, backport-stable-3.1

#2992 rolling_update: fix upgrade when using fqdn
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-3.0, backport-stable-3.1

#3192 Fix problem with ceph_key in python3
  library/ceph_key.py
Labels: backport-stable-3.1
