Repository ceph/ceph-ansible, pull requests merged in 2018-09, with the labels that each got.

#3068 purge: only purge /var/lib/ceph content
  infrastructure-playbooks/purge-cluster.yml
  infrastructure-playbooks/purge-docker-cluster.yml
Labels: backport-stable-3.1

#3077 roles: ceph-rgw: Enable the ceph-radosgw target
  roles/ceph-rgw/tasks/start_radosgw.yml
Labels: backport-stable-3.1

#3088 ceph-nfs: run rados cmds in container
  roles/ceph-nfs/tasks/start_nfs.yml
Labels: backport-stable-3.1

#3096 defaults: add a default value to rgw_hostname
  roles/ceph-config/templates/ceph.conf.j2
  roles/ceph-defaults/tasks/facts.yml
Labels: backport-stable-3.1

#3118 tests: pin sphinx version to 1.7.9
  docs/tox.ini
Labels: backport-stable-3.0, backport-stable-3.1

#3114 nfs: ignore error on semanage command for ganesha_t
  roles/ceph-nfs/tasks/ganesha_selinux_fix.yml
Labels: backport-stable-3.0, backport-stable-3.1

#3126 tests: fix monitor_address for shrink_osd scenario
  tests/functional/centos/7/shrink_osd/hosts
Labels: backport

#3133 config: set default _rgw_hostname value to respective host
  roles/ceph-config/templates/ceph.conf.j2
Labels: backport-stable-3.1

#3137 restart_osd_daemon.sh.j2 - consider scrubbing pgs as OK
  roles/ceph-defaults/templates/restart_osd_daemon.sh.j2
Labels: backport-stable-3.0, backport-stable-3.1

#3158 Fix version check in ceph.conf template
  roles/ceph-config/templates/ceph.conf.j2
Labels: backport-stable-3.1

#3164 upgrade: consider all 'active+clean' states as valid pgs
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-3.1

#3174 purge: actually remove of /var/lib/ceph/*
  infrastructure-playbooks/purge-cluster.yml
  infrastructure-playbooks/purge-docker-cluster.yml
Labels: backport-stable-3.1

#3051 don't use "include" to include tasks
  infrastructure-playbooks/untested-by-ci/purge-multisite.yml
  roles/ceph-agent/tasks/main.yml
  roles/ceph-client/tasks/main.yml
  roles/ceph-common-coreos/tasks/main.yml
  roles/ceph-common/tasks/installs/configure_debian_repository_installation.yml
  roles/ceph-common/tasks/installs/configure_redhat_repository_installation.yml
  roles/ceph-common/tasks/installs/configure_suse_repository_installation.yml
  roles/ceph-common/tasks/installs/debian_rhcs_repository.yml
  roles/ceph-common/tasks/installs/install_on_debian.yml
  roles/ceph-common/tasks/installs/install_on_redhat.yml
  roles/ceph-common/tasks/installs/install_on_suse.yml
  roles/ceph-common/tasks/installs/redhat_rhcs_repository.yml
  roles/ceph-common/tasks/main.yml
  roles/ceph-defaults/tasks/check_running_cluster.yml
  roles/ceph-defaults/tasks/main.yml
  roles/ceph-docker-common/tasks/checks.yml
  roles/ceph-docker-common/tasks/main.yml
  roles/ceph-docker-common/tasks/misc/ntp_atomic.yml
  roles/ceph-docker-common/tasks/misc/ntp_debian.yml
  roles/ceph-docker-common/tasks/misc/ntp_rpm.yml
  roles/ceph-docker-common/tasks/pre_requisites/prerequisites.yml
  roles/ceph-iscsi-gw/tasks/main.yml
  roles/ceph-mds/tasks/main.yml
  roles/ceph-mgr/tasks/docker/main.yml
  roles/ceph-mgr/tasks/main.yml
  roles/ceph-mon/tasks/docker/main.yml
  roles/ceph-mon/tasks/main.yml
  roles/ceph-nfs/tasks/main.yml
  roles/ceph-osd/tasks/docker/main.yml
  roles/ceph-osd/tasks/main.yml
  roles/ceph-rbd-mirror/tasks/docker/main.yml
  roles/ceph-rbd-mirror/tasks/main.yml
  roles/ceph-restapi/tasks/docker/main.yml
  roles/ceph-restapi/tasks/main.yml
  roles/ceph-rgw/tasks/docker/main.yml
  roles/ceph-rgw/tasks/main.yml
  roles/ceph-rgw/tasks/multisite/main.yml
  roles/ceph-validate/tasks/main.yml
Labels: DNM
