Repository ceph/ceph-ansible, pull requests merged in 2019-07, with the labels that each got.

#4174 Add condition on dashboard installer phase
  site-container.yml.sample
  site.yml.sample
Labels: backport-stable-4.0, enhancement

#4177 tox-podman.ini: add missing reruns option
  tox-podman.ini
Labels: backport-stable-4.0, bug

#4130 Add radosgw_frontend_ssl_certificate parameter
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-config/templates/ceph.conf.j2
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-handler/templates/restart_rgw_daemon.sh.j2
  roles/ceph-rgw/templates/ceph-radosgw.service.j2
Labels: backport-stable-4.0

#3946 ceph-handler: Fix rgw socket in restart script
  roles/ceph-handler/templates/restart_rgw_daemon.sh.j2
Labels: backport-stable-3.2, backport-stable-4.0, bug

#4188 tests: wait 30sec before running testinfra
  tox.ini
Labels: backport-stable-4.0

#4196 ceph-mon: Fix cluster name parameter
  roles/ceph-mon/tasks/deploy_monitors.yml
Labels: backport-stable-4.0, bug

#4194 ceph-handler: Fix radosgw_address default value
  roles/ceph-handler/templates/restart_rgw_daemon.sh.j2
Labels: bug

#4195 ceph-iscsi-gw: Update log directories bind mount
  roles/ceph-iscsi-gw/tasks/container/containerized.yml
  roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2
  roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2
Labels: backport-stable-4.0, enhancement

#4193 add tag on ceph-grafana-dashboards package.
  roles/ceph-grafana/tasks/configure_grafana.yml
Labels: backport-stable-4.0

#4190 ceph-handler: fix cluster name in socket path
  roles/ceph-handler/templates/restart_osd_daemon.sh.j2
  roles/ceph-handler/templates/restart_rgw_daemon.sh.j2
Labels: backport-stable-4.0

#4211 dashboard: Use upstream default port
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0

#4202 ceph-dashboard: remove bool filter for rgw vars
  roles/ceph-dashboard/tasks/configure_dashboard.yml
Labels: backport-stable-4.0, bug

#4206 ceph-iscsi: Update gateway config/template
  group_vars/iscsigws.yml.sample
  roles/ceph-iscsi-gw/defaults/main.yml
  roles/ceph-iscsi-gw/tasks/common.yml
  roles/ceph-iscsi-gw/templates/iscsi-gateway.cfg.j2
Labels: backport-stable-4.0, enhancement

#4217 validate: improve message printed in check_devices.yml
  roles/ceph-validate/tasks/check_devices.yml
Labels: backport-stable-3.2, backport-stable-4.0

#4210 handler: remove legacy condition
  roles/ceph-handler/handlers/main.yml
Labels: backport-stable-4.0

#4222 Install nfs-ganesha stable v2.7
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
  tests/functional/all_daemons/hosts-ubuntu
  tests/functional/shrink_mon/hosts-ubuntu
Labels: enhancement

#4225 ceph-infra: Open prometheus port
  roles/ceph-infra/tasks/configure_firewall.yml
Labels: backport-stable-4.0, bug

#4223 ceph-infra: update handler with daemon variable
  roles/ceph-infra/handlers/main.yml
Labels: backport-stable-3.2, backport-stable-4.0, bug

#4236 tests: remove useless setting
  tox-dashboard.ini
  tox-update.ini
  tox.ini
Labels: backport-stable-4.0

#4241 validate: fail if gpt header found on unprepared devices
  roles/ceph-validate/tasks/check_devices.yml
Labels: backport-stable-4.0

#4234 library/ceph_volume.py: remove six dependency
  library/ceph_volume.py
Labels: backport-stable-4.0, enhancement

#4247 handler: fix bug in osd handlers
  roles/ceph-handler/templates/restart_osd_daemon.sh.j2
Labels: backport-stable-4.0

#4252 Fix backward compat with old cephfs_pools format
  roles/ceph-mds/tasks/create_mds_filesystems.yml
Labels: backport-stable-4.0, bug

#4231 Avoid to setup provisioners in a fully containerized environment
  roles/ceph-grafana/tasks/configure_grafana.yml
Labels: backport-stable-4.0

#4264 container: rename docker directories
  roles/ceph-rbd-mirror/tasks/container/main.yml
  roles/ceph-rbd-mirror/tasks/container/start_docker_rbd_mirror.yml
  roles/ceph-rbd-mirror/tasks/main.yml
  roles/ceph-rgw/tasks/container/main.yml
  roles/ceph-rgw/tasks/container/start_docker_rgw.yml
  roles/ceph-rgw/tasks/main.yml
Labels: backport-stable-4.0

#4270 infra-playbooks: rewite a condition for better readability
  infrastructure-playbooks/shrink-mgr.yml
  infrastructure-playbooks/shrink-rbdmirror.yml
Labels: backport-stable-4.0

#4250 Remove NBSP characters
  .travis.yml
  infrastructure-playbooks/purge-cluster.yml
  roles/ceph-validate/tasks/check_ipaddr_mon.yml
  tests/functional/setup.yml
Labels: backport-stable-3.2, backport-stable-4.0, bug

#4258 ceph-osd: check container engine rc for pools
  roles/ceph-osd/tasks/openstack_config.yml
Labels: backport-stable-3.2, backport-stable-4.0, bug

#4235 osd: add 'osd blacklist' cap for osp keyrings
  group_vars/all.yml.sample
  group_vars/clients.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-client/defaults/main.yml
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-3.2, backport-stable-4.0

#4282 tests: Update ooo-collocation scenario
  tests/functional/ooo-collocation/hosts
  tests/functional/tests/osd/test_osds.py
  tox.ini
Labels: enhancement

#4294 tests/shrink_rgw: Disable dashboard
  tests/functional/shrink_rgw/container/group_vars/all
  tests/functional/shrink_rgw/group_vars/all
Labels: bug
