Repository ceph/ceph-ansible, pull requests merged in 2019-04, with the labels that each got.

#3759 tox: Fix container purge jobs
  tox.ini
Labels: bug

#3760 tox: Set nautilus as default release
  tests/functional/lvm-auto-discovery/container/group_vars/all
  tox-update.ini
  tox.ini
Labels: enhancement

#3769 purge: fix lvm-batch purge osd
  infrastructure-playbooks/purge-cluster.yml
  infrastructure-playbooks/purge-docker-cluster.yml
Labels: backport-stable-3.2, backport-stable-4.0

#3781 Check ceph_health_raw.stdout value as string during mon bootstrap
  roles/ceph-mon/tasks/ceph_keys.yml
Labels: backport-stable-4.0

#3776 radosgw: Raise cpu limit to 8
  group_vars/rgws.yml.sample
  roles/ceph-rgw/defaults/main.yml
  roles/ceph-rgw/templates/ceph-radosgw.service.j2
Labels: backport-stable-3.2, backport-stable-4.0

#3560 rgw multisite: add more than 1 rgw to the master or secondary zone
  README-MULTISITE.md
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-rgw/tasks/multisite/master.yml
  roles/ceph-rgw/tasks/multisite/secondary.yml
  tests/functional/rgw-multisite/container/group_vars/rgws
  tests/functional/rgw-multisite/container/hosts
  tests/functional/rgw-multisite/container/secondary/hosts
  tests/functional/rgw-multisite/group_vars/rgws
  tests/functional/rgw-multisite/hosts
  tests/functional/rgw-multisite/secondary/hosts
Labels: backport-stable-3.2, backport-stable-4.0

#3805 ceph-rgw: Fix bad paths which depend on the cluster name
  roles/ceph-rgw/tasks/docker/start_docker_rgw.yml
  roles/ceph-rgw/templates/ceph-radosgw.service.j2
Labels: backport-stable-4.0, bug

#3800 ceph-facts: use last ipv6 address for mon/rgw
  roles/ceph-facts/tasks/set_monitor_address.yml
  roles/ceph-facts/tasks/set_radosgw_address.yml
Labels: backport-stable-4.0, bug

#3801 mon/rgw: use last ipv6 address
  roles/ceph-config/templates/ceph.conf.j2
  roles/ceph-handler/templates/restart_rgw_daemon.sh.j2
  roles/ceph-mon/templates/ceph-mon.service.j2
Labels: bug

#3749 UCA: Uncomment UCA variables in defaults, fix consequent breakage
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-common/tasks/installs/install_debian_packages.yml
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-mds/tasks/non_containerized.yml
  roles/ceph-mgr/tasks/pre_requisite.yml
Labels: backport-stable-3.2, backport-stable-4.0

#3828 mon: remove useless delegate_to
  roles/ceph-mon/tasks/main.yml
Labels: backport-stable-4.0, enhancement

#3840 osds: allow passing devices by path
  roles/ceph-facts/tasks/facts.yml
  tests/functional/lvm-batch/container/group_vars/all
  tests/functional/lvm-batch/group_vars/all
Labels: backport-stable-4.0

#3843 update: fix undefined error when no mgr group is declared
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0

#3851 switch-from-non-containerized: stop all osds
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Labels: bug

#3854 ceph-mon: increase timeout waiting for admin and bootstrap keys
  roles/ceph-mon/tasks/ceph_keys.yml
Labels: enhancement

#3852 docs: Update ceph.conf supported section
  docs/source/index.rst
Labels: backport-stable-4.0, documentation, enhancement

#3855 purge-cluster: remove python-ceph-argparse package
  infrastructure-playbooks/purge-cluster.yml
Labels: backport-stable-4.0, bug

#3861 defaults: remove some package dependencies
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-common/tasks/installs/install_on_debian.yml
  roles/ceph-common/tasks/installs/install_redhat_packages.yml
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0

#3864 defaults: refact package dependencies installation.
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-common/tasks/installs/install_on_debian.yml
  roles/ceph-common/tasks/installs/install_redhat_packages.yml
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0

#3869 test_mons: test mon listening on port 3300
  tests/functional/tests/mon/test_mons.py
Labels: backport-stable-4.0, enhancement

#3853 tests/functional/setup: change mount options
  tests/functional/setup.yml
  tests/requirements.txt
Labels: enhancement

#3874 allow using ansible 2.8
  roles/ceph-agent/meta/main.yml
  roles/ceph-client/meta/main.yml
  roles/ceph-common/meta/main.yml
  roles/ceph-config/meta/main.yml
  roles/ceph-container-common/meta/main.yml
  roles/ceph-defaults/meta/main.yml
  roles/ceph-validate/tasks/check_system.yml
Labels: backport-stable-4.0, feature

#3868 test_osds: remove scenario leftover
  tests/functional/tests/osd/test_osds.py
Labels: backport-stable-4.0

#3875 ceph-iscsi-gw: Remove library directory
  roles/ceph-iscsi-gw/ceph-iscsi-ansible.spec
  roles/ceph-iscsi-gw/library/igw_client.py
  roles/ceph-iscsi-gw/library/igw_gateway.py
  roles/ceph-iscsi-gw/library/igw_lun.py
  roles/ceph-iscsi-gw/library/igw_purge.py
Labels: backport-stable-4.0, enhancement

#3863 ceph-mgr: Add extra module packages
  group_vars/mgrs.yml.sample
  roles/ceph-mgr/defaults/main.yml
  roles/ceph-mgr/tasks/pre_requisite.yml
Labels: backport-stable-4.0, enhancement

#3882 rgw: add cpuset support
  group_vars/rgws.yml.sample
  roles/ceph-rgw/defaults/main.yml
  roles/ceph-rgw/templates/ceph-radosgw.service.j2
Labels: backport-stable-4.0

#3880 mds: remove legacy task
  roles/ceph-mds/tasks/create_mds_filesystems.yml
Labels: backport-stable-4.0

#3867 ceph-container-common: modify requirement flow
  roles/ceph-container-common/tasks/pre_requisites/debian_prerequisites.yml
  roles/ceph-container-common/tasks/pre_requisites/prerequisites.yml
  roles/ceph-container-common/vars/Debian.yml
  roles/ceph-container-common/vars/RedHat-8.yml
  roles/ceph-container-common/vars/RedHat.yml
  roles/ceph-container-common/vars/Ubuntu-16.yml
  roles/ceph-container-common/vars/Ubuntu-18.yml
Labels: backport-stable-4.0, enhancement

#3655 mds: allow cephFS pool to be created with specific rule_name
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-mds/tasks/create_mds_filesystems.yml
Labels: backport-stable-4.0, enhancement, feature

#3893 validate: fix notario error
  plugins/actions/validate.py
Labels: backport-stable-4.0

#3896 validate: fix a typo
  plugins/actions/validate.py
Labels: backport-stable-4.0

#3902 rolling_update: restart all ceph-iscsi services
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-3.2, backport-stable-4.0, bug

#3905 Update group_vars according to defaults
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
Labels: backport-stable-4.0, enhancement

#3901 ansible.cfg: Add library path to configuration
  ansible.cfg
Labels: bug, enhancement

#3906 tox: Remove update scenario reference
  tox.ini
Labels: backport-stable-4.0, enhancement

#3904 ceph-osd: Increase cpu limit to 4
  group_vars/osds.yml.sample
  roles/ceph-osd/defaults/main.yml
  roles/ceph-osd/templates/ceph-osd-run.sh.j2
Labels: backport-stable-3.2, backport-stable-4.0, bug

#3918 ceph-osd: Fix merge conflict from mergify
  roles/ceph-osd/templates/ceph-osd-run.sh.j2
Labels: bug

#3903 ceph-mds: Increase cpu limit to 4
  group_vars/mdss.yml.sample
  roles/ceph-mds/defaults/main.yml
  roles/ceph-mds/templates/ceph-mds.service.j2
Labels: backport-stable-3.2, backport-stable-4.0, bug

#3922 osd: set default bluestore_wal_devices empty
  docs/source/osds/scenarios.rst
  group_vars/osds.yml.sample
  roles/ceph-osd/defaults/main.yml
  roles/ceph-osd/tasks/scenarios/non-collocated.yml
Labels: bug
