Repository ceph/ceph-ansible, pull requests merged in 2019-05, with the labels that each got.

#3932 ansible: remove private and static attribute
  roles/ceph-osd/tasks/main.yml
  site-container.yml.sample
Labels: backport-stable-4.0

#3807 test adding a RBD mirror to already deployed cluster
  tests/functional/add-rbdmirrors/Vagrantfile
  tests/functional/add-rbdmirrors/ceph-override.json
  tests/functional/add-rbdmirrors/container/Vagrantfile
  tests/functional/add-rbdmirrors/container/ceph-override.json
  tests/functional/add-rbdmirrors/container/group_vars/all
  tests/functional/add-rbdmirrors/container/hosts
  tests/functional/add-rbdmirrors/container/hosts-2
  tests/functional/add-rbdmirrors/container/vagrant_variables.yml
  tests/functional/add-rbdmirrors/group_vars/all
  tests/functional/add-rbdmirrors/hosts
  tests/functional/add-rbdmirrors/hosts-2
  tests/functional/add-rbdmirrors/hosts-ubuntu
  tests/functional/add-rbdmirrors/vagrant_variables.yml
  tox.ini
Labels: backport-stable-4.0

#3934 Fix check mode support
  roles/ceph-facts/tasks/facts.yml
  roles/ceph-mgr/tasks/mgr_modules.yml
Labels: backport-stable-4.0

#3889 test adding a RGW to already deployed cluster
  tests/functional/add-rgws/Vagrantfile
  tests/functional/add-rgws/ceph-override.json
  tests/functional/add-rgws/container/Vagrantfile
  tests/functional/add-rgws/container/ceph-override.json
  tests/functional/add-rgws/container/group_vars/all
  tests/functional/add-rgws/container/hosts
  tests/functional/add-rgws/container/hosts-2
  tests/functional/add-rgws/container/vagrant_variables.yml
  tests/functional/add-rgws/group_vars/all
  tests/functional/add-rgws/group_vars/rgws
  tests/functional/add-rgws/hosts
  tests/functional/add-rgws/hosts-2
  tests/functional/add-rgws/hosts-ubuntu
  tests/functional/add-rgws/vagrant_variables.yml
  tox.ini
Labels: backport-stable-4.0

#3927 don't access other node's docker_exec_cmd variable
  roles/ceph-mds/tasks/create_mds_filesystems.yml
  roles/ceph-mon/tasks/deploy_monitors.yml
  roles/ceph-osd/tasks/openstack_config.yml
Labels: backport-stable-4.0

#3940 remove infrastructure-playbooks/rgw-standalone.yml
  infrastructure-playbooks/rgw-standalone.yml
Labels: backport-stable-4.0

#3943 facts: fix external cluster bug
  roles/ceph-facts/tasks/facts.yml
Labels: backport-stable-3.2, backport-stable-4.0

#3782 tox: Refact lvm-osds scenario
  plugins/actions/validate.py
  tests/functional/bs-lvm-osds/Vagrantfile
  tests/functional/bs-lvm-osds/ceph-override.json
  tests/functional/bs-lvm-osds/container/Vagrantfile
  tests/functional/bs-lvm-osds/container/ceph-override.json
  tests/functional/bs-lvm-osds/container/group_vars/all
  tests/functional/bs-lvm-osds/container/hosts
  tests/functional/bs-lvm-osds/container/vagrant_variables.yml
  tests/functional/bs-lvm-osds/group_vars/all
  tests/functional/bs-lvm-osds/hosts
  tests/functional/bs-lvm-osds/hosts-ubuntu
  tests/functional/bs-lvm-osds/vagrant_variables.yml
  tests/functional/lvm-osds/container/group_vars/all
  tests/functional/lvm-osds/container/hosts
  tests/functional/lvm-osds/container/vagrant_variables.yml
  tests/functional/lvm-osds/group_vars/all
  tests/functional/lvm-osds/hosts
  tests/functional/lvm-osds/vagrant_variables.yml
  tox.ini
Labels: backport-stable-3.2, backport-stable-4.0

#3912 refactor role ceph-mds
  roles/ceph-mds/tasks/create_mds_filesystems.yml
Labels: backport-stable-4.0

#3913 ceph-rbd-mirror: use blocks for similar tasks in main.yml
  roles/ceph-rbd-mirror/tasks/main.yml
Labels: backport-stable-4.0

#3954 igw: Fix rolling update service ordering
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-3.2, backport-stable-4.0, bug

#3960 Set the rgw_create_pools pools application to rgw
  roles/ceph-rgw/tasks/main.yml
Labels: backport-stable-4.0

#3962 Update RHCS version with Nautilus
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  rhcs_edits.txt
  roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install.yml
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0, enhancement

#3967 ceph-nfs: fixed condition for "stable repos specific tasks"
  roles/ceph-nfs/tasks/pre_requisite_non_container_debian.yml
Labels: backport-stable-4.0

#3973 gather-ceph-logs: fix logs list generation
  infrastructure-playbooks/gather-ceph-logs.yml
Labels: backport-stable-4.0, bug

#3969 ceph-nfs: fixed with_items
  roles/ceph-nfs/tasks/pre_requisite_non_container.yml
Labels: backport-stable-4.0

#3963 container-common: allow podman for other distros
  roles/ceph-container-common/tasks/pre_requisites/prerequisites.yml
  roles/ceph-container-common/vars/RedHat-8.yml
Labels: backport-stable-4.0, enhancement

#3979 purge-docker-cluster: remove docker data
  infrastructure-playbooks/purge-docker-cluster.yml
Labels: backport-stable-4.0, enhancement

#3982 tests: fix a typo in dev_setup.yml
  tests/functional/dev_setup.yml
Labels: backport-stable-4.0

#3985 shrink_osd: mark all osd(s) out in one command
  infrastructure-playbooks/shrink-osd.yml
Labels: backport-stable-4.0

#3989 purge-docker-cluster: don't remove data on atomic
  infrastructure-playbooks/purge-docker-cluster.yml
Labels: backport-stable-4.0, bug

#3900 tox: Don't copy infrastructure playbook
  tox-update.ini
  tox.ini
Labels: backport-stable-4.0, enhancement

#3998 dashboard: move the call to ceph-node-exporter
  site-container.yml.sample
Labels: backport-stable-4.0

#3996 common: install dependencies for apt modules
  roles/ceph-common/tasks/installs/debian_community_repository.yml
  roles/ceph-container-common/tasks/pre_requisites/debian_prerequisites.yml
Labels: backport-stable-4.0, bug

#4014 config: fix ipv6
  roles/ceph-config/templates/ceph.conf.j2
Labels: backport-stable-4.0

#4015 ceph-prometheus: fix error in templates
  roles/ceph-prometheus/tasks/main.yml
  roles/ceph-prometheus/templates/alertmanager.service.j2
  roles/ceph-prometheus/templates/prometheus.service.j2
Labels: backport-stable-4.0, bug

#4013 common: use gnupg instead of gpg
  roles/ceph-common/tasks/installs/debian_community_repository.yml
  roles/ceph-container-common/tasks/pre_requisites/debian_prerequisites.yml
Labels: backport-stable-4.0, bug

#3997 ceph-mgr: install python-routes for dashboard
  roles/ceph-mgr/tasks/pre_requisite.yml
Labels: backport-stable-4.0, bug

#4024 tests: add retries on failing tests in testinfra
  tests/requirements.txt
  tox-dashboard.ini
  tox-update.ini
  tox.ini
Labels: backport-stable-4.0, enhancement

#4030 Sync config_template from upstream
  plugins/actions/config_template.py
Labels: backport-stable-4.0, enhancement
