Repository ceph/ceph-ansible, pull requests merged in 2019-11, with the labels that each got.

#4706 tests/requirements: bump testinfra and pytest
  tests/requirements.txt
Labels: backport-stable-4.0, enhancement

#4716 ceph-osd: fix fs.aio-max-nr sysctl condition
  roles/ceph-osd/tasks/system_tuning.yml
Labels: backport-stable-3.2, backport-stable-4.0, bug

#4709 add-{mon,osd}: run raw install python tasks
  infrastructure-playbooks/add-mon.yml
  infrastructure-playbooks/add-osd.yml
Labels: backport-stable-4.0, bug

#4316 ceph-handler: Use /proc/net/unix for rgw socket
  roles/ceph-handler/templates/restart_rgw_daemon.sh.j2
Labels: backport-stable-4.0

#4713 ceph-validate: add rbdmirror validation
  roles/ceph-validate/tasks/check_rbdmirror.yml
  roles/ceph-validate/tasks/main.yml
Labels: backport-stable-4.0, bug

#4736 ceph_key: restore file mode after a key is fetched
  library/ceph_key.py
Labels: backport-stable-3.2, backport-stable-4.0

#4718 fixes failure of site-docker.yml due to unnecessary validation of ceph_repository_type
  roles/ceph-validate/tasks/main.yml
Labels: backport-stable-3.2, backport-stable-4.0

#4711 ceph-defaults: pin prometheus container tags
  group_vars/all.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0, enhancement

#4739 container: add always tag on gather fact tasks
  site-container.yml.sample
Labels: backport-stable-3.2, backport-stable-4.0, bug

#4747 Fixes failure of cephfs configuration using --limit while running purge-docker.yml
  roles/ceph-mds/tasks/common.yml
  roles/ceph-mds/tasks/create_mds_filesystems.yml
Labels: backport-stable-4.0

#4751 tox-podman: use centos 8 vagrant image
  roles/ceph-container-engine/tasks/main.yml
  roles/ceph-container-engine/vars/CentOS-8.yml
  tox-podman.ini
Labels: backport-stable-4.0, enhancement

#4750 upgrade: use flags noout and nodeep-scrub only
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0

#4758 rolling_update: don't enable ceph-mon unit
  infrastructure-playbooks/rolling_update.yml
Labels: bug

#4767 travis: add python 3.7 and 3.8
  .travis.yml
Labels: enhancement

#4771 tests: revert vagrant_variable file name detection
  Vagrantfile
Labels: backport-stable-3.2, backport-stable-4.0

#4775 ceph-grafana: remove ipv6 brakets on wait_for
  roles/ceph-grafana/tasks/configure_grafana.yml
Labels: backport-stable-4.0, bug

#4781 tests: fix cluster health status
  tests/functional/add-mdss/container/group_vars/all
  tests/functional/add-mdss/group_vars/all
  tests/functional/add-mgrs/container/group_vars/all
  tests/functional/add-mgrs/group_vars/all
  tests/functional/add-mons/container/group_vars/all
  tests/functional/add-mons/group_vars/all
  tests/functional/add-osds/container/group_vars/all
  tests/functional/add-osds/group_vars/all
  tests/functional/add-rbdmirrors/container/group_vars/all
  tests/functional/add-rbdmirrors/group_vars/all
  tests/functional/add-rgws/container/group_vars/all
  tests/functional/add-rgws/group_vars/all
  tests/functional/add-rgws/group_vars/rgws
  tests/functional/all_daemons/ceph-override.json
  tests/functional/all_daemons/container/group_vars/all
  tests/functional/all_daemons/container/group_vars/rgws
  tests/functional/all_daemons/group_vars/all
  tests/functional/all_daemons/group_vars/rgws
  tests/functional/collocation/container/group_vars/all
  tests/functional/collocation/container/group_vars/rgws
  tests/functional/collocation/group_vars/all
  tests/functional/collocation/group_vars/rgws
  tests/functional/lvm-auto-discovery/container/group_vars/all
  tests/functional/lvm-auto-discovery/group_vars/all
  tests/functional/lvm-batch/container/group_vars/all
  tests/functional/lvm-batch/group_vars/all
  tests/functional/lvm-osds/container/group_vars/all
  tests/functional/lvm-osds/group_vars/all
  tests/functional/migrate_ceph_disk_to_ceph_volume/group_vars/all
  tests/functional/ooo-collocation/hosts
  tests/functional/podman/group_vars/all
  tests/functional/podman/group_vars/rgws
  tests/functional/rgw-multisite/container/group_vars/all
  tests/functional/rgw-multisite/container/group_vars/rgws
  tests/functional/rgw-multisite/container/secondary/group_vars/all
  tests/functional/rgw-multisite/container/secondary/group_vars/rgws
  tests/functional/rgw-multisite/group_vars/all
  tests/functional/rgw-multisite/group_vars/rgws
  tests/functional/rgw-multisite/secondary/group_vars/all
  tests/functional/rgw-multisite/secondary/group_vars/rgws
  tests/functional/shrink_mds/container/group_vars/all
  tests/functional/shrink_mds/group_vars/all
  tests/functional/shrink_mgr/container/group_vars/all
  tests/functional/shrink_mgr/group_vars/all
  tests/functional/shrink_mon/container/group_vars/all
  tests/functional/shrink_mon/group_vars/all
  tests/functional/shrink_osd/container/group_vars/all
  tests/functional/shrink_rbdmirror/container/group_vars/all
  tests/functional/shrink_rbdmirror/group_vars/all
  tests/functional/shrink_rgw/container/group_vars/all
  tests/functional/shrink_rgw/container/group_vars/rgws
  tests/functional/shrink_rgw/group_vars/all
  tests/functional/shrink_rgw/group_vars/rgws
Labels: enhancement

#4778 purge/update: remove backward compatibility legacy
  infrastructure-playbooks/purge-cluster.yml
  infrastructure-playbooks/purge-docker-cluster.yml
  infrastructure-playbooks/purge-iscsi-gateways.yml
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0

#4777 dashboard: only print dashboard url of the grafana-server node
  roles/ceph-dashboard/tasks/main.yml
Labels: backport-stable-4.0

#4783 ceph-osd: wait for all osds once
  roles/ceph-osd/tasks/main.yml
Labels: bug
