Repository ceph/ceph-ansible, pull requests merged in 2019-09, with the labels that each got.

#4419 Fix discovered_interpreter_python variable
  roles/ceph-facts/tasks/facts.yml
Labels: backport-stable-4.0, bug

#4423 rhcs: Pin downstream containers
  group_vars/rhcs.yml.sample
  rhcs_edits.txt
Labels: backport-stable-4.0, enhancement

#4422 rbd-mirror: configure pool and peer
  group_vars/rbdmirrors.yml.sample
  roles/ceph-rbd-mirror/defaults/main.yml
  roles/ceph-rbd-mirror/tasks/configure_mirroring.yml
  roles/ceph-rbd-mirror/tasks/main.yml
Labels: backport-stable-3.2, backport-stable-4.0, enhancement

#4429 tox: Fix incorrect ANSIBLE_CONFIG value
  tox.ini
Labels: bug

#4426 Support comma-delimited subnets in firewall
  roles/ceph-infra/tasks/configure_firewall.yml
Labels: backport-stable-4.0, enhancement

#4431 Look for additional names when checking ceph-nfs container status
  roles/ceph-handler/tasks/check_running_containers.yml
  roles/ceph-handler/templates/restart_nfs_daemon.sh.j2
  roles/ceph-nfs/tasks/main.yml
Labels: backport-stable-3.2, backport-stable-4.0, bug

#4438 tox-update: set the ansible.cfg path before update
  tox-update.ini
Labels: backport-stable-4.0, bug

#4430 ceph-handler: Fix osd restart condition
  roles/ceph-handler/handlers/main.yml
Labels: backport-stable-3.2, backport-stable-4.0, bug

#4449 shrink-mon: search mon in the quorum_names list
  infrastructure-playbooks/shrink-mon.yml
Labels: backport-stable-4.0, bug

#4448 rhel8: add default python bin path
  raw_install_python.yml
Labels: backport-stable-4.0, bug

#4418 group_vars: remove useless dashboard files
  group_vars/dashboards.yml.sample
  group_vars/grafanas.yml.sample
  group_vars/node-exporters.yml.sample
  group_vars/prometheuss.yml.sample
Labels: backport-stable-4.0

#4460 shrink-rgw.yml: fix confirmation play's name
  infrastructure-playbooks/shrink-rgw.yml
Labels: backport-stable-4.0

#4470 ceph-osd: handle loop devices with containers
  roles/ceph-osd/templates/ceph-osd-run.sh.j2
Labels: bug

#4471 mon: use ceph_key module for containerized mgr keyring creation
  roles/ceph-mon/tasks/docker/main.yml
Labels: bug

#4437 Inject ceph grafana dashboard layouts
  Vagrantfile
  roles/ceph-dashboard/tasks/configure_dashboard.yml
  roles/ceph-facts/tasks/facts.yml
Labels: backport-stable-4.0, enhancement

#4474 dashboard: add grafana dashboard support on Debian based OS
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-grafana/tasks/configure_grafana.yml
  site.yml.sample
Labels: backport-stable-4.0

#4477 ceph-nfs: Allow to configure SecType value
  group_vars/nfss.yml.sample
  roles/ceph-nfs/defaults/main.yml
  roles/ceph-nfs/templates/ganesha.conf.j2
Labels: backport-stable-4.0, enhancement

#4414 ceph-common: install only necesarry ceph-* packages on debian
  roles/ceph-common/vars/main.yml
Labels: backport-stable-4.0

#4479 ceph-dashboard: Add prometheus api host
  roles/ceph-dashboard/tasks/configure_dashboard.yml
Labels: backport-stable-4.0, enhancement

#4339 Replace ipaddr() with ips_in_ranges()
  .travis.yml
  ansible.cfg
  infrastructure-playbooks/purge-cluster.yml
  infrastructure-playbooks/purge-docker-cluster.yml
  plugins/filter/__init__.py
  plugins/filter/ipaddrs_in_ranges.py
  plugins/filter/test_ipaddrs_in_ranges.py
  roles/ceph-facts/tasks/facts.yml
  roles/ceph-facts/tasks/set_monitor_address.yml
  roles/ceph-facts/tasks/set_radosgw_address.yml
  roles/ceph-validate/tasks/check_ipaddr_mon.yml
  tox-podman.ini
  tox-update.ini
  tox.ini
Labels: backport-stable-4.0, enhancement

#4486 update: reset mon_host after mons upgrade
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0

#4488 Revert "ceph-common: install only necesarry ceph-* packages on debian"
  roles/ceph-common/vars/main.yml
Labels: backport-stable-4.0

#4489 tests: remove debug log verbosity
  tests/functional/all_daemons/ceph-override.json
Labels: backport-stable-4.0

#4499 ceph-config: do not always assume containers when calculating num_osds
  roles/ceph-config/tasks/main.yml
Labels: bug
