Repository ceph/ceph-ansible, pull requests merged in 2019-10, with the labels that each got.

#4501 ceph-facts: update external grafana fact filter
  roles/ceph-facts/tasks/facts.yml
Labels: backport-stable-4.0, bug

#4507 ceph-facts: use --admin-daemon to get fsid
  roles/ceph-facts/tasks/facts.yml
Labels: backport-stable-4.0, bug

#4508 common: improve keyrings generation
  roles/ceph-client/tasks/pre_requisite.yml
  roles/ceph-iscsi-gw/tasks/common.yml
  roles/ceph-mds/tasks/common.yml
  roles/ceph-mgr/tasks/common.yml
  roles/ceph-nfs/tasks/pre_requisite_container.yml
  roles/ceph-nfs/tasks/pre_requisite_non_container.yml
  roles/ceph-osd/tasks/common.yml
  roles/ceph-osd/tasks/openstack_config.yml
  roles/ceph-rbd-mirror/tasks/common.yml
  roles/ceph-rgw/tasks/common.yml
Labels: backport-stable-4.0, enhancement

#4522 ceph-facts: fix _radosgw_address with block
  roles/ceph-facts/tasks/set_radosgw_address.yml
Labels: backport-stable-4.0, bug

#4515 ceph-handler: don't restart all OSDs with limit
  roles/ceph-handler/handlers/main.yml
Labels: backport-stable-3.2, backport-stable-4.0, bug

#4516 dashboard: remove useless block section
  infrastructure-playbooks/dashboard.yml
Labels: backport-stable-4.0, enhancement

#4530 ceph-dashboard: add cluster parameter to ceph cmd
  roles/ceph-dashboard/tasks/configure_dashboard.yml
Labels: backport-stable-4.0, bug

#4538 handler: followup on #4519
  roles/ceph-handler/tasks/main.yml
Labels: backport-stable-4.0

#4537 playbook: add missing tags
  site-container.yml.sample
  site.yml.sample
Labels: backport-stable-3.2, backport-stable-4.0

#4540 tests: fix rgw multisite vagrant variables
  tests/functional/rgw-multisite/container/hosts
  tests/functional/rgw-multisite/container/secondary/hosts
  tests/functional/rgw-multisite/container/secondary/vagrant_variables.yml
  tests/functional/rgw-multisite/hosts
  tests/functional/rgw-multisite/secondary/hosts
  tests/functional/rgw-multisite/secondary/vagrant_variables.yml
  tox.ini
Labels: backport-stable-4.0, bug

#4517 ceph-dashboard: Improve https configuration
  roles/ceph-dashboard/tasks/configure_dashboard.yml
Labels: backport-stable-4.0, enhancement

#4514 dashboard: remove rgw api host,port,scheme
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-dashboard/tasks/configure_dashboard.yml
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0, enhancement

#4550 switch_to_containers: optimize ownership change
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
  roles/ceph-facts/tasks/facts.yml
Labels: backport-stable-4.0

#4559 ceph-mgr: fix ceph_key module with container
  roles/ceph-mgr/tasks/common.yml
Labels: bug

#4561 ceph-config: remove container_binary variable
  infrastructure-playbooks/shrink-osd.yml
  roles/ceph-config/tasks/main.yml
Labels: bug

#4560 switch_to_containers: umount osd lockbox partition
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Labels: backport-stable-3.2, backport-stable-4.0, bug

#4575 mergify: Update condition on status success
  .mergify.yml
Labels: backport-stable-3.2, backport-stable-4.0, enhancement

#4568 tests: reduce handler mon and osd delay
  tests/functional/all_daemons/container/group_vars/all
  tests/functional/all_daemons/group_vars/all
  tests/functional/collocation/container/group_vars/all
  tests/functional/collocation/group_vars/all
  tests/functional/lvm-auto-discovery/container/group_vars/all
  tests/functional/lvm-auto-discovery/group_vars/all
  tests/functional/lvm-batch/container/group_vars/all
  tests/functional/lvm-batch/group_vars/all
  tests/functional/lvm-osds/container/group_vars/all
  tests/functional/lvm-osds/group_vars/all
  tests/functional/podman/group_vars/all
Labels: enhancement

#4567 dashboard: update layouts before the restart
  roles/ceph-dashboard/tasks/configure_dashboard.yml
Labels: backport-stable-4.0, bug

#4578 dashboard: do not fail in case of external ceph cluster
  infrastructure-playbooks/dashboard.yml
Labels: backport-stable-4.0, bug

#4566 validate: prevent from installing OSD on same disk as the OS
  roles/ceph-validate/tasks/check_devices.yml
Labels: backport-stable-3.2, backport-stable-4.0

#4564 common: do not reset `container_exec_cmd`
  roles/ceph-mds/tasks/containerized.yml
  roles/ceph-mds/tasks/main.yml
  roles/ceph-nfs/tasks/pre_requisite_container.yml
  roles/ceph-nfs/tasks/pre_requisite_non_container.yml
Labels: backport-stable-4.0

#4582 dashboard: disable facts gathering
  infrastructure-playbooks/dashboard.yml
Labels: backport-stable-4.0, enhancement

#4583 ceph-handler: group listen topics and condition
  roles/ceph-handler/handlers/main.yml
  roles/ceph-handler/tasks/handler_mdss.yml
  roles/ceph-handler/tasks/handler_mgrs.yml
  roles/ceph-handler/tasks/handler_mons.yml
  roles/ceph-handler/tasks/handler_nfss.yml
  roles/ceph-handler/tasks/handler_osds.yml
  roles/ceph-handler/tasks/handler_rbd_target_api.yml
  roles/ceph-handler/tasks/handler_rbd_target_gw.yml
  roles/ceph-handler/tasks/handler_rbdmirrors.yml
  roles/ceph-handler/tasks/handler_rgws.yml
  roles/ceph-handler/tasks/handler_tcmu_runner.yml
Labels: backport-stable-4.0, enhancement

#4584 lint: fix error [303,602,701,702]
  .travis.yml
  roles/ceph-common/tasks/installs/configure_redhat_local_installation.yml
  roles/ceph-dashboard/tasks/configure_dashboard.yml
  roles/ceph-mds/tasks/create_mds_filesystems.yml
  roles/ceph-mon/tasks/ceph_keys.yml
  roles/ceph-osd/tasks/main.yml
  roles/ceph-prometheus/meta/main.yml
  roles/ceph-rgw-loadbalancer/meta/main.yml
Labels: enhancement

#4598 Remove validate action and notario dependency
  ceph-ansible.spec.in
  plugins/actions/validate.py
  requirements.txt
  roles/ceph-validate/tasks/main.yml
  tests/requirements.txt
Labels: backport-stable-4.0, bug, enhancement

#4604 mgr: do not copy all keyrings on all mgr
  roles/ceph-mgr/tasks/common.yml
Labels: backport-stable-4.0, bug

#4607 playbook: remove duplicate facts
  site-container.yml.sample
  site.yml.sample
Labels: backport-stable-4.0, enhancement

#4305 Execute common roles once on all nodes
  infrastructure-playbooks/dashboard.yml
  site-container.yml.sample
  site.yml.sample
Labels: backport-stable-4.0, enhancement

#4585 ceph-iscsi: notify rbd target services
  roles/ceph-config/tasks/main.yml
  roles/ceph-handler/handlers/main.yml
  roles/ceph-handler/tasks/handler_rbd_target_api_gw.yml
  roles/ceph-handler/tasks/handler_rbd_target_gw.yml
  roles/ceph-iscsi-gw/tasks/common.yml
  roles/ceph-iscsi-gw/tasks/systemd.yml
Labels: backport-stable-4.0, enhancement

#4612 nfs: remove unnecessary set_fact in main.yml
  roles/ceph-nfs/tasks/main.yml
Labels: backport-stable-4.0, bug

#4588 update: follow new recommandation to upgrade mds cluster
  infrastructure-playbooks/rolling_update.yml
  roles/ceph-mds/tasks/create_mds_filesystems.yml
Labels: backport-stable-3.2, backport-stable-4.0

#4608 iscsi-gw: Fix rtslib installation
  roles/ceph-iscsi-gw/tasks/non-container/prerequisites.yml
Labels: backport-stable-4.0, bug

#4625 tests: fix the size on the second data LV
  tests/functional/lvm_setup.yml
Labels: backport-stable-3.2, backport-stable-4.0, bug

#4624 common: do not override ceph_release when using custom repo
  roles/ceph-common/tasks/main.yml
Labels: backport-stable-3.2, backport-stable-4.0

#4621 upgrade: fix standby_mdss group creation
  infrastructure-playbooks/rolling_update.yml
  tests/functional/all_daemons/container/group_vars/all
  tests/functional/all_daemons/container/hosts
  tests/functional/all_daemons/container/hosts-ubuntu
  tests/functional/all_daemons/container/vagrant_variables.yml
  tests/functional/all_daemons/group_vars/all
  tests/functional/all_daemons/hosts
  tests/functional/all_daemons/hosts-switch-to-containers
  tests/functional/all_daemons/hosts-ubuntu
  tests/functional/all_daemons/vagrant_variables.yml
Labels: backport-stable-4.0

#4637 update: add missing quotes
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0, enhancement

#4640 travis: fail on ansible-lint errors
  .travis.yml
  roles/ceph-rbd-mirror/tasks/configure_mirroring.yml
Labels: backport-stable-4.0, enhancement

#4642 validate: fix credentials validation
  roles/ceph-validate/tasks/main.yml
Labels: backport-stable-4.0, bug

#4648 container/dashboard: run the registry auth task
  dashboard.yml
  roles/ceph-container-common/tasks/main.yml
  roles/ceph-container-common/tasks/registry.yml
Labels: backport-stable-4.0, bug

#4655 update: skip mds deactivation when no mds in inventory
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-3.2, backport-stable-4.0

#4664 openstack_config: fix docker exec command
  roles/ceph-osd/tasks/openstack_config.yml
Labels: bug

#4665 defaults: add user/pass auth registry variables
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0, enhancement

#4663 add-{mon,osd}: add ceph-container-engine role
  infrastructure-playbooks/add-mon.yml
  infrastructure-playbooks/add-osd.yml
Labels: backport-stable-4.0, bug

#4672 rolling_update: fix reset mon_host variable
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0, bug

#4671 add-mon: add missing become flag
  infrastructure-playbooks/add-mon.yml
Labels: backport-stable-4.0, bug

#4677 rolling_update: fix active mds host value
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-3.2, backport-stable-4.0, bug

#4687 ceph-nfs: add nfs-ganesha-rados-grace explicitly
  roles/ceph-nfs/tasks/pre_requisite_non_container_red_hat.yml
Labels: bug

#4692 update: add default values when setting fact
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0, bug

#4689 Ceph RGW nfs user modify to specific defined access key and secret key
  roles/ceph-nfs/tasks/create_rgw_nfs_user.yml
Labels: enhancement

#4685 ceph-mon: use --admin-daemon to set default crush rule
  roles/ceph-mon/tasks/crush_rules.yml
Labels: backport-stable-4.0, enhancement

#4696 ceph-osd: Remove ulimit nofile on container start
  roles/ceph-osd/templates/ceph-osd-run.sh.j2
Labels: backport-stable-3.2, backport-stable-4.0, bug

#4702 ceph-defaults: pin grafana container tag to 5.2.4
  group_vars/all.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0, enhancement
