Repository ceph/ceph-ansible, pull requests merged in 2019-08, with the labels that each got.

#4292 dashboard: do not deploy on Debian based OS/non-containerized
  site.yml.sample
Labels: backport-stable-4.0

#4287 rgw: add beast frontend
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-config/templates/ceph.conf.j2
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-validate/tasks/main.yml
Labels: feature

#4290 ceph-grafana: Set grafana uid/gid on files
  roles/ceph-grafana/tasks/configure_grafana.yml
  roles/ceph-grafana/tasks/setup_container.yml
Labels: backport-stable-4.0, enhancement

#4293 ceph-infra: Apply firewall rules with container
  roles/ceph-infra/tasks/configure_firewall.yml
Labels: backport-stable-4.0, enhancement

#4276 openSUSE: support newer Leap releases
  roles/ceph-validate/tasks/check_system.yml
Labels: backport-stable-4.0

#4309 shrink-osd: Stop ceph-disk container based on ID
  infrastructure-playbooks/shrink-osd-ceph-disk.yml
Labels: bug

#4315 mgr: refact 'wait for all mgr to be up' task
  roles/ceph-mgr/tasks/mgr_modules.yml
Labels: backport-stable-4.0

#4335 doc: update backport section
  CONTRIBUTING.md
Labels: backport-stable-3.2, backport-stable-4.0

#4344 osd: remove useless condition
  roles/ceph-osd/tasks/openstack_config.yml
Labels: backport-stable-4.0

#4334 validate: do not validate devices/lvm_volumes in osd_auto_discovery case
  plugins/actions/validate.py
Labels: backport-stable-3.2, backport-stable-4.0

#4349 common: remove duplicate task installing suse dependencies
  roles/ceph-common/tasks/installs/install_on_suse.yml
Labels: backport-stable-4.0

#4350 handler: do not validate the server certificate against the CA
  roles/ceph-handler/templates/restart_rgw_daemon.sh.j2
Labels: backport-stable-4.0

#4341 install ceph-mds packages on SUSE/openSUSE
  roles/ceph-mds/tasks/non_containerized.yml
Labels: backport-stable-4.0

#4343 validate: fail on openSUSE Leap using distro packages
  roles/ceph-validate/tasks/check_nfs.yml
Labels: backport-stable-4.0

#4323 Set proper ownership command performance improvement
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Labels: backport-stable-4.0

#4317 ceph-osd: Add ulimit nofile on container start
  library/ceph_volume.py
  library/test_ceph_volume.py
  roles/ceph-osd/tasks/start_osds.yml
  roles/ceph-osd/templates/ceph-osd-run.sh.j2
Labels: backport-stable-4.0

#3523 rgw/multisite: assign 'rgw_zone' to the exact section in ceph.conf
  roles/ceph-rgw/tasks/multisite/main.yml
Labels: backport-stable-4.0

#4390 ceph-osd: Add ulimit nofile on container start
  library/ceph_volume.py
  library/test_ceph_volume.py
  roles/ceph-osd/tasks/scenarios/collocated.yml
  roles/ceph-osd/tasks/scenarios/non-collocated.yml
  roles/ceph-osd/tasks/start_osds.yml
  roles/ceph-osd/templates/ceph-osd-run.sh.j2
Labels: enhancement

#4389 ceph-mon: Bind mount the ca-trust directory
  roles/ceph-mon/templates/ceph-mon.service.j2
Labels: backport-stable-4.0, enhancement

#4375 generating cluster fsid failed if ansible_python_interpreter is set
  roles/ceph-facts/tasks/facts.yml
Labels: backport-stable-4.0

#4378 fix openSUSE OBS repo creation
  roles/ceph-common/tasks/installs/suse_obs_repository.yml
Labels: backport-stable-4.0

#4365 openSUSE OBS repository using ceph_stable_release
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0

#4383 Add http_addr option to grafana config
  roles/ceph-grafana/tasks/configure_grafana.yml
  roles/ceph-grafana/templates/datasources-ceph-dashboard.yml.j2
  roles/ceph-grafana/templates/grafana.ini.j2
  roles/ceph-prometheus/templates/prometheus.yml.j2
Labels: backport-stable-4.0

#4410 lint: fix error [201,206]
  roles/ceph-container-engine/tasks/pre_requisites/debian_prerequisites.yml
  roles/ceph-rgw/tasks/multisite/master.yml
Labels: backport-stable-4.0, enhancement

#4413 tests: update dedidated mgr node all_daemons
  tests/functional/all_daemons/container/hosts-ubuntu
  tests/functional/all_daemons/hosts-switch-to-containers
  tests/functional/all_daemons/hosts-ubuntu
Labels: bug
