Repository ceph/ceph-ansible, pull requests merged in 2019-06, with the labels that each got.

#4042 ceph-facts: generate fsid on mon node
  roles/ceph-facts/tasks/facts.yml
Labels: backport-stable-4.0, bug

#4033 remove ceph-agent role and references
  .gitignore
  CONTRIBUTING.md
  contrib/push-roles-to-ansible-galaxy.sh
  generate_group_vars_sample.sh
  group_vars/agent.yml.sample
  infrastructure-playbooks/gather-ceph-logs.yml
  infrastructure-playbooks/purge-cluster.yml
  infrastructure-playbooks/purge-docker-cluster.yml
  infrastructure-playbooks/take-over-existing-cluster.yml
  plugins/callback/installer_checkpoint.py
  roles/ceph-agent/LICENSE
  roles/ceph-agent/README.md
  roles/ceph-agent/defaults/main.yml
  roles/ceph-agent/meta/main.yml
  roles/ceph-agent/tasks/main.yml
  roles/ceph-agent/tasks/pre_requisite.yml
  roles/ceph-agent/tasks/start_agent.yml
  roles/ceph-agent/templates/ceph_agent.j2
  site-container.yml.sample
  site.yml.sample
Labels: backport-stable-3.2, backport-stable-4.0, bug

#4046 ceph-nfs: use template module for configuration
  roles/ceph-nfs/tasks/start_nfs.yml
Labels: backport-stable-4.0, bug

#4044 update default rhcs values and docs
  group_vars/all.yml.sample
  group_vars/iscsigws.yml.sample
  group_vars/mdss.yml.sample
  group_vars/mgrs.yml.sample
  group_vars/mons.yml.sample
  group_vars/osds.yml.sample
  group_vars/rbdmirrors.yml.sample
  group_vars/rgws.yml.sample
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-iscsi-gw/defaults/main.yml
  roles/ceph-mds/defaults/main.yml
  roles/ceph-mgr/defaults/main.yml
  roles/ceph-mon/defaults/main.yml
  roles/ceph-osd/defaults/main.yml
  roles/ceph-rbd-mirror/defaults/main.yml
  roles/ceph-rgw/defaults/main.yml
Labels: enhancement

#4035 site-container: update container-engine role
  site-container.yml.sample
Labels: backport-stable-4.0, enhancement

#4003 container-common: support podman on Ubuntu
  roles/ceph-container-engine/tasks/pre_requisites/debian_prerequisites.yml
  roles/ceph-container-engine/tasks/pre_requisites/prerequisites.yml
Labels: backport-stable-4.0, feature

#4058 purge-cluster: clean all ceph repo files
  infrastructure-playbooks/purge-cluster.yml
Labels: backport-stable-4.0, bug

#4060 podman: Add systemd dependency on network.target
  roles/ceph-grafana/templates/grafana-server.service.j2
  roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2
  roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2
  roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2
  roles/ceph-mds/templates/ceph-mds.service.j2
  roles/ceph-mgr/templates/ceph-mgr.service.j2
  roles/ceph-mon/templates/ceph-mon.service.j2
  roles/ceph-nfs/templates/ceph-nfs.service.j2
  roles/ceph-node-exporter/templates/node_exporter.service.j2
  roles/ceph-osd/templates/ceph-osd.service.j2
  roles/ceph-prometheus/templates/alertmanager.service.j2
  roles/ceph-prometheus/templates/prometheus.service.j2
  roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
  roles/ceph-rgw/templates/ceph-radosgw.service.j2
Labels: backport-stable-4.0, enhancement

#4065 spec: bring back possibility to install ceph with custom repo
  ceph-ansible.spec.in
Labels: backport-stable-3.2, backport-stable-4.0

#4066 validate: fail in check_devices at the right task
  roles/ceph-validate/tasks/check_devices.yml
Labels: backport-stable-3.2, backport-stable-4.0

#4074 ceph-node-exporter: use modprobe ansible module
  roles/ceph-node-exporter/tasks/setup_container.yml
  roles/ceph-node-exporter/templates/node_exporter.service.j2
Labels: backport-stable-4.0, bug

#4076 ceph-node-exporter: Fix systemd template
  roles/ceph-node-exporter/templates/node_exporter.service.j2
Labels: backport-stable-4.0, bug

#4087 dashboard: fix dashboard_url setting
  roles/ceph-dashboard/tasks/configure_dashboard.yml
Labels: backport-stable-4.0

#4086 dashboard: add allow_embedding support
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-grafana/templates/grafana.ini.j2
Labels: backport-stable-4.0

#4088 mon: enforce mon0 delegation for initial_mon_key register
  roles/ceph-mon/tasks/deploy_monitors.yml
Labels: backport-stable-4.0

#4059 ceph-handler: replace fuser by /proc/net/unix
  roles/ceph-handler/tasks/check_socket_non_container.yml
Labels: backport-stable-3.2, backport-stable-4.0, bug

#4096 tox-dashboard: update for nautilus
  tox-dashboard.ini
Labels: enhancement

#4097 iscsi: assign application (rbd) to pool 'rbd'
  roles/ceph-iscsi-gw/tasks/common.yml
  tests/functional/all_daemons/group_vars/all
Labels: backport-stable-3.2, backport-stable-4.0

#2510 align cephfs pool creation
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-mds/tasks/create_mds_filesystems.yml
  roles/ceph-nfs/tasks/start_nfs.yml
  roles/ceph-nfs/templates/ganesha.conf.j2
  tests/functional/all_daemons/ceph-override.json
  tests/functional/all_daemons/group_vars/all
  tests/functional/ooo-collocation/hosts
Labels: backport-stable-4.0

#4101 ceph-infra: update cache for Ubuntu
  roles/ceph-infra/tasks/main.yml
Labels: backport-stable-4.0

#4089 ceph-infra: make chronyd default NTP daemon
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-facts/tasks/facts.yml
  roles/ceph-infra/tasks/setup_ntp.yml
Labels: backport-stable-4.0

#4106 tests: increase docker pull timeout
  tests/functional/all_daemons/container/group_vars/all
Labels: backport-stable-4.0

#4110 tests: Update ansible ssh_args variable
  ansible.cfg
  roles/ceph-config/tasks/create_ceph_initial_dirs.yml
  tox-dashboard.ini
  tox-podman.ini
  tox-update.ini
  tox.ini
Labels: backport-stable-4.0

#4107 dashboard: fix hosts sections in main playbook
  site-container.yml.sample
  site.yml.sample
Labels: backport-stable-4.0

#4118 remove ceph restapi references
  contrib/push-roles-to-ansible-galaxy.sh
  infrastructure-playbooks/gather-ceph-logs.yml
  tests/functional/lvm-auto-discovery/container/vagrant_variables.yml
  tests/functional/lvm-batch/container/vagrant_variables.yml
  tests/functional/lvm-osds/container/vagrant_variables.yml
  tests/functional/rgw-multisite/container/secondary/vagrant_variables.yml
  tests/functional/rgw-multisite/container/vagrant_variables.yml
Labels: backport-stable-4.0

#4119 Add installer phase for dashboard roles
  plugins/callback/installer_checkpoint.py
  site-container.yml.sample
  site.yml.sample
Labels: backport-stable-4.0, enhancement

#4126 roles: Remove useless become (true) flag
  roles/ceph-common/tasks/installs/configure_redhat_local_installation.yml
  roles/ceph-iscsi-gw/tasks/container/containerized.yml
  roles/ceph-mgr/tasks/start_mgr.yml
  roles/ceph-mon/tasks/start_monitor.yml
  roles/ceph-nfs/tasks/pre_requisite_container.yml
  roles/ceph-nfs/tasks/start_nfs.yml
  roles/ceph-osd/tasks/start_osds.yml
  roles/ceph-rbd-mirror/tasks/docker/start_docker_rbd_mirror.yml
  roles/ceph-rgw/tasks/docker/start_docker_rgw.yml
Labels: backport-stable-4.0, enhancement

#4133 facts: add a retry on get current fsid task
  roles/ceph-facts/tasks/facts.yml
Labels: backport-stable-4.0

#4132 ceph-volume: Set max open files limit on container
  library/ceph_volume.py
  library/test_ceph_volume.py
  roles/ceph-osd/tasks/start_osds.yml
Labels: backport-stable-3.2, backport-stable-4.0, bug

#4131 Add higher retry/delay defaults to check the quorum status.
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0

#4129 upgrade: add the possibility to upgrade even when HEALTH_WARN
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0

#4135 Change ansible_lsb by ansible_distribution_release
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-common/tasks/installs/debian_community_repository.yml
  roles/ceph-common/tasks/installs/debian_custom_repository.yml
  roles/ceph-common/tasks/installs/debian_dev_repository.yml
  roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install_debian.yml
  roles/ceph-common/tasks/installs/prerequisite_rhcs_iso_install_debian.yml
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-nfs/tasks/pre_requisite_non_container_debian.yml
Labels: backport-stable-4.0, enhancement

#4140 ceph-handler: Fix OSD restart script
  roles/ceph-handler/templates/restart_osd_daemon.sh.j2
Labels: backport-stable-3.2, backport-stable-4.0, bug

#4146 ceph-disk: Set max open files limit on container
  roles/ceph-osd/tasks/scenarios/collocated.yml
  roles/ceph-osd/tasks/scenarios/non-collocated.yml
Labels: enhancement

#4158 validate.py: Fix alphabetical order on uca
  plugins/actions/validate.py
Labels: backport-stable-3.2, backport-stable-4.0, bug

#4153 facts: fix bug in grafana_server_addr fact setting
  roles/ceph-facts/tasks/facts.yml
Labels: backport-stable-4.0

#4128 Set grafana_server_addr fact for ipv6 scenarios.
  roles/ceph-facts/tasks/facts.yml
Labels: backport-stable-4.0

#4168 ceph-osd: Add CONTAINER_IMAGE env variable
  roles/ceph-osd/templates/ceph-osd-run.sh.j2
Labels: backport-stable-4.0, bug

#4166 containers: improve logging
  roles/ceph-config/templates/ceph.conf.j2
  roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2
  roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2
  roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2
  roles/ceph-mds/templates/ceph-mds.service.j2
  roles/ceph-mgr/templates/ceph-mgr.service.j2
  roles/ceph-mon/templates/ceph-mon.service.j2
  roles/ceph-nfs/templates/ceph-nfs.service.j2
  roles/ceph-osd/templates/ceph-osd-run.sh.j2
  roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
  roles/ceph-rgw/templates/ceph-radosgw.service.j2
Labels: backport-stable-4.0

#4143 nfs: clean template
  roles/ceph-nfs/templates/ganesha.conf.j2
Labels: backport-stable-4.0
