Repository ceph/ceph-ansible, pull requests merged in 2019-03, with the labels that each got.

#3641 Extends check_devices tasks to non-collocated an lvm-batch scenarios
  roles/ceph-validate/tasks/check_devices.yml
  roles/ceph-validate/tasks/main.yml
Labels: backport-stable-3.2

#3662 purge: fix purge of lvm devices
  infrastructure-playbooks/purge-cluster.yml
Labels: backport-stable-3.2

#3673 common: Add noarch to community repository
  roles/ceph-common/tasks/installs/redhat_community_repository.yml
Labels: enhancement

#3692 ceph_key: Use client name to build key path
  library/ceph_key.py
Labels: enhancement

#3686 common: Use rhsm_repository module for RHCS
  roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install.yml
Labels: enhancement

#3696 systemd/service: Set docker.service conditionally
  roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2
  roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2
  roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2
  roles/ceph-mds/templates/ceph-mds.service.j2
  roles/ceph-mgr/templates/ceph-mgr.service.j2
  roles/ceph-mon/templates/ceph-mon.service.j2
  roles/ceph-nfs/templates/ceph-nfs.service.j2
  roles/ceph-osd/templates/ceph-osd.service.j2
  roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
  roles/ceph-rgw/templates/ceph-radosgw.service.j2
Labels: enhancement

#3698 add-osd.yml: Add become flag for ceph-validate
  infrastructure-playbooks/add-osd.yml
Labels: backport-stable-3.2, bug

#3705 ceph-osd: Install numactl package when needed
  roles/ceph-osd/tasks/main.yml
Labels: backport-stable-3.2

#3697 Set the default crush rule in ceph.conf
  roles/ceph-config/templates/ceph.conf.j2
  roles/ceph-defaults/vars/main.yml
  roles/ceph-facts/tasks/facts.yml
  roles/ceph-mon/tasks/crush_rules.yml
Labels: backport-stable-3.2, bug

#3677 ceph-mgr: run mgr_modules.yml only on the first mgr host
  roles/ceph-mgr/tasks/main.yml
Labels: enhancement

#3719 ceph-common: Install yum plugin priorities
  roles/ceph-common/tasks/installs/redhat_community_repository.yml
Labels: enhancement

#3713 ceph-validate: fail if there's no ipaddr available in monitor_address…
  roles/ceph-validate/tasks/check_ipaddr_mon.yml
  roles/ceph-validate/tasks/main.yml
Labels: backport-stable-3.2, bug

#3700 osd: backward compatibility with old disk_list.sh location
  roles/ceph-osd/tasks/start_osds.yml
  roles/ceph-osd/vars/main.yml
Labels: backport-stable-3.2

#3688 Remove trailing forward slash in ceph_docker_registry variable from g…
  group_vars/rhcs.yml.sample
  rhcs_edits.txt
Labels: backport-stable-3.2, bug

#3725 ceph_volume: fix rstrip for python 3
  library/ceph_volume.py
Labels: bug

#3726 ceph_crush: fix rstrip for python 3
  library/ceph_crush.py
Labels: backport-stable-3.2, bug

#3732 ceph-osd: Ensure lvm2 is installed
  roles/ceph-osd/tasks/main.yml
Labels: backport-stable-3.2, bug

#3740 Add uca to ceph_repository choices validation
  plugins/actions/validate.py
Labels: backport-stable-3.2, bug

#3741 travis: Remove galaxy lint rules repository
  .travis.yml
Labels: enhancement

#3708 rolling_update: Update systemd unit regex for nvme
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-3.2, bug

#3747 tests/functional: Use the ansible reboot module
  tests/functional/reboot.yml
Labels: enhancement

#3750 container: Add python3-docker on Ubuntu bionic
  roles/ceph-container-common/tasks/pre_requisites/prerequisites.yml
Labels: bug

#3731 purge-docker-cluster: Remove ceph-osd service
  infrastructure-playbooks/purge-docker-cluster.yml
Labels: backport-stable-3.2, bug
