Repository ceph/ceph-ansible, pull requests merged in 2019-01, with the labels that each got.

#3470 update: do not enforce `serial: 1` on client nodes
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-3.2

#3488 site: Make sure is_atomic is defined
  site.yml.sample
Labels: backport-stable-3.2, bug

#3535 Fix ceph.conf generation
  roles/ceph-config/templates/ceph.conf.j2
Labels: bug

#3539 use shortname in keyring path
  library/ceph_key.py
Labels: backport-stable-3.1, backport-stable-3.2, bug
