Repository ceph/ceph-ansible, pull requests merged in 2019-12, with the labels that each got.

#4788 switch_to_containers: fix umount ceph partitions
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Labels: backport-stable-3.2, backport-stable-4.0, bug

#4792 docker2podman: various fixes
  infrastructure-playbooks/docker-to-podman.yml
  roles/ceph-handler/handlers/main.yml
Labels: backport-stable-4.0, bug

#4799 dashboard: use fqdn url for active alert
  roles/ceph-prometheus/templates/alertmanager.yml.j2
Labels: backport-stable-4.0, blocker, bug

#4805 purge: rename playbook (container)
  infrastructure-playbooks/purge-container-cluster.yml
  infrastructure-playbooks/purge-docker-cluster.yml
  tox-podman.ini
  tox.ini
Labels: backport-stable-4.0

#4814 tests: reduce max_mds from 3 to 2
  tests/functional/all_daemons/container/group_vars/all
  tests/functional/all_daemons/group_vars/all
Labels: backport-stable-3.2, backport-stable-4.0, enhancement

#4812 purge-cluster: add podman support
  infrastructure-playbooks/purge-cluster.yml
  infrastructure-playbooks/purge-container-cluster.yml
Labels: backport-stable-4.0, enhancement

#4819 ceph-defaults: exclude md devices from discovery
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0, bug

#4822 ceph-facts: move ntp/chrony facts to ceph-infra
  roles/ceph-facts/tasks/facts.yml
  roles/ceph-infra/tasks/setup_ntp.yml
Labels: enhancement

#4829 ceph-validate: start with ansible version test
  roles/ceph-validate/tasks/check_iscsi.yml
  roles/ceph-validate/tasks/check_system.yml
  roles/ceph-validate/tasks/main.yml
Labels: enhancement

#4804 dashboard: run node_export as privileged container
  roles/ceph-node-exporter/templates/node_exporter.service.j2
Labels: backport-stable-4.0

#4832 switch_to_containers: exclude clients nodes from facts gathering
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Labels: backport-stable-4.0

#4835 shrink-osd: support fqdn in inventory
  infrastructure-playbooks/shrink-osd.yml
Labels: backport-stable-3.2, backport-stable-4.0

#4841 defaults: add a comment
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0

#4839 ansible.cfg: do not enforce PreferredAuthentications
  ansible.cfg
Labels: backport-stable-3.2, backport-stable-4.0, enhancement

#4852 ceph-facts: set use_new_ceph_iscsi on iscsi nodes
  roles/ceph-facts/tasks/facts.yml
  roles/ceph-validate/tasks/check_iscsi.yml
Labels: enhancement

#4834 ceph-osd: update systemd unit script
  roles/ceph-osd/templates/ceph-osd.service.j2
Labels: bug

#4863 ceph-defaults: exclude rbd devices from discovery
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-3.2, backport-stable-4.0, bug

#4864 ceph-defaults: regenerate group_vars samples
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
Labels: bug

#4871 filestore-to-bluestore: umount partitions before zapping them
  infrastructure-playbooks/filestore-to-bluestore.yml
Labels: backport-stable-4.0
