Repository ceph/ceph-ansible, pull requests merged in 2020-09, with the labels that each got.

#5712 Fix typo shrink osd file name in day-2 docs
  docs/source/day-2/osds.rst
Labels: documentation

#5738 Add --cluster option on ceph require-osd-release command
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5744 [skip ci] Fix hosts field in rolling_update playbook when mds are processed
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5745 tests: use grafana from quay.io
  tests/functional/all_daemons/container/group_vars/all
  tests/functional/all_daemons/group_vars/all
  tests/functional/collocation/container/group_vars/all
  tests/functional/collocation/group_vars/all
  tests/functional/docker2podman/group_vars/all
  tests/functional/podman/group_vars/all
Labels: enhancement, tests

#5748 ceph-rgw: use ceph_pool module
  roles/ceph-rgw/tasks/rgw_create_pools.yml
Labels: backport-stable-5.0, enhancement

#5758 tests: add quay registry for collocation baremetal
  tests/functional/collocation/group_vars/all
Labels: bug, tests

#5760 tests: migrate to quay.ceph.io registry
  docs/source/testing/tox.rst
  library/test_ceph_volume.py
  tests/functional/add-osds/container/group_vars/all
  tests/functional/all-in-one/container/group_vars/all
  tests/functional/all_daemons/container/group_vars/all
  tests/functional/all_daemons/group_vars/all
  tests/functional/bs-lvm-osds/container/group_vars/all
  tests/functional/collocation/container/group_vars/all
  tests/functional/collocation/group_vars/all
  tests/functional/docker2podman/group_vars/all
  tests/functional/external_clients/container/group_vars/all
  tests/functional/lvm-auto-discovery/container/group_vars/all
  tests/functional/lvm-batch/container/group_vars/all
  tests/functional/lvm-osds/container/group_vars/all
  tests/functional/ooo-collocation/hosts
  tests/functional/rgw-multisite/container/group_vars/all
  tests/functional/rgw-multisite/container/secondary/group_vars/all
  tests/functional/shrink_mon/container/group_vars/all
  tests/functional/shrink_osd/container/group_vars/all
  tests/functional/shrink_osd_legacy/container/group_vars/all
  tox-docker2podman.ini
  tox-external_clients.ini
  tox-update.ini
  tox.ini
Labels: tests

#5668 Allow updating crush rule on existing pool
  roles/ceph-client/tasks/create_users_keys.yml
  roles/ceph-mds/tasks/create_mds_filesystems.yml
  roles/ceph-osd/tasks/openstack_config.yml
Labels: feature

#5750 ceph_pool: use default size/min_size and rule_name
  roles/ceph-client/tasks/create_users_keys.yml
  roles/ceph-mds/tasks/create_mds_filesystems.yml
  roles/ceph-osd/tasks/openstack_config.yml
Labels: backport-stable-5.0, enhancement

#5729 library: add ceph_dashboard_user module
  library/ceph_dashboard_user.py
  roles/ceph-dashboard/tasks/configure_dashboard.yml
  tests/library/test_ceph_dashboard_user.py
Labels: backport-stable-5.0, feature

#5751 [skip ci] ceph_pool: set state as optional
  library/ceph_pool.py
  roles/ceph-client/tasks/create_users_keys.yml
  roles/ceph-iscsi-gw/tasks/common.yml
  roles/ceph-mds/tasks/create_mds_filesystems.yml
  roles/ceph-osd/tasks/openstack_config.yml
Labels: backport-stable-5.0, enhancement

#5770 [skip ci] node-exporter: exclude client nodes
  dashboard.yml
  roles/ceph-prometheus/templates/prometheus.yml.j2
Labels: backport-stable-4.0, backport-stable-5.0

#5709 dashboard: use run_once at block level
  roles/ceph-dashboard/tasks/configure_dashboard.yml
Labels: backport-stable-4.0, backport-stable-5.0, enhancement

#5776 [skip ci] tests/library: rename ceph_dashboard_user class
  tests/library/test_ceph_dashboard_user.py
Labels: backport-stable-5.0, enhancement

#5769 [skip ci] purge: remove potential socket leftover
  infrastructure-playbooks/purge-cluster.yml
  infrastructure-playbooks/purge-container-cluster.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5708 ansible: bump to ansible 2.9
  ceph-ansible.spec.in
  requirements.txt
  roles/ceph-validate/tasks/check_system.yml
  tests/requirements.txt
Labels: enhancement

#5785 [skip ci] switch2container: fixes for running containers on Debian based host
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Labels: backport-stable-3.2, backport-stable-4.0, backport-stable-5.0

#5786 container: add optional http(s) proxy option
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-container-common/tasks/fetch_image.yml
  roles/ceph-container-common/tasks/registry.yml
  roles/ceph-container-engine/tasks/pre_requisites/prerequisites.yml
  roles/ceph-container-engine/templates/docker-proxy.conf.j2
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0, backport-stable-5.0, feature

#5784 [skip ci] ceph-prometheus: update pool stat counter
  roles/ceph-prometheus/files/ceph_dashboard.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5780 [skip ci] infra: support log rotation for tcmu-runner
  roles/ceph-infra/templates/logrotate.conf.j2
  roles/ceph-iscsi-gw/tasks/containerized.yml
  roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2
Labels: backport-stable-4.0, backport-stable-5.0

#5800 [skip ci] ceph-infra: include iscsi nodes for logrotate
  roles/ceph-infra/tasks/main.yml
  roles/ceph-infra/templates/logrotate.conf.j2
Labels: backport-stable-4.0, backport-stable-5.0

#5789 switch2container: fixes for running containers on Debian based host (bp #5785)
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Labels: bug

#5804 [skip ci] facts: fix 'set_fact rgw_instances with rgw multisite'
  roles/ceph-facts/tasks/set_radosgw_address.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5805 [skip ci] container: quote registry password
  roles/ceph-container-common/tasks/registry.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5820 [skip ci] Remove libjemalloc1 installation task
  roles/ceph-nfs/tasks/pre_requisite_non_container_debian.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5823 [skip ci] library/ceph_key: set no_log on secret
  library/ceph_key.py
Labels: backport-stable-3.2, backport-stable-4.0, backport-stable-5.0

#5833 docs: update URLs to point to the RTD links
  README.rst
Labels: backport-stable-3.2, backport-stable-4.0, backport-stable-5.0, documentation

#5840 [skip ci] ceph-config: remove ceph_release from ceph.conf.j2
  roles/ceph-config/templates/ceph.conf.j2
Labels: backport-stable-4.0, backport-stable-5.0, enhancement

#5838 rolling_update: remove msgr2 migration
  infrastructure-playbooks/rolling_update.yml
  roles/ceph-config/templates/ceph.conf.j2
Labels: enhancement

#5724 [skip ci] ceph_pool: add idempotency to absent state
  library/ceph_pool.py
Labels: backport-stable-5.0, bug

#5774 [skip ci] ceph-rgw: remove ceph_pool state and default value
  roles/ceph-rgw/tasks/rgw_create_pools.yml
Labels: backport-stable-5.0

#5722 [skip ci] README-MULTISITE: Fix syntax issues reported by markdownlint
  README-MULTISITE.md
Labels: backport-stable-4.0, backport-stable-5.0, documentation

#5717 library: Fix new-style modules check mode
  library/ceph_crush.py
  library/ceph_key.py
  library/ceph_pool.py
  library/ceph_volume.py
Labels: backport-stable-5.0

#5584 facts: support device aliases for (dedicated|bluestore_wal)_devices
  roles/ceph-facts/tasks/facts.yml
Labels: backport-stable-5.0

#5538 [skip ci] Update methods.rst
  docs/source/installation/methods.rst
Labels: backport-stable-5.0

#5856 ceph-mds: remove unused block condition
  roles/ceph-mds/tasks/create_mds_filesystems.yml
Labels: backport-stable-5.0, enhancement

#5853 Revert "ceph-rgw: remove ceph_pool state and default value"
  roles/ceph-rgw/tasks/rgw_create_pools.yml
Labels: backport-stable-5.0

#5841 add missing boolean filter
  infrastructure-playbooks/filestore-to-bluestore.yml
  infrastructure-playbooks/rolling_update.yml
  infrastructure-playbooks/shrink-osd.yml
  infrastructure-playbooks/storage-inventory.yml
  roles/ceph-client/tasks/create_users_keys.yml
  roles/ceph-client/tasks/pre_requisite.yml
  roles/ceph-common/tasks/installs/install_debian_packages.yml
  roles/ceph-common/tasks/installs/prerequisite_rhcs_iso_install.yml
  roles/ceph-common/vars/main.yml
  roles/ceph-config/tasks/main.yml
  roles/ceph-config/tasks/rgw_systemd_environment_file.yml
  roles/ceph-config/templates/ceph.conf.j2
  roles/ceph-crash/tasks/main.yml
  roles/ceph-facts/tasks/facts.yml
  roles/ceph-handler/templates/restart_mds_daemon.sh.j2
  roles/ceph-handler/templates/restart_mgr_daemon.sh.j2
  roles/ceph-handler/templates/restart_mon_daemon.sh.j2
  roles/ceph-handler/templates/restart_nfs_daemon.sh.j2
  roles/ceph-handler/templates/restart_osd_daemon.sh.j2
  roles/ceph-handler/templates/restart_rbd_mirror_daemon.sh.j2
  roles/ceph-iscsi-gw/tasks/common.yml
  roles/ceph-mds/tasks/common.yml
  roles/ceph-mds/tasks/create_mds_filesystems.yml
  roles/ceph-mds/tasks/non_containerized.yml
  roles/ceph-mgr/tasks/common.yml
  roles/ceph-mgr/tasks/main.yml
  roles/ceph-mgr/tasks/pre_requisite.yml
  roles/ceph-mon/tasks/ceph_keys.yml
  roles/ceph-mon/tasks/deploy_monitors.yml
  roles/ceph-mon/tasks/start_monitor.yml
  roles/ceph-mon/templates/ceph-mon.service.j2
  roles/ceph-nfs/tasks/main.yml
  roles/ceph-nfs/tasks/pre_requisite_container.yml
  roles/ceph-nfs/tasks/pre_requisite_non_container.yml
  roles/ceph-nfs/tasks/pre_requisite_non_container_red_hat.yml
  roles/ceph-nfs/templates/ceph-nfs.service.j2
  roles/ceph-nfs/templates/ganesha.conf.j2
  roles/ceph-osd/tasks/common.yml
  roles/ceph-osd/tasks/openstack_config.yml
  roles/ceph-osd/tasks/scenarios/lvm-batch.yml
  roles/ceph-osd/tasks/scenarios/lvm.yml
  roles/ceph-osd/tasks/start_osds.yml
  roles/ceph-rbd-mirror/tasks/common.yml
  roles/ceph-rgw/tasks/common.yml
  roles/ceph-rgw/tasks/rgw_create_pools.yml
  roles/ceph-validate/tasks/check_nfs.yml
Labels: enhancement

#5857 ceph-facts: check for mon socket in its own host
  roles/ceph-facts/tasks/facts.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5855 ceph-iscsi: create pool once from monitor
  roles/ceph-iscsi-gw/tasks/common.yml
Labels: backport-stable-5.0, bug

#5852 ceph-handler: set handler on xxx_stat result
  roles/ceph-handler/tasks/main.yml
  roles/ceph-mon/tasks/main.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5846 Remove unused centos docker tasks
  Vagrantfile
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-container-engine/tasks/pre_requisites/prerequisites.yml
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-osd/tasks/start_osds.yml
  tests/functional/all-in-one/container/group_vars/all
  tests/functional/all-in-one/group_vars/all
  tests/functional/all_daemons/container/group_vars/all
  tests/functional/collocation/container/group_vars/all
  tests/functional/collocation/group_vars/all
  tests/functional/docker2podman/group_vars/all
  tests/functional/external_clients/container/inventory/group_vars/all
  tests/functional/external_clients/inventory/group_vars/all
  tests/functional/podman/group_vars/all
  tests/functional/shrink_mds/container/group_vars/all
  tests/functional/shrink_mgr/container/group_vars/all
  tests/functional/shrink_mon/container/group_vars/all
  tests/functional/shrink_osd/container/group_vars/all
  tests/functional/shrink_rbdmirror/container/group_vars/all
  tests/functional/shrink_rgw/container/group_vars/all
Labels: enhancement

#5797 rgw multisite: check connection for realm endpoint
  roles/ceph-rgw/tasks/multisite/secondary.yml
Labels: backport-stable-4.0, backport-stable-5.0, enhancement

#5593 defaults: change default grafana-server name
  Vagrantfile
  dashboard.yml
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  infrastructure-playbooks/cephadm-adopt.yml
  infrastructure-playbooks/cephadm.yml
  infrastructure-playbooks/docker-to-podman.yml
  infrastructure-playbooks/purge-cluster.yml
  infrastructure-playbooks/purge-container-cluster.yml
  infrastructure-playbooks/rolling_update.yml
  roles/ceph-crash/tasks/main.yml
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-defaults/tasks/main.yml
  roles/ceph-facts/tasks/convert_grafana_server_group_name.yml
  roles/ceph-facts/tasks/grafana.yml
  roles/ceph-facts/tasks/main.yml
  roles/ceph-infra/tasks/dashboard_firewall.yml
  roles/ceph-prometheus/templates/prometheus.yml.j2
  roles/ceph-validate/tasks/main.yml
  site-container.yml.sample
  site.yml.sample
  tests/conftest.py
  tests/functional/all_daemons/container/hosts
  tests/functional/all_daemons/group_vars/all
  tests/functional/all_daemons/hosts
  tests/functional/all_daemons/hosts-switch-to-containers
  tests/functional/cephadm/hosts
  tests/functional/collocation/container/hosts
  tests/functional/collocation/hosts
  tests/functional/docker2podman/hosts
  tests/functional/podman/hosts
Labels: backport-stable-5.0

#5858 ceph-facts: add get default crush rule from running monitor
  roles/ceph-facts/tasks/facts.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5821 fs2bs: support `osd_auto_discovery` scenario
  infrastructure-playbooks/filestore-to-bluestore.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5862 mds: support enabling pg autoscaler on rerun
  roles/ceph-mds/tasks/create_mds_filesystems.yml
Labels: bug
