Repository ceph/ceph-ansible, pull requests merged in 2020-10, with the labels that each got.

#5893 ceph-osd: refact `docker_exec_start_osd`
  roles/ceph-osd/tasks/start_osds.yml
Labels: backport-stable-5.0

#5900 ceph_key: remove backward compatibility
  roles/ceph-client/tasks/create_users_keys.yml
  roles/ceph-osd/tasks/main.yml
  roles/ceph-validate/tasks/main.yml
Labels: backport-stable-5.0, enhancement

#5897 [skip ci] flake8: fix pep8 syntax on tests/functional/tests/
  .github/workflows/flake8.yml
  tests/conftest.py
  tests/functional/tests/test_install.py
Labels: backport-stable-4.0, backport-stable-5.0

#5896 [skip ci] flake8: run the workflow conditionally
  .github/workflows/flake8.yml
Labels: backport-stable-5.0, tests

#5878 library: add ceph_fs module
  infrastructure-playbooks/rolling_update.yml
  library/ceph_fs.py
  roles/ceph-mds/tasks/create_mds_filesystems.yml
  tests/library/test_ceph_fs.py
Labels: backport-stable-5.0, feature

#5783 [skip ci] infrastructure-playbooks: drop add-osd playbook
  infrastructure-playbooks/add-osd.yml
  tox.ini
Labels: backport-stable-5.0

#5911 tests: change cephfs pool size
  tests/functional/all_daemons/ceph-override.json
Labels: backport-stable-4.0, backport-stable-5.0

#5718 Fix Ansible check mode for site.yml.sample playbook
  roles/ceph-crash/tasks/main.yml
  roles/ceph-mgr/tasks/common.yml
  roles/ceph-mgr/tasks/mgr_modules.yml
  roles/ceph-mon/tasks/ceph_keys.yml
  roles/ceph-osd/tasks/common.yml
  roles/ceph-osd/tasks/main.yml
  roles/ceph-rgw/tasks/common.yml
  site.yml.sample
Labels: backport-stable-4.0, backport-stable-5.0

#5913 handler: refact check_socket_non_container
  roles/ceph-handler/tasks/check_socket_non_container.yml
  roles/ceph-handler/tasks/main.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5932 ceph-osd: don't start the OSD services twice
  roles/ceph-osd/tasks/start_osds.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5933 ceph-osd: start osd after systemd overrides
  roles/ceph-osd/tasks/start_osds.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5943 ceph-crash: Only deploy key to targeted hosts
  roles/ceph-crash/tasks/main.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5942 ceph-volume: refresh lvm metadata cache
  library/ceph_volume.py
Labels: backport-stable-4.0, backport-stable-5.0

#5951 crash: refact caps definition
  roles/ceph-crash/tasks/main.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5964 iscsi: fix ownership on iscsi-gateway.cfg
  roles/ceph-iscsi-gw/tasks/common.yml
Labels: backport-stable-4.0, backport-stable-5.0
