Repository ceph/ceph-ansible, pull requests merged in 2020-05, with the labels that each got.

#5341 ceph-rgw: use match instead of equalto from jinja2
  roles/ceph-rgw/tasks/multisite/create_realm_zonegroup_zone_lists.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5344 ceph-validate: Fix "fail on unsupported CentOS release"
  roles/ceph-validate/tasks/check_system.yml
Labels: backport-stable-5.0, bug

#5328 [skip-ci] docs: minor fixes to README-MULTISITE.md
  README-MULTISITE.md
Labels: backport-stable-4.0, backport-stable-5.0, documentation

#5337 ceph-nfs: bind mount ganesha log directory
  roles/ceph-nfs/templates/ceph-nfs.service.j2
Labels: backport-stable-4.0, backport-stable-5.0, enhancement

#5330 dashboard: allow disabling grafana api ssl verify
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-dashboard/tasks/configure_dashboard.yml
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0, backport-stable-5.0, enhancement

#5336 rolling_update: fix rbdmirror group name
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-3.2, backport-stable-4.0, backport-stable-5.0, bug

#5366 test: set sitepackages=false in tox
  tox.ini
Labels: backport-stable-4.0, backport-stable-5.0

#5370 tests: force using the more recent build
  tox.ini
Labels: enhancement

#5352 tests: improve ceph-volume testing
  tests/library/test_ceph_volume.py
Labels: backport-stable-5.0, enhancement

#5365 facts: always set ceph_run_cmd and ceph_admin_command
  roles/ceph-facts/tasks/facts.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5364 common: fix target_size_ratio task enablement
  roles/ceph-client/tasks/create_users_keys.yml
  roles/ceph-mds/tasks/create_mds_filesystems.yml
  roles/ceph-osd/tasks/openstack_config.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5377 ceph-nfs: add stable noarch repository
  roles/ceph-nfs/tasks/pre_requisite_non_container_red_hat.yml
Labels: backport-stable-5.0, bug

#5318 [skip ci] doc: Add a release note
  RELEASE-NOTE.md
Labels: documentation

#5397 rgwloadbalancer undefined index variable
  roles/ceph-rgw-loadbalancer/tasks/pre_requisite.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug
