Repository ceph/ceph-ansible, pull requests merged in 2020-03, with the labels that each got.

#5105 ceph-validate: add key format validation
  roles/ceph-validate/tasks/main.yml
Labels: enhancement

#5116 tests: add lvm batch filestore testing
  tests/functional/lvm-batch/container/group_vars/all
  tests/functional/lvm-batch/container/hosts
  tests/functional/lvm-batch/container/vagrant_variables.yml
  tests/functional/lvm-batch/hosts
  tests/functional/lvm-batch/vagrant_variables.yml
Labels: enhancement

#4545 rgw multisite: enable more than 1 realm per cluster
  README-MULTISITE-MULTIREALM.md
  README-MULTISITE.md
  group_vars/all.yml.sample
  group_vars/realm.yml.sample
  group_vars/rhcs.yml.sample
  group_vars/zone.yml.sample
  roles/ceph-config/templates/ceph.conf.j2
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-facts/tasks/set_radosgw_address.yml
  roles/ceph-rgw/handlers/main.yml
  roles/ceph-rgw/tasks/main.yml
  roles/ceph-rgw/tasks/multisite/checks.yml
  roles/ceph-rgw/tasks/multisite/create_realm_zonegroup_zone_lists.yml
  roles/ceph-rgw/tasks/multisite/create_zone_user.yml
  roles/ceph-rgw/tasks/multisite/destroy.yml
  roles/ceph-rgw/tasks/multisite/main.yml
  roles/ceph-rgw/tasks/multisite/master.yml
  roles/ceph-rgw/tasks/multisite/secondary.yml
  roles/ceph-validate/tasks/check_rgw_multisite.yml
  tests/functional/rgw-multisite/container/group_vars/rgws
  tests/functional/rgw-multisite/container/secondary/hosts
  tests/functional/rgw-multisite/group_vars/rgws
  tests/functional/rgw-multisite/secondary/hosts
Labels: backport-stable-4.0, do-not-close

#5127 rgw: add retry/until on pools tasks
  roles/ceph-rgw/tasks/rgw_create_pools.yml
Labels: enhancement

#5123 tests/requirements: bump testinfra
  tests/requirements.txt
Labels: backport-stable-4.0, enhancement

#5134 infra: add retries/until on firewalld start task
  roles/ceph-infra/tasks/configure_firewall.yml
Labels: backport-stable-4.0

#5139 update osd pool set size command
  roles/ceph-client/tasks/create_users_keys.yml
  roles/ceph-iscsi-gw/tasks/common.yml
  roles/ceph-mds/tasks/create_mds_filesystems.yml
  roles/ceph-osd/tasks/openstack_config.yml
  roles/ceph-rgw/tasks/rgw_create_pools.yml
  tests/functional/add-mdss/container/group_vars/all
  tests/functional/add-mdss/group_vars/all
  tests/functional/add-mgrs/container/group_vars/all
  tests/functional/add-mgrs/group_vars/all
  tests/functional/add-mons/container/group_vars/all
  tests/functional/add-mons/group_vars/all
  tests/functional/add-osds/container/group_vars/all
  tests/functional/add-osds/group_vars/all
  tests/functional/add-rbdmirrors/container/group_vars/all
  tests/functional/add-rbdmirrors/group_vars/all
  tests/functional/add-rgws/container/group_vars/all
  tests/functional/add-rgws/group_vars/all
  tests/functional/all-in-one/container/group_vars/all
  tests/functional/all-in-one/group_vars/all
  tests/functional/all_daemons/ceph-override.json
  tests/functional/all_daemons/container/group_vars/all
  tests/functional/all_daemons/group_vars/all
  tests/functional/collocation/container/group_vars/all
  tests/functional/collocation/group_vars/all
  tests/functional/docker2podman/ceph-override.json
  tests/functional/docker2podman/group_vars/all
  tests/functional/external_clients/container/group_vars/all
  tests/functional/external_clients/group_vars/all
  tests/functional/filestore-to-bluestore/container/group_vars/all
  tests/functional/filestore-to-bluestore/group_vars/all
  tests/functional/lvm-auto-discovery/container/group_vars/all
  tests/functional/lvm-auto-discovery/group_vars/all
  tests/functional/lvm-batch/container/group_vars/all
  tests/functional/lvm-batch/group_vars/all
  tests/functional/lvm-osds/container/group_vars/all
  tests/functional/lvm-osds/group_vars/all
  tests/functional/migrate_ceph_disk_to_ceph_volume/group_vars/all
  tests/functional/ooo-collocation/hosts
  tests/functional/podman/group_vars/all
  tests/functional/rgw-multisite/container/group_vars/all
  tests/functional/rgw-multisite/container/secondary/group_vars/all
  tests/functional/rgw-multisite/group_vars/all
  tests/functional/rgw-multisite/secondary/group_vars/all
  tests/functional/shrink_mds/container/group_vars/all
  tests/functional/shrink_mds/group_vars/all
  tests/functional/shrink_mgr/container/group_vars/all
  tests/functional/shrink_mgr/group_vars/all
  tests/functional/shrink_mon/container/group_vars/all
  tests/functional/shrink_mon/group_vars/all
  tests/functional/shrink_osd/container/group_vars/all
  tests/functional/shrink_rbdmirror/container/group_vars/all
  tests/functional/shrink_rbdmirror/group_vars/all
  tests/functional/shrink_rgw/container/group_vars/all
  tests/functional/shrink_rgw/group_vars/all
Labels: enhancement

#5146 config: remove legacy option in ceph.conf.j2
  roles/ceph-config/templates/ceph.conf.j2
Labels: backport-stable-4.0, bug

#5149 rhcs_edits: Update grafana version
  group_vars/rhcs.yml.sample
  rhcs_edits.txt
Labels: backport-stable-4.0, enhancement

#5151 ceph-facts: Fix system_secret_key variable handling
  roles/ceph-facts/tasks/set_radosgw_address.yml
Labels: backport-stable-4.0, bug

#5154 ceph-defaults: update grafana container tag
  group_vars/all.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0, enhancement

#5158 ceph-defaults: add registry name on dashboard vars
  group_vars/all.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: enhancement

#5164 dashboard: allow to set read-only admin user
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-dashboard/tasks/configure_dashboard.yml
  roles/ceph-defaults/defaults/main.yml
  tests/functional/collocation/container/group_vars/all
  tests/functional/collocation/group_vars/all
Labels: backport-stable-4.0, feature

#5169 nfs: fix nfs with external ceph cluster support
  group_vars/clients.yml.sample
  roles/ceph-client/defaults/main.yml
  roles/ceph-client/tasks/create_users_keys.yml
  roles/ceph-nfs/tasks/main.yml
  roles/ceph-validate/tasks/main.yml
  site-container.yml.sample
  site.yml.sample
Labels: backport-stable-4.0, bug

#5175 Add pacific release
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-common/tasks/release-rhcs.yml
  roles/ceph-container-common/tasks/release.yml
  roles/ceph-defaults/defaults/main.yml
  tests/conftest.py
Labels: feature

#5182 tests: update mgr dashboard socket listening test
  tests/functional/tests/mgr/test_mgr.py
Labels: bug

#5184 ceph-facts: fix rgw_instances_all fact
  roles/ceph-facts/tasks/set_radosgw_address.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5189 docker-common: remove legacy tasks for ntp configuration (bp #3251)
  roles/ceph-docker-common/tasks/checks/check_ntp_atomic.yml
  roles/ceph-docker-common/tasks/checks/check_ntp_debian.yml
  roles/ceph-docker-common/tasks/checks/check_ntp_rpm.yml
  roles/ceph-docker-common/tasks/main.yml
  roles/ceph-docker-common/tasks/misc/ntp_atomic.yml
  roles/ceph-docker-common/tasks/misc/ntp_debian.yml
  roles/ceph-docker-common/tasks/misc/ntp_rpm.yml
Labels: bug

#5191 ceph-defaults: update ceph_stable_redhat_distro
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: enhancement

#5178 mergify: Update with stable-5.0 branch
  .mergify.yml
Labels: enhancement

#5193 defaults: remove legacy comment
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-3.2, backport-stable-4.0, backport-stable-5.0

#5199 ceph-defaults: update ganesha to 2.8
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: feature

#5201 rhcs: update release to 5 for octopus
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  rhcs_edits.txt
  roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install.yml
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-5.0, enhancement

#5204 Add a release note
  RELEASE-NOTE.md
Labels: enhancement

#5203 rhcs: drop debian support
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-common/tasks/installs/configure_debian_repository_installation.yml
  roles/ceph-common/tasks/installs/debian_rhcs_repository.yml
  roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install_debian.yml
  roles/ceph-common/tasks/installs/prerequisite_rhcs_iso_install_debian.yml
  roles/ceph-common/templates/rhcs.pref.j2
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-validate/tasks/main.yml
Labels: backport-stable-4.0, backport-stable-5.0, enhancement

#5209 ceph_volume: fix multiple db/wal/journal devices
  library/ceph_volume.py
  tests/library/test_ceph_volume.py
Labels: backport-stable-4.0, backport-stable-5.0, bug

#4922 container: remove ulimit nofile parameter
  infrastructure-playbooks/filestore-to-bluestore.yml
  infrastructure-playbooks/shrink-osd.yml
  library/ceph_volume.py
  roles/ceph-osd/tasks/start_osds.yml
  tests/library/test_ceph_volume.py
Labels: backport-stable-5.0, do-not-close, enhancement

#5208 ceph-defaults: update container tag for nautilus
  group_vars/all.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: enhancement

#5215 purge-container: get *all* osds id
  infrastructure-playbooks/purge-container-cluster.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5216 remove *docker*.yml symlinks
  Vagrantfile
  infrastructure-playbooks/purge-docker-cluster.yml
  site-docker.yml.sample
  tox-external_clients.ini
  tox-filestore_to_bluestore.ini
  tox-update.ini
  tox.ini
Labels: backport-stable-5.0

#5141 osd: support changing default rule even without osd_crush_location
  roles/ceph-osd/tasks/crush_rules.yml
Labels: backport-stable-3.2, backport-stable-4.0, backport-stable-5.0

#5223 Add site-container.yml symlink
  site-container.yml.sample
Labels: enhancement
