Repository ceph/ceph-ansible, pull requests merged in 2020-08, with the labels that each got.

#5610 dashboard: allow remote TLS cert/key copy
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-dashboard/tasks/configure_dashboard.yml
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-grafana/tasks/configure_grafana.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug, enhancement

#5561 tests: add more coverage for test_ceph_key
  library/ceph_key.py
  tests/library/test_ceph_key.py
Labels: backport-stable-4.0, backport-stable-5.0

#5618 [skip ci] Remove ceph-radosgw.target when switching to containerize daemons
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5599 shrink-osd: various fixes
  infrastructure-playbooks/shrink-osd.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5632 osd: change lvm bindmount
  roles/ceph-osd/tasks/start_osds.yml
  roles/ceph-osd/templates/ceph-osd-run.sh.j2
Labels: bug

#5636 [skip ci] tox: remove dashboard file
  tox-dashboard.ini
Labels: enhancement

#5635 [skip ci] pytest: register ceph_crash mark
  tests/pytest.ini
Labels: backport-stable-5.0, enhancement

#5643 nfs: do not copy rgw keyring when `nfs_obj_gw` is true
  roles/ceph-nfs/tasks/pre_requisite_non_container.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5613 [skip ci] rgw: support 1+ rgw instance in `radosgw_frontend_port`
  roles/ceph-facts/tasks/set_radosgw_address.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5656 [skip ci] infra: add missing tag
  roles/ceph-infra/tasks/main.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5629 purge-cluster: use sysfs method for unmapping rbd devices
  infrastructure-playbooks/purge-cluster.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5404 rgw: allow rgws can be run with or without multisite at the same
  roles/ceph-facts/tasks/set_radosgw_address.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5667 [skip ci] container: don't install the engine on all clients
  site-container.yml.sample
Labels: backport-stable-4.0, backport-stable-5.0, enhancement

#5666 [skip ci] ceph-rgw: allow specifying crush rule on pool
  group_vars/rgws.yml.sample
  roles/ceph-rgw/defaults/main.yml
  roles/ceph-rgw/tasks/rgw_create_pools.yml
Labels: backport-stable-4.0, backport-stable-5.0, feature

#5676 [skip ci] travis: enforce ansible-lint 4.2.0
  .travis.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5659 [skip ci] infra: only install logrotate on right nodes
  roles/ceph-infra/tasks/main.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5683 [skip ci] shrink-mds: use mds_to_kill_hostname instead
  infrastructure-playbooks/shrink-mds.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5680 [skip ci] Set default permission for prometheus config files
  roles/ceph-prometheus/tasks/main.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5691 osd: move systemd rendering task
  roles/ceph-osd/tasks/start_osds.yml
  roles/ceph-osd/tasks/systemd.yml
Labels: bug

#5545 [skip ci] Make 'disable ssl for dashboard task' idempotent.
  roles/ceph-dashboard/tasks/configure_dashboard.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5517 [skip ci] tests: reenable nfs-ganesha testing
  tests/functional/all_daemons/hosts
  tests/functional/all_daemons/vagrant_variables.yml
Labels: backport-stable-5.0, do-not-close, enhancement

#5663 facts: refact and optimize memory consumption
  roles/ceph-facts/tasks/facts.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5693 [skip ci] dashboard: refact admin user creation task
  roles/ceph-dashboard/tasks/configure_dashboard.yml
Labels: backport-stable-4.0, backport-stable-5.0
