Repository ceph/ceph-ansible, pull requests merged in 2020-12, with the labels that each got.

#6006 library: add ceph_osd_flag module
  infrastructure-playbooks/rolling_update.yml
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
  library/ceph_osd_flag.py
  roles/ceph-handler/tasks/handler_osds.yml
  roles/ceph-osd/tasks/main.yml
  tests/library/test_ceph_osd_flag.py
Labels: enhancement, feature, modules

#5940 library: add cephadm_bootstrap module
  infrastructure-playbooks/cephadm.yml
  library/cephadm_bootstrap.py
  tests/functional/cephadm/group_vars/all
  tests/library/test_cephadm_bootstrap.py
Labels: feature, modules

#6093 ceph-client: use group_by instead of add_host
  roles/ceph-client/tasks/create_users_keys.yml
Labels: enhancement

#6077 [skip ci] osd: add tag on 'wait for all osd to be up' task
  roles/ceph-osd/tasks/main.yml
Labels: backport-stable-4.0, backport-stable-5.0

#6013 library: add ceph_crush_rule module
  library/ceph_crush_rule.py
  roles/ceph-facts/tasks/get_def_crush_rule_name.yml
  roles/ceph-osd/tasks/crush_rules.yml
  roles/ceph-rgw/tasks/rgw_create_pools.yml
  tests/library/test_ceph_crush_rule.py
Labels: enhancement, feature, modules

#6055 consume ceph_volume module when possible
  infrastructure-playbooks/cephadm-adopt.yml
  infrastructure-playbooks/filestore-to-bluestore.yml
  infrastructure-playbooks/shrink-osd.yml
  roles/ceph-osd/tasks/start_osds.yml
Labels: enhancement, modules

#6092 common: do not use pipefail when not needed
  infrastructure-playbooks/purge-cluster.yml
  infrastructure-playbooks/rolling_update.yml
  roles/ceph-osd/tasks/start_osds.yml
Labels: backport-stable-4.0, backport-stable-5.0

#6096 [skip ci] library: add cephadm_adopt module
  infrastructure-playbooks/cephadm-adopt.yml
  library/cephadm_adopt.py
  tests/library/test_cephadm_adopt.py
Labels: enhancement, feature, modules

#6101 ceph-mon: No become during gen mon initial keyring
  roles/ceph-mon/tasks/deploy_monitors.yml
Labels: backport-stable-5.0

#6104 [skip ci] rhcs: drop fetch_directory override
  rhcs_edits.txt
Labels: backport-stable-4.0, backport-stable-5.0, enhancement

#6116 [skip ci] tests: remove pyyaml workaround on OSD nodes
  tests/functional/setup.yml
Labels: tests

#6111 ceph-facts: fix grafana group conversion
  roles/ceph-facts/tasks/convert_grafana_server_group_name.yml
  roles/ceph-facts/tasks/main.yml
Labels: bug

#6126 ceph-rgw: add cluster parameter on ceph_ec_profile
  roles/ceph-rgw/tasks/rgw_create_pools.yml
Labels: bug

#6125 monitoring: use config_template module for config
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-grafana/tasks/configure_grafana.yml
  roles/ceph-prometheus/tasks/main.yml
Labels: backport-stable-4.0, backport-stable-5.0, enhancement, feature

#6117 [skip ci] Revert "config: Always use osd_memory_target if set"
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-config/templates/ceph.conf.j2
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#6079 [skip ci] fix broken ceph-fetch-keys role
  generate_group_vars_sample.sh
  roles/ceph-fetch-keys/defaults/main.yml
  roles/ceph-fetch-keys/tasks/main.yml
Labels: backport-stable-4.0, backport-stable-5.0

#6144 ceph-config: fix ceph-volume lvm batch report
  roles/ceph-config/tasks/main.yml
Labels: backport-stable-4.0, backport-stable-5.0, enhancement

#6139 library: add missing `target_size_ratio` parameter support in ceph_pool module
  library/ceph_pool.py
  roles/ceph-rgw/tasks/rgw_create_pools.yml
  tests/library/test_ceph_pool.py
Labels: backport-stable-5.0, modules

#6119 [skip ci] cephadm: remove loop on host add tasks
  infrastructure-playbooks/cephadm-adopt.yml
  infrastructure-playbooks/cephadm.yml
Labels: backport-stable-5.0, enhancement
