Repository ceph/ceph-ansible, pull requests merged in 2020-04, with the labels that each got.

#5157 ceph_key: remove 'update' state
  library/ceph_key.py
  tests/library/test_ceph_key.py
Labels: backport-stable-3.2, backport-stable-4.0, backport-stable-5.0, bug

#5226 docker2podman: call `container_options_facts.yml` on osd nodes
  infrastructure-playbooks/docker-to-podman.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5229 vagrant: force centos 8.1 libvirt image
  tests/scripts/vagrant_up.sh
Labels: backport-stable-5.0

#5236 tests: add mgr nodes to shrink_mon inventory
  tests/functional/shrink_mon/container/hosts
  tests/functional/shrink_mon/hosts
Labels: bug

#5238 tox-docker2podman: update container image tag
  tox-docker2podman.ini
Labels: backport-stable-5.0

#5239 tox: replace testinfra by pytest for add-mgrs
  tox.ini
Labels: backport-stable-4.0, backport-stable-5.0

#5242 ceph_key: fix idempotency when no secret is passed
  library/ceph_key.py
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5246 ceph_key: fetch key when needed
  library/ceph_key.py
Labels: backport-stable-4.0, backport-stable-5.0

#5249 ceph-mgr: add saml python lib for dashboard SSO
  roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install.yml
  roles/ceph-mgr/tasks/pre_requisite.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5261 osd: fix monitor_name error when scaling out OSDs
  roles/ceph-facts/tasks/facts.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5264 ceph-validate: update RHEL requirement for RHCS
  roles/ceph-validate/tasks/check_system.yml
Labels: backport-stable-3.2, backport-stable-4.0, backport-stable-5.0, enhancement

#5271 nfs: create empty rados index object for nfs standalone
  roles/ceph-nfs/tasks/main.yml
  roles/ceph-nfs/tasks/start_nfs.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5270 mds: fix --limit runs against mds nodes
  roles/ceph-facts/tasks/facts.yml
  roles/ceph-mds/tasks/create_mds_filesystems.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5282 docs: Update and consolidate rgw multisite documentation
  README-MULTISITE-MULTIREALM.md
  README-MULTISITE.md
Labels: documentation

#5262 library/ceph_volume: look for error messages in stderr
  library/ceph_volume.py
Labels: backport-stable-3.2, backport-stable-4.0, backport-stable-5.0, bug

#5284 Updated use of deprecated filter
  roles/ceph-common/tasks/release-rhcs.yml
  roles/ceph-container-common/tasks/release.yml
  roles/ceph-validate/tasks/check_system.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5288 filestore-to-bluestore: fix py2 on skipped tasks
  infrastructure-playbooks/filestore-to-bluestore.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5293 doc: add day-2 operations documentation
  docs/source/day-2/osds.rst
  docs/source/day-2/purge.rst
  docs/source/index.rst
Labels: backport-stable-3.2, backport-stable-4.0, backport-stable-5.0, documentation, enhancement

#5296 Correcting validation type check on rc
  roles/ceph-validate/tasks/check_system.yml
Labels: bug

#5294 mds: don't enable application pool on cephfs pools
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-mds/tasks/create_mds_filesystems.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5260 ceph-container-engine: add CentOS 8 support
  roles/ceph-container-engine/vars/CentOS-8.yml
Labels: feature

#5195 tests: add back nfs testing on master
  tests/functional/all_daemons/container/hosts
  tests/functional/all_daemons/container/vagrant_variables.yml
Labels: backport-stable-5.0

#5237 Readd CentOS 7 with conditions
  group_vars/all.yml.sample
  group_vars/mgrs.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-common/tasks/installs/redhat_community_repository.yml
  roles/ceph-common/tasks/installs/redhat_dev_repository.yml
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-mgr/defaults/main.yml
  roles/ceph-mgr/tasks/mgr_modules.yml
  roles/ceph-mgr/tasks/pre_requisite.yml
  roles/ceph-validate/tasks/check_system.yml
  tests/conftest.py
  tests/functional/docker2podman/group_vars/all
  tests/functional/docker2podman/hosts
Labels: backport-stable-5.0, feature

#5309 ceph-dashboard: fix mgr dashboard IPv6 fact
  roles/ceph-dashboard/tasks/configure_dashboard_backends.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5273 Refresh ceph dashboard user role
  roles/ceph-dashboard/tasks/configure_dashboard.yml
Labels: backport-stable-4.0, backport-stable-5.0, enhancement

#5326 clients: move dummy container creation
  roles/ceph-client/tasks/create_users_keys.yml
Labels: bug

#5327 ceph-facts: fix IPv6 _radosgw_address interface
  roles/ceph-facts/tasks/set_radosgw_address.yml
Labels: backport-stable-3.2, backport-stable-4.0, backport-stable-5.0, bug

#5335 tox-update: fix update container tag value
  tox-update.ini
Labels: bug
