Repository ceph/ceph-ansible, pull requests merged in 2020-11, with the labels that each got.

#5969 ceph-handler: fix curl ipv6 command with rgw
  roles/ceph-handler/templates/restart_rgw_daemon.sh.j2
Labels: backport-stable-4.0, backport-stable-5.0

#5968 podman: force log driver to journald
  roles/ceph-crash/templates/ceph-crash.service.j2
  roles/ceph-grafana/templates/grafana-server.service.j2
  roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2
  roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2
  roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2
  roles/ceph-mds/templates/ceph-mds.service.j2
  roles/ceph-mgr/templates/ceph-mgr.service.j2
  roles/ceph-mon/templates/ceph-mon.service.j2
  roles/ceph-nfs/templates/ceph-nfs.service.j2
  roles/ceph-node-exporter/templates/node_exporter.service.j2
  roles/ceph-osd/templates/ceph-osd.service.j2
  roles/ceph-prometheus/templates/alertmanager.service.j2
  roles/ceph-prometheus/templates/prometheus.service.j2
  roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
  roles/ceph-rgw/templates/ceph-radosgw.service.j2
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5948 openstack: omit mode on key if not set on item
  roles/ceph-osd/tasks/openstack_config.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5979 library: remove unused module import
  library/ceph_dashboard_user.py
  library/ceph_fs.py
  library/ceph_key.py
  library/ceph_pool.py
  library/ceph_volume.py
  library/radosgw_realm.py
  library/radosgw_user.py
  library/radosgw_zone.py
  library/radosgw_zonegroup.py
Labels: enhancement

#5982 ceph-mon: Don't set monitor directory mode recursively
  roles/ceph-mon/tasks/deploy_monitors.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5992 common: follow up on #5948
  roles/ceph-client/tasks/create_users_keys.yml
  roles/ceph-osd/tasks/openstack_config.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5971 infrastructure: consume ceph_fs module
  infrastructure-playbooks/rolling_update.yml
  infrastructure-playbooks/shrink-mds.yml
Labels: backport-stable-5.0, enhancement

#5985 rolling_update: fix mgr start with mon collocation
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-5.0, bug

#5944 osd: Fix number of OSD calculation
  roles/ceph-config/tasks/main.yml
Labels: backport-stable-4.0, backport-stable-5.0

#6002 dashboard: enable https by default
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0, backport-stable-5.0

#6014 rolling_update: always run cv simple scan/activate
  infrastructure-playbooks/rolling_update.yml
Labels: bug

#5959 [skip ci] switch2container: disable ceph-osd enabled-runtime
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
  tox.ini
Labels: backport-stable-4.0, backport-stable-5.0, bug

#6022 [skip ci] main: followup on pr 6012
  site-container.yml.sample
  site.yml.sample
Labels: backport-stable-4.0, backport-stable-5.0, enhancement

#5945 config: Always use osd_memory_target if set
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-config/templates/ceph.conf.j2
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5921 ceph-facts: Fix osd_pool_default_crush_rule fact
  roles/ceph-facts/tasks/facts.yml
Labels: backport-stable-4.0, backport-stable-5.0

#6018 container: force rm --storage on ExecStartPre
  roles/ceph-crash/templates/ceph-crash.service.j2
  roles/ceph-grafana/templates/grafana-server.service.j2
  roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2
  roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2
  roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2
  roles/ceph-mds/templates/ceph-mds.service.j2
  roles/ceph-mgr/templates/ceph-mgr.service.j2
  roles/ceph-mon/templates/ceph-mon.service.j2
  roles/ceph-nfs/templates/ceph-nfs.service.j2
  roles/ceph-node-exporter/templates/node_exporter.service.j2
  roles/ceph-osd/templates/ceph-osd.service.j2
  roles/ceph-prometheus/templates/alertmanager.service.j2
  roles/ceph-prometheus/templates/prometheus.service.j2
  roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
  roles/ceph-rgw/templates/ceph-radosgw.service.j2
Labels: backport-stable-4.0, backport-stable-5.0

#6033 [skip ci] switch2container: chown symlink in mon/mgr plays
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Labels: backport-stable-3.2, backport-stable-4.0, backport-stable-5.0

#6040 containers: modify bindmount option
  roles/ceph-mgr/templates/ceph-mgr.service.j2
  roles/ceph-mon/templates/ceph-mon.service.j2
Labels: backport-stable-3.2, backport-stable-4.0, backport-stable-5.0

#5970 [skip ci] tests: use github workflow for pytest
  .github/workflows/pytest.yml
  .travis.yml
  tests/requirements.txt
Labels: backport-stable-4.0, backport-stable-5.0

#6051 ceph-facts: fix read osd pool default crush fact
  roles/ceph-facts/tasks/facts.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#6042 osd: ensure /var/lib/ceph/osd/{cluster}-{id} is present
  roles/ceph-osd/tasks/start_osds.yml
Labels: backport-stable-4.0, backport-stable-5.0

#6065 ceph-iscsi: set the pool name in the config file
  roles/ceph-iscsi-gw/templates/iscsi-gateway.cfg.j2
Labels: backport-stable-4.0, backport-stable-5.0, bug

#6064 mon: refact initial keyring generation
  infrastructure-playbooks/add-mon.yml
  library/ceph_key.py
  roles/ceph-mon/tasks/deploy_monitors.yml
  tests/library/test_ceph_key.py
Labels: backport-stable-4.0, backport-stable-5.0, modules

#6054 library: add ceph_volume_simple_{activate,scan}
  infrastructure-playbooks/filestore-to-bluestore.yml
  infrastructure-playbooks/rolling_update.yml
  library/ceph_volume_simple_activate.py
  library/ceph_volume_simple_scan.py
  tests/library/test_ceph_volume_simple_activate.py
  tests/library/test_ceph_volume_simple_scan.py
Labels: enhancement, feature, modules

#6068 library: remove useless condition in ceph_volume
  library/ceph_volume.py
Labels: enhancement, modules

#5928 [skip ci] rhcs: default to containerized deployment
  group_vars/rhcs.yml.sample
  rhcs_edits.txt
Labels: do-not-close

#6071 library: use exit_module from ca_common
  library/ceph_volume_simple_activate.py
  library/ceph_volume_simple_scan.py
  tests/library/test_ceph_volume_simple_activate.py
  tests/library/test_ceph_volume_simple_scan.py
Labels: enhancement, modules

#6082 [skip ci] tests: add module_utils directory to flake8/pytest
  .github/workflows/flake8.yml
  .github/workflows/pytest.yml
  tests/module_utils/test_ca_common.py
Labels: modules, tests

#6074 alertmanager/prometheus: fix owner/group
  roles/ceph-prometheus/tasks/main.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#6078 switch2containers: do not stop ceph.target in osd play
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Labels: backport-stable-4.0, backport-stable-5.0

#6088 [skip ci] improve plugins/filter testing
  .github/workflows/flake8.yml
  .github/workflows/pytest.yml
  plugins/filter/ipaddrs_in_ranges.py
  tests/plugins/filter/test_ipaddrs_in_ranges.py
Labels: tests

#6089 [skip ci] tests: use ca_test_common with ceph_volume_simple
  tests/library/test_ceph_volume_simple_activate.py
  tests/library/test_ceph_volume_simple_scan.py
Labels: modules, tests

#6039 library: add ceph_mgr_module module
  infrastructure-playbooks/cephadm-adopt.yml
  library/ceph_mgr_module.py
  roles/ceph-dashboard/tasks/configure_dashboard.yml
  roles/ceph-mgr/tasks/mgr_modules.yml
  tests/library/test_ceph_mgr_module.py
Labels: enhancement, feature, modules

#6059 library: add ceph_osd module
  infrastructure-playbooks/filestore-to-bluestore.yml
  infrastructure-playbooks/shrink-osd.yml
  library/ceph_osd.py
  tests/library/test_ceph_osd.py
Labels: enhancement, feature, modules
