Repository ceph/ceph-ansible, pull requests merged in 2020-06, with the labels that each got.

#5354 docker-to-podman: conditional docker commands
  infrastructure-playbooks/docker-to-podman.yml
Labels: bug

#5407 mergify: remove merge on skip ci
  .mergify.yml
Labels: enhancement

#5406 rgw multisite: add master zone endpoints to zonegroup
  roles/ceph-rgw/tasks/multisite/master.yml
Labels: backport-stable-4.0, backport-stable-5.0, enhancement

#5403 switch_to_container: fix osd systemd regex
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5405 container: inspect Id field instead of RepoDigests
  roles/ceph-container-common/tasks/fetch_image.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5413 lvm_setup: lookup device from inventory, default to /dev/sd* names
  tests/functional/lvm_setup.yml
Labels: bug, ceph-volume-testing-impact?

#5418 switch_to_containers: don't set noup flag
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
  roles/ceph-osd/tasks/main.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5411 [skip ci] debian/uca: remove the handler notification
  roles/ceph-common/tasks/installs/debian_uca_repository.yml
  roles/ceph-handler/handlers/main.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5390 library/ceph_pool: set name parameter as required
  library/ceph_pool.py
Labels: backport-stable-5.0, bug

#5424 switch-to-containers: set and unset osd flags
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Labels: enhancement

#5410 ceph-osd: remove ceph-osd-run.sh script
  group_vars/osds.yml.sample
  infrastructure-playbooks/purge-container-cluster.yml
  roles/ceph-osd/defaults/main.yml
  roles/ceph-osd/tasks/systemd.yml
  roles/ceph-osd/templates/ceph-osd-run.sh.j2
  roles/ceph-osd/templates/ceph-osd.service.j2
  tests/functional/add-mdss/container/group_vars/all
  tests/functional/add-mgrs/container/group_vars/all
  tests/functional/add-mons/container/group_vars/all
  tests/functional/add-osds/container/group_vars/all
  tests/functional/add-rbdmirrors/container/group_vars/all
  tests/functional/add-rgws/container/group_vars/all
  tests/functional/all-in-one/container/group_vars/all
  tests/functional/all-in-one/group_vars/all
  tests/functional/all_daemons/container/group_vars/osds
  tests/functional/collocation/container/group_vars/osds
  tests/functional/collocation/group_vars/osds
  tests/functional/docker2podman/group_vars/osds
  tests/functional/external_clients/container/inventory/group_vars/all
  tests/functional/external_clients/inventory/group_vars/all
  tests/functional/filestore-to-bluestore/container/group_vars/all
  tests/functional/lvm-auto-discovery/container/group_vars/all
  tests/functional/lvm-batch/container/group_vars/all
  tests/functional/lvm-osds/container/group_vars/all
  tests/functional/ooo-collocation/hosts
  tests/functional/podman/group_vars/osds
  tests/functional/rgw-multisite/container/group_vars/all
  tests/functional/rgw-multisite/container/secondary/group_vars/all
  tests/functional/rgw-multisite/secondary/group_vars/all
  tests/functional/shrink_mds/container/group_vars/osds
  tests/functional/shrink_mgr/container/group_vars/osds
  tests/functional/shrink_mon/container/group_vars/osds
  tests/functional/shrink_osd/container/group_vars/osds
  tests/functional/shrink_rbdmirror/container/group_vars/osds
  tests/functional/shrink_rgw/container/group_vars/osds
Labels: enhancement

#5389 [skip ci] Update release note
  RELEASE-NOTE.md
Labels: documentation

#5394 docs: Add upgrade operation.
  docs/source/day-2/upgrade.rst
  docs/source/index.rst
Labels: backport-stable-3.2, backport-stable-4.0, backport-stable-5.0, documentation

#5435 requirements: exclude ansible 2.9.10
  requirements.txt
  tests/requirements.txt
Labels: backport-stable-5.0

#5437 travis: use tests/requirements.txt
  .travis.yml
Labels: backport-stable-5.0, enhancement

#5440 docker2podman: make images pulling optional
  infrastructure-playbooks/docker-to-podman.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5444 [skip ci] docker: Add Requires on docker service
  roles/ceph-grafana/templates/grafana-server.service.j2
  roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2
  roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2
  roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2
  roles/ceph-mds/templates/ceph-mds.service.j2
  roles/ceph-mgr/templates/ceph-mgr.service.j2
  roles/ceph-mon/templates/ceph-mon.service.j2
  roles/ceph-nfs/templates/ceph-nfs.service.j2
  roles/ceph-node-exporter/templates/node_exporter.service.j2
  roles/ceph-osd/templates/ceph-osd.service.j2
  roles/ceph-prometheus/templates/alertmanager.service.j2
  roles/ceph-prometheus/templates/prometheus.service.j2
  roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
  roles/ceph-rgw/templates/ceph-radosgw.service.j2
Labels: backport-stable-3.2, backport-stable-4.0, backport-stable-5.0, bug

#5434 ceph_volume: make zap function idempotent
  library/ceph_volume.py
  tests/library/test_ceph_volume.py
Labels: backport-stable-4.0, backport-stable-5.0

#5443 podman: Add Type and PIDFile value to unit files
  roles/ceph-grafana/templates/grafana-server.service.j2
  roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2
  roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2
  roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2
  roles/ceph-mds/templates/ceph-mds.service.j2
  roles/ceph-mgr/templates/ceph-mgr.service.j2
  roles/ceph-mon/templates/ceph-mon.service.j2
  roles/ceph-nfs/templates/ceph-nfs.service.j2
  roles/ceph-node-exporter/templates/node_exporter.service.j2
  roles/ceph-osd/templates/ceph-osd.service.j2
  roles/ceph-prometheus/templates/alertmanager.service.j2
  roles/ceph-prometheus/templates/prometheus.service.j2
  roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
  roles/ceph-rgw/templates/ceph-radosgw.service.j2
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5450 dashboard: copy self-signed generated crt to mons
  roles/ceph-dashboard/tasks/configure_dashboard.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5466 dashboard: configure mgr backend before restart
  roles/ceph-dashboard/tasks/configure_dashboard.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5269 [skip ci] Add playbook for converting cluster to cephadm
  infrastructure-playbooks/cephadm-adopt.yml
Labels: backport-stable-5.0, do-not-close, feature

#5478 [skip ci] Add container settings for Ubuntu 20 (the same as Ubuntu 18)
  roles/ceph-container-engine/vars/Ubuntu-20.yml
Labels: backport-stable-5.0, feature

#5477 rolling_update: add any_errors_fatal
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5426 ceph-common: remove copr and sepia repositories
  roles/ceph-common/tasks/installs/redhat_dev_repository.yml
Labels: backport-stable-5.0, enhancement

#5461 ceph-volume.py: add support for batch refactored code
  library/ceph_volume.py
Labels: backport-stable-4.0, backport-stable-5.0, enhancement

#5420 vagrant: update centos image to 8.2
  tests/scripts/vagrant_up.sh
Labels: backport-stable-5.0, enhancement
