Repository ceph/ceph-ansible, pull requests merged in 2020-07, with the labels that each got.

#5489 tests: enforce pytest-rerunfailures version
  tests/requirements.txt
Labels: tests

#5487 rgw: fix multi instances scaleout
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
  roles/ceph-config/tasks/main.yml
  roles/ceph-config/tasks/rgw_systemd_environment_file.yml
  roles/ceph-rgw/tasks/common.yml
  roles/ceph-rgw/tasks/start_docker_rgw.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5493 radosgw: remove INST_PORT environment variable
  roles/ceph-config/tasks/rgw_systemd_environment_file.yml
  roles/ceph-rgw/templates/ceph-radosgw.service.j2
Labels: backport-stable-4.0, backport-stable-5.0, enhancement

#5486 facts: explicitly disable facter and ohai
  infrastructure-playbooks/add-mon.yml
  infrastructure-playbooks/add-osd.yml
  infrastructure-playbooks/cephadm-adopt.yml
  infrastructure-playbooks/docker-to-podman.yml
  infrastructure-playbooks/filestore-to-bluestore.yml
  infrastructure-playbooks/purge-cluster.yml
  infrastructure-playbooks/purge-container-cluster.yml
  infrastructure-playbooks/rolling_update.yml
  infrastructure-playbooks/shrink-rgw.yml
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
  site-container.yml.sample
  site.yml.sample
Labels: backport-stable-3.2, backport-stable-4.0, backport-stable-5.0, enhancement

#5496 [skip ci] ceph-defaults: update nfs-ganesha to 3.3
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-5.0, enhancement

#5499 doc: fix warning treated as an error
  docs/source/day-2/upgrade.rst
Labels: backport-stable-3.2, backport-stable-4.0, backport-stable-5.0

#5509 [skip ci] tests: update nfs-ganesha to V3.3-stable
  tests/functional/all_daemons/group_vars/nfss
Labels: backport-stable-5.0

#5514 [skip ci] tests: remove nfs_ganesha_stable_branch variable
  tests/functional/all_daemons/group_vars/nfss
Labels: backport-stable-5.0, enhancement

#5513 [skip ci] ceph-nfs: change ganesha devel source
  roles/ceph-nfs/tasks/pre_requisite_non_container_red_hat.yml
Labels: backport-stable-5.0, enhancement

#5467 ceph-osd: exit gracefully when no data partition
  roles/ceph-osd/templates/ceph-osd-run.sh.j2
Labels: enhancement

#5524 README-MULTISITE: fix old conflict
  README-MULTISITE.md
Labels: bug, documentation

#5525 play: remove backward compatibility group name
  infrastructure-playbooks/gather-ceph-logs.yml
  site-container.yml.sample
  site.yml.sample
Labels: enhancement

#5531 rgw: set container memory limit to 4g
  group_vars/rgws.yml.sample
  roles/ceph-rgw/defaults/main.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5532 play: followup on cc0d969
  site-container.yml.sample
  site.yml.sample
Labels: enhancement

#5541 [skip ci] cephadm-adopt: use placement parameter
  infrastructure-playbooks/cephadm-adopt.yml
Labels: backport-stable-5.0, enhancement

#5543 [skip ci] batch fixes/features cephadm adopt
  infrastructure-playbooks/cephadm-adopt.yml
Labels: backport-stable-5.0, enhancement, feature

#5537 ceph_key: fix bug in 'info' feature
  library/ceph_key.py
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5552 [skip ci] enchancement on displayed information
  infrastructure-playbooks/cephadm-adopt.yml
Labels: backport-stable-5.0, enhancement

#5554 [skip ci] cephadm-adopt: delegate task for orch apply
  infrastructure-playbooks/cephadm-adopt.yml
Labels: backport-stable-5.0, bug

#5548 [skip ci] cephadm: add playbook
  infrastructure-playbooks/cephadm.yml
  tests/functional/cephadm/Vagrantfile
  tests/functional/cephadm/group_vars/all
  tests/functional/cephadm/hosts
  tests/functional/cephadm/vagrant_variables.yml
  tox-cephadm.ini
Labels: backport-stable-5.0, feature

#5559 ceph-dashboard: copy TLS cert/key on monitor
  roles/ceph-dashboard/tasks/configure_dashboard.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5544 facts: fix broken facts when using --limit
  roles/ceph-facts/tasks/facts.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5564 [skip ci] cephadm: set the command as a fact
  infrastructure-playbooks/cephadm-adopt.yml
  infrastructure-playbooks/cephadm.yml
Labels: backport-stable-5.0, bug

#5508 ceph-crash: introduce new role ceph-crash
  infrastructure-playbooks/docker-to-podman.yml
  infrastructure-playbooks/purge-cluster.yml
  infrastructure-playbooks/purge-container-cluster.yml
  infrastructure-playbooks/rolling_update.yml
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
  roles/ceph-container-common/tasks/fetch_image.yml
  roles/ceph-crash/meta/main.yml
  roles/ceph-crash/tasks/main.yml
  roles/ceph-crash/tasks/systemd.yml
  roles/ceph-crash/templates/ceph-crash.service.j2
  roles/ceph-handler/handlers/main.yml
  roles/ceph-handler/tasks/check_running_containers.yml
  roles/ceph-handler/tasks/check_socket_non_container.yml
  roles/ceph-handler/tasks/handler_crash.yml
  roles/ceph-handler/tasks/main.yml
  site-container.yml.sample
  site.yml.sample
  tests/conftest.py
  tests/functional/tests/test_install.py
Labels: backport-stable-4.0, backport-stable-5.0

#5571 [skip ci] crash: rm container in ExecPreStart even with docker
  roles/ceph-crash/templates/ceph-crash.service.j2
Labels: backport-stable-4.0, backport-stable-5.0

#5573 ceph-handler: add missing condition on ceph-crash
  roles/ceph-handler/handlers/main.yml
  roles/ceph-handler/tasks/check_running_containers.yml
  roles/ceph-handler/tasks/check_socket_non_container.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5578 tests: (lvm_setup.yml), don't shrink lvol
  tests/functional/lvm_setup.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5570 podman: always remove container on start
  roles/ceph-grafana/templates/grafana-server.service.j2
  roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2
  roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2
  roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2
  roles/ceph-mds/templates/ceph-mds.service.j2
  roles/ceph-mgr/templates/ceph-mgr.service.j2
  roles/ceph-mon/templates/ceph-mon.service.j2
  roles/ceph-nfs/templates/ceph-nfs.service.j2
  roles/ceph-node-exporter/templates/node_exporter.service.j2
  roles/ceph-osd/templates/ceph-osd.service.j2
  roles/ceph-prometheus/templates/alertmanager.service.j2
  roles/ceph-prometheus/templates/prometheus.service.j2
  roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
  roles/ceph-rgw/templates/ceph-radosgw.service.j2
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5574 ceph-handler: remove iscsigws restart scripts
  roles/ceph-handler/handlers/main.yml
  roles/ceph-handler/tasks/handler_rbd_target_api_gw.yml
  roles/ceph-handler/tasks/handler_tcmu_runner.yml
  roles/ceph-handler/templates/restart_rbd_target_api.sh.j2
  roles/ceph-handler/templates/restart_rbd_target_gw.sh.j2
  roles/ceph-handler/templates/restart_tcmu_runner.sh.j2
Labels: backport-stable-4.0, backport-stable-5.0, enhancement

#5575 [skip ci] ceph-facts: remove mds_name fact
  roles/ceph-facts/tasks/facts.yml
  roles/ceph-handler/templates/restart_mds_daemon.sh.j2
  roles/ceph-mds/tasks/common.yml
  roles/ceph-mds/tasks/non_containerized.yml
Labels: backport-stable-4.0, backport-stable-5.0, enhancement

#5572 rolling_update: stop/start instead of restart
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#5602 tests: pin pytest-forked to 1.2.0
  tests/requirements.txt
Labels: tests

#5603 tests: install pyyaml on osd nodes
  tests/functional/setup.yml
Labels: bug, tests

#5601 [skip ci] rolling_update: restart active mds after the upgrade
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0, backport-stable-5.0

#5608 docker2podman: set disk_list for non lvm scenario
  infrastructure-playbooks/docker-to-podman.yml
  tests/functional/docker2podman/host_vars/osd0
  tests/functional/docker2podman/host_vars/osd1
  tests/functional/docker2podman/hosts
  tests/functional/docker2podman/vagrant_variables.yml
Labels: bug
