Repository ceph/ceph-ansible, pull requests merged in 2020-01, with the labels that each got.

#4808 ceph-rgw-loadbalancer: Modify keepalived master selection
  roles/ceph-rgw-loadbalancer/tasks/pre_requisite.yml
  roles/ceph-rgw-loadbalancer/templates/keepalived.conf.j2
Labels: enhancement

#4889 ceph_volume: support filestore to bluestore migration
  library/ceph_volume.py
Labels: backport-stable-4.0

#4886 purge-iscsi-gateways: remove node from dashboard
  infrastructure-playbooks/purge-iscsi-gateways.yml
Labels: backport-stable-4.0, enhancement

#4878 dashboard: use fqdn in external url
  roles/ceph-prometheus/templates/alertmanager.service.j2
  roles/ceph-prometheus/templates/prometheus.service.j2
Labels: backport-stable-4.0

#4896 shrink-mds: do not play ceph-facts entirely
  infrastructure-playbooks/shrink-mds.yml
Labels: enhancement

#4898 ceph-iscsi: add ceph-iscsi stable repositories
  roles/ceph-iscsi-gw/tasks/non-container/prerequisites.yml
  tests/functional/all_daemons/hosts
Labels: enhancement

#4890 ceph-iscsi: manage ipv6 in trusted_ip_list
  roles/ceph-dashboard/tasks/configure_dashboard.yml
  roles/ceph-iscsi-gw/tasks/common.yml
Labels: backport-stable-4.0, bug

#4887 ceph-rgw: Fix custom pool size setting
  roles/ceph-rgw/tasks/main.yml
Labels: backport-stable-4.0, bug

#4875 handler: fix bug
  roles/ceph-handler/tasks/handler_mdss.yml
  roles/ceph-handler/tasks/handler_mgrs.yml
  roles/ceph-handler/tasks/handler_mons.yml
  roles/ceph-handler/tasks/handler_nfss.yml
  roles/ceph-handler/tasks/handler_osds.yml
  roles/ceph-handler/tasks/handler_rbdmirrors.yml
  roles/ceph-handler/tasks/handler_rgws.yml
Labels: backport-stable-4.0, bug

#4904 mon: support replacing a mon
  roles/ceph-facts/tasks/facts.yml
  roles/ceph-mon/tasks/deploy_monitors.yml
Labels: backport-stable-4.0

#4905 shrink-rgw: refact global workflow
  infrastructure-playbooks/shrink-rgw.yml
Labels: backport-stable-4.0, bug

#4909 rolling_update: run registry auth before upgrading
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0, bug

#4908 config: exclude ceph-disk prepared osds in lvm batch report
  roles/ceph-config/tasks/main.yml
Labels: backport-stable-4.0, blocker, bug

#4914 purge-iscsi-gateways: don't run all ceph-facts
  infrastructure-playbooks/purge-iscsi-gateways.yml
Labels: backport-stable-4.0, bug

#4919 ceph-validate: fail on CentOS 7
  roles/ceph-validate/tasks/check_system.yml
Labels: enhancement

#4921 tests/setup: update mount options on EL 8
  tests/functional/setup.yml
Labels: enhancement

#4866 [stable-3.2] ceph-mds: allow directory fragmentation
  roles/ceph-mds/tasks/create_mds_filesystems.yml
Labels: bug

#4865 [stable-3.2] switch_to_containers: set GUID on lockbox part
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Labels: bug

#4926 osd: ensure osd ids collected are well restarted
  roles/ceph-osd/tasks/start_osds.yml
Labels: backport-stable-4.0, bug

#4925 ceph-facts: move grafana fact to dedicated file
  dashboard.yml
  roles/ceph-facts/tasks/facts.yml
  roles/ceph-facts/tasks/grafana.yml
Labels: backport-stable-4.0, bug

#4924 facts: fix osp/ceph external use case
  roles/ceph-facts/tasks/facts.yml
Labels: backport-stable-4.0, bug

#4932 osd: use _devices fact in lvm batch scenario
  roles/ceph-osd/tasks/scenarios/lvm-batch.yml
Labels: backport-stable-4.0

#4935 ceph-iscsi: don't use bracket with trusted_ip_list
  roles/ceph-iscsi-gw/tasks/common.yml
Labels: backport-stable-4.0, bug

#4941 shrink-mds: fix condition on fs deletion
  infrastructure-playbooks/shrink-mds.yml
Labels: backport-stable-4.0

#4938 travis: drop python2 support
  .travis.yml
Labels: enhancement

#4939 drop use_fqdn variables
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-config/templates/ceph.conf.j2
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-facts/tasks/facts.yml
  roles/ceph-validate/tasks/main.yml
Labels: enhancement

#4943 remove container_exec_cmd_mgr fact
  roles/ceph-mgr/tasks/common.yml
  roles/ceph-mgr/tasks/main.yml
  roles/ceph-mgr/tasks/mgr_modules.yml
Labels: backport-stable-4.0

#4940 group_vars: remove useless files
  group_vars/ceph-fetch-keys.yml.sample
  group_vars/docker-commons.yml.sample
  group_vars/factss.yml.sample
  roles/ceph-facts/defaults/main.yml
  roles/ceph-fetch-keys/defaults/main.yml
Labels: enhancement

#4948 ceph-facts: move facts to defaults value
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-facts/tasks/facts.yml
Labels: enhancement

#4951 Fix undefined running_mon
  roles/ceph-mgr/tasks/common.yml
Labels: backport-stable-4.0, bug

#4956 fix `container_exec_cmd` calls for --limit runs
  roles/ceph-handler/tasks/handler_osds.yml
  roles/ceph-nfs/tasks/pre_requisite_container.yml
  roles/ceph-osd/tasks/main.yml
Labels: backport-stable-4.0, bug

#4958 ceph-rgw: Fix customize pool size "when" condition
  roles/ceph-rgw/tasks/main.yml
Labels: backport-stable-4.0, bug

#4964 ceph-osd: set container objectstore env variables
  roles/ceph-osd/tasks/container_options_facts.yml
  roles/ceph-osd/tasks/main.yml
  roles/ceph-osd/templates/ceph-osd-run.sh.j2
Labels: backport-stable-4.0, bug

#4966 filestore-to-bluestore: --destroy with raw devices
  infrastructure-playbooks/filestore-to-bluestore.yml
  tests/functional/filestore-to-bluestore/container/hosts
  tests/functional/filestore-to-bluestore/container/vagrant_variables.yml
  tests/functional/filestore-to-bluestore/hosts
  tests/functional/filestore-to-bluestore/vagrant_variables.yml
  tests/functional/lvm_setup.yml
  tox-filestore_to_bluestore.ini
Labels: backport-stable-4.0, bug

#4967 common: add a default value for ceph_directories_mode
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-config/tasks/main.yml
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-mds/tasks/common.yml
  roles/ceph-mgr/tasks/common.yml
  roles/ceph-mon/tasks/deploy_monitors.yml
  roles/ceph-nfs/tasks/pre_requisite_non_container.yml
  roles/ceph-osd/tasks/common.yml
  roles/ceph-rgw/tasks/common.yml
Labels: enhancement

#4971 filestore-to-bluestore: fix osd_auto_discovery
  infrastructure-playbooks/filestore-to-bluestore.yml
  tests/functional/filestore-to-bluestore/container/hosts
  tests/functional/filestore-to-bluestore/container/vagrant_variables.yml
  tests/functional/filestore-to-bluestore/hosts
  tests/functional/filestore-to-bluestore/vagrant_variables.yml
Labels: backport-stable-4.0, bug

#4973 rolling_update: support upgrading 3.x + ceph-metrics on a dedicated node
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0, bug

#4976 site-container: don't skip ceph-container-common
  site-container.yml.sample
Labels: backport-stable-4.0, bug

#4978 ceph-facts: Fix for 'running_mon is undefined' error
  roles/ceph-facts/tasks/facts.yml
Labels: backport-stable-4.0, bug

#4980 handler: read container_exec_cmd value from first mon
  roles/ceph-handler/tasks/handler_osds.yml
Labels: backport-stable-4.0, bug

#4985 filestore-to-bluestore: don't fail when with no PV
  infrastructure-playbooks/filestore-to-bluestore.yml
Labels: backport-stable-4.0, bug

#4984 filestore-to-bluestore: skip bluestore osd nodes
  infrastructure-playbooks/filestore-to-bluestore.yml
Labels: backport-stable-4.0, enhancement

#5003 ceph-facts: fix _container_exec_cmd fact value
  roles/ceph-facts/tasks/facts.yml
Labels: backport-stable-4.0, bug

#4999 ceph-defaults: remove rgw from ceph_conf_overrides
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-3.2, backport-stable-4.0, bug

#5004 ceph-container-engine: lvm2 on OSD nodes only
  roles/ceph-container-engine/tasks/pre_requisites/prerequisites.yml
Labels: backport-stable-4.0, enhancement

#5011 [stable-3.2] update: remove legacy tasks
  infrastructure-playbooks/rolling_update.yml
Labels: bug

#5019 ceph-common: rhcs 4 repositories for rhel 7
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install.yml
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0, bug

#5015 validate: allow running ceph-ansible 3.2 against ansible 2.7
  roles/ceph-validate/tasks/check_system.yml
Labels: feature

#5002 iscsi: Fix crashes during rolling update
  roles/ceph-iscsi-gw/tasks/main.yml
  roles/ceph-iscsi-gw/tasks/non-container/postrequisites.yml
  roles/ceph-iscsi-gw/tasks/non-container/prerequisites.yml
Labels: backport-stable-3.2, backport-stable-4.0, bug

#4882 purge: fix purge cluster failed when container images does not exist
  infrastructure-playbooks/purge-cluster.yml
  infrastructure-playbooks/purge-container-cluster.yml
Labels: backport-stable-4.0, enhancement
