Repository ceph/ceph-ansible, pull requests merged in 2020-02, with the labels that each got.

#4997 update: remove legacy tasks
  infrastructure-playbooks/rolling_update.yml
Labels: bug

#4995 ceph-facts: remove is_podman fact
  roles/ceph-facts/tasks/facts.yml
Labels: enhancement

#4952 ceph-facts: set devices osd_auto_discovery on OSDs
  roles/ceph-facts/tasks/facts.yml
Labels: enhancement

#5037 rhcs: update container image name
  group_vars/rhcs.yml.sample
  rhcs_edits.txt
Labels: backport-stable-4.0, bug

#5036 ceph-mon: use interactive session with aliases
  roles/ceph-mon/templates/ceph-aliases.sh.j2
Labels: bug

#5013 switch_to_containers: increase health check values
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0

#4993 dashboard: allow configuring multiple grafana host
  roles/ceph-dashboard/tasks/configure_dashboard.yml
  roles/ceph-dashboard/tasks/configure_grafana_layouts.yml
  roles/ceph-facts/tasks/grafana.yml
Labels: backport-stable-4.0, enhancement

#5052 ceph-validate: fail if no mgr host is present
  roles/ceph-validate/tasks/main.yml
Labels: enhancement

#5051 containers: add KillMode=none to systemd templates
  roles/ceph-grafana/templates/grafana-server.service.j2
  roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2
  roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2
  roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2
  roles/ceph-mds/templates/ceph-mds.service.j2
  roles/ceph-mgr/templates/ceph-mgr.service.j2
  roles/ceph-mon/templates/ceph-mon.service.j2
  roles/ceph-nfs/templates/ceph-nfs.service.j2
  roles/ceph-node-exporter/templates/node_exporter.service.j2
  roles/ceph-osd/templates/ceph-osd.service.j2
  roles/ceph-prometheus/templates/alertmanager.service.j2
  roles/ceph-prometheus/templates/prometheus.service.j2
  roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
  roles/ceph-rgw/templates/ceph-radosgw.service.j2
Labels: enhancement

#5059 ceph-prometheus: add alertmanager HA config
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-infra/tasks/dashboard_firewall.yml
  roles/ceph-prometheus/templates/alertmanager.service.j2
Labels: backport-stable-4.0, enhancement

#5055 ceph-grafana: fix grafana_{crt,key} condition
  roles/ceph-grafana/tasks/configure_grafana.yml
Labels: backport-stable-4.0, bug

#5049 ceph-{mon,osd}: move default crush variables
  group_vars/mons.yml.sample
  group_vars/osds.yml.sample
  roles/ceph-mon/defaults/main.yml
  roles/ceph-osd/defaults/main.yml
  roles/ceph-osd/tasks/crush_rules.yml
  roles/ceph-osd/tasks/main.yml
Labels: backport-stable-3.2, backport-stable-4.0, bug

#5042 ceph-nfs: add nfs-ganesha-rados-urls package
  roles/ceph-nfs/tasks/pre_requisite_non_container_red_hat.yml
Labels: bug

#5048 ceph-nfs: fix ceph_nfs_ceph_user variable
  roles/ceph-nfs/tasks/main.yml
Labels: backport-stable-4.0, bug

#5044 ceph-iscsi: don't use ceph_dev_xxx variables
  roles/ceph-iscsi-gw/tasks/non-container/prerequisites.yml
Labels: enhancement

#5046 tests: don't install s3cmd on containerized setup
  tests/functional/rgw_multisite.yml
Labels: bug

#5040 The _filtered_clients list should intersect with ansible_play_batch
  roles/ceph-client/tasks/create_users_keys.yml
Labels: backport-stable-4.0, enhancement

#4953 purge-cluster: update package list to remove
  infrastructure-playbooks/purge-cluster.yml
Labels: enhancement

#4714 rgw: don't create user on secondary zones
  roles/ceph-dashboard/tasks/configure_dashboard.yml
Labels: backport-stable-4.0, bug, do-not-close

#5028 ceph-rgw-loadbalancer: Fix SSL newline issue
  roles/ceph-rgw-loadbalancer/templates/haproxy.cfg.j2
Labels: backport-stable-4.0, bug

#4688 rgw: extend automatic rgw pool creation capability
  README-MULTISITE.md
  group_vars/rgws.yml.sample
  roles/ceph-rgw/defaults/main.yml
  roles/ceph-rgw/tasks/main.yml
  roles/ceph-rgw/tasks/rgw_create_pools.yml
  roles/ceph-validate/tasks/check_rgw_pools.yml
  roles/ceph-validate/tasks/main.yml
  tests/functional/add-rgws/group_vars/rgws
  tests/functional/all-in-one/container/group_vars/all
  tests/functional/all-in-one/group_vars/all
  tests/functional/all_daemons/container/group_vars/rgws
  tests/functional/all_daemons/group_vars/rgws
  tests/functional/collocation/container/group_vars/rgws
  tests/functional/collocation/group_vars/rgws
  tests/functional/podman/group_vars/rgws
  tests/functional/rgw-multisite/container/group_vars/rgws
  tests/functional/rgw-multisite/container/secondary/group_vars/rgws
  tests/functional/rgw-multisite/group_vars/rgws
  tests/functional/rgw-multisite/secondary/group_vars/rgws
  tests/functional/shrink_rgw/container/group_vars/rgws
  tests/functional/shrink_rgw/group_vars/rgws
Labels: backport-stable-4.0, do-not-close, enhancement

#5056 ceph-defaults: remove bootstrap_dirs_xxx vars
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0, enhancement

#4715 ceph-rgw: Allow SSL certificate content to be supplied
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-rgw/tasks/common.yml
Labels: feature

#5074 ceph-rgw: Fix custom pool size setting
  roles/ceph-rgw/tasks/main.yml
Labels: bug

#5075 [skip ci] tests: pg num should be a power of two number
  tests/functional/all_daemons/container/group_vars/rgws
  tests/functional/all_daemons/group_vars/rgws
  tests/functional/bs-osds/container/group_vars/rgws.yml
  tests/functional/bs-osds/group_vars/rgws.yml
  tests/functional/collocation/container/group_vars/rgws
  tests/functional/collocation/group_vars/rgws
  tests/functional/fs-osds/container/group_vars/rgws.yml
  tests/functional/fs-osds/group_vars/rgws.yml
Labels: enhancement

#5076 tests: pg num should be a power of two number
  tests/functional/all_daemons/container/group_vars/rgws
  tests/functional/all_daemons/group_vars/rgws
  tests/functional/collocation/container/group_vars/rgws
  tests/functional/collocation/group_vars/rgws
  tests/functional/rgw-multisite/container/group_vars/rgws
  tests/functional/rgw-multisite/container/secondary/group_vars/rgws
  tests/functional/rgw-multisite/group_vars/rgws
  tests/functional/rgw-multisite/secondary/group_vars/rgws
Labels: enhancement

#5077 ceph-dashboard: update create/get rgw user tasks
  roles/ceph-dashboard/tasks/configure_dashboard.yml
  tests/functional/tests/rgw/test_rgw_tuning.py
Labels: bug

#4903 infrastructure-playbooks: Run shrink-osd tasks on monitor
  infrastructure-playbooks/shrink-osd.yml
Labels: backport-stable-4.0, bug

#5054 Configure ceph dashboard backend and dashboard_frontend_vip
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-dashboard/tasks/configure_dashboard.yml
  roles/ceph-dashboard/tasks/configure_dashboard_backends.yml
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-prometheus/templates/prometheus.service.j2
Labels: backport-stable-4.0, enhancement

#5086 ceph-rgw: increase connection timeout to 10
  roles/ceph-rgw/tasks/rgw_create_pools.yml
Labels: backport-stable-4.0, enhancement

#5093 doc: update infra playbooks statements
  infrastructure-playbooks/README.md
Labels: documentation

#5034 filestore-to-bluestore: reuse dedicated journal
  infrastructure-playbooks/filestore-to-bluestore.yml
Labels: backport-stable-4.0, enhancement

#5083 shrink-osd: support shrinking a legacy ceph-disk prepared osd with ceph-volume
  infrastructure-playbooks/shrink-osd.yml
Labels: backport-stable-4.0, bug

#5087 common: support OSDs with more than 2 digits
  infrastructure-playbooks/purge-container-cluster.yml
  infrastructure-playbooks/rolling_update.yml
  roles/ceph-handler/templates/restart_osd_daemon.sh.j2
Labels: backport-stable-4.0, bug

#5099 requirements: enforce ansible version requirement
  requirements.txt
  tests/requirements.txt
Labels: backport-stable-4.0
