Repository ceph/ceph-ansible, pull requests merged in 2021-12, with the labels that each got.

#7008 validate: support obs repository
  roles/ceph-validate/tasks/check_repository.yml
Labels: backport-stable-5.0, backport-stable-6.0

#7000 [skip ci] purge: remove ceph directories on client nodes
  infrastructure-playbooks/purge-cluster.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6969 make grafana network configurable option
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-facts/tasks/grafana.yml
Labels: backport-stable-5.0, backport-stable-6.0

#7016 [skip ci] cephadm-adopt: ensure /etc/ceph is present on monitoring node
  infrastructure-playbooks/cephadm-adopt.yml
Labels: backport-stable-5.0, backport-stable-6.0

#7021 container: align systemd units with rpm
  roles/ceph-crash/templates/ceph-crash.service.j2
  roles/ceph-grafana/templates/grafana-server.service.j2
  roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2
  roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2
  roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2
  roles/ceph-mds/templates/ceph-mds.service.j2
  roles/ceph-mgr/templates/ceph-mgr.service.j2
  roles/ceph-mon/templates/ceph-mon.service.j2
  roles/ceph-nfs/templates/ceph-nfs.service.j2
  roles/ceph-node-exporter/templates/node_exporter.service.j2
  roles/ceph-osd/templates/ceph-osd.service.j2
  roles/ceph-prometheus/templates/alertmanager.service.j2
  roles/ceph-prometheus/templates/prometheus.service.j2
  roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
  roles/ceph-rgw/templates/ceph-radosgw.service.j2
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6992 [skip ci] update: speed up client play
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#7029 [skip ci] common: remove legacy repositories
  roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install.yml
Labels: backport-stable-6.0
