Repository ceph/ceph-ansible, pull requests merged in 2021-05, with the labels that each got.

#6507 [skip ci] update: fix ceph-crash stop task
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6517 ceph-rgw: fix pg_autoscale_mode for pool
  roles/ceph-rgw/tasks/rgw_create_pools.yml
Labels: backport-stable-5.0, backport-stable-6.0, bug

#6519 [skip ci] nfs: get org.ganesha.nfsd.conf from container
  roles/ceph-nfs/tasks/pre_requisite_container.yml
Labels: backport-stable-5.0, backport-stable-6.0

#6532 Make sure the repo url contains the correct arch
  roles/ceph-common/tasks/installs/debian_dev_repository.yml
Labels: bug, teuthology-impact

#6533 Make sure the repo url contains the correct arch
  roles/ceph-common/tasks/installs/debian_dev_repository.yml
Labels: bug, teuthology-impact

#6534 [skip ci] update: do not gather facts on each play
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6547 prometheus: enforce osd nodes in templates
  roles/ceph-prometheus/templates/prometheus.yml.j2
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6551 [skip ci] fs2bs: fix wrong filter when setting osd_ids
  infrastructure-playbooks/filestore-to-bluestore.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6558 fs2bs: use match filter in selectattr()
  infrastructure-playbooks/filestore-to-bluestore.yml
Labels: backport-stable-6.0

#6562 dashboard: fix typo introduced during backport
  infrastructure-playbooks/rolling_update.yml
  roles/ceph-common/tasks/installs/prerequisite_rhcs_cdn_install.yml
Labels: backport-stable-4.0

#6561 crash: fix --limit deployments (containers)
  roles/ceph-crash/tasks/main.yml
Labels: fixes a bz
