Repository ceph/ceph-ansible, pull requests merged in 2021-02, with the labels that each got.

#6211 ceph-facts: set rgw_instances_all fact once
  roles/ceph-facts/tasks/set_radosgw_address.yml
Labels: enhancement

#6228 rgw: quick fix in create_zone_user.yml
  roles/ceph-rgw/tasks/multisite/create_zone_user.yml
Labels: fixes a bz

#6229 [skip ci] purge: zap and destroy db and wal devices for lvm batch
  infrastructure-playbooks/purge-cluster.yml
  infrastructure-playbooks/purge-container-cluster.yml
Labels: backport-stable-4.0, backport-stable-5.0, fixes a bz

#6190 osd: support adding osd in auto discovery scenario
  roles/ceph-osd/tasks/start_osds.yml
  roles/ceph-osd/templates/ceph-osd-run.sh.j2
Labels: fixes a bz

#6230 ceph-defaults: use https for download.ceph.com
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: enhancement

#6174 library/cephadm_bootstrap: add registry support
  library/cephadm_bootstrap.py
  tests/library/test_cephadm_bootstrap.py
Labels: enhancement, modules

#6187 purge-cluster: use parted ansible module
  infrastructure-playbooks/purge-cluster.yml
Labels: enhancement

#6205 cephadm-adopt: use ceph_osd_flag module
  infrastructure-playbooks/cephadm-adopt.yml
Labels: enhancement

#6203 [skip ci] library: fix idempotency in ceph_mgr_module
  library/ceph_mgr_module.py
  tests/library/test_ceph_mgr_module.py
Labels: bug, modules

#6245 vagrant: remove centos/8 workaround
  tests/scripts/vagrant_up.sh
Labels: backport-stable-5.0, enhancement

#6238 dashboard: update with the new monitoring group
  dashboard.yml
Labels: bug

#6223 docs: nautilus uses ansible 2.9
  docs/source/index.rst
Labels: documentation

#6239 rolling_update: exclude clients from node-exporter
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0, backport-stable-5.0, bug

#6259 [skip ci] tests: pin ansible-lint version
  .github/workflows/ansible-lint.yml
Labels: backport-stable-4.0, backport-stable-5.0

#6214 doc: update containerized deployment
  docs/source/installation/containerized.rst
Labels: documentation

#6206 cephadm-adopt: remove prometheus workaround
  infrastructure-playbooks/cephadm-adopt.yml
Labels: enhancement

#6266 [skip ci] doc: add a note about "latest" tags
  docs/source/installation/containerized.rst
Labels: backport-stable-3.2, backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6272 [skip ci] switch2container: do not serialize the ceph-crash migration
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6237 purge: rm service-cid files
  infrastructure-playbooks/purge-container-cluster.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6234 Add quincy release
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-common/tasks/release-rhcs.yml
  roles/ceph-container-common/tasks/release.yml
  roles/ceph-defaults/defaults/main.yml
  tests/conftest.py
Labels: feature

#6256 library: do not always add --yes in batch mode
  library/ceph_volume.py
Labels: backport-stable-4.0, backport-stable-5.0

#6280 requirements.txt: Move the six dependency into the general requirements
  requirements.txt
  tests/requirements.txt
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6289 defaults: update rhcs dashboard images versions
  group_vars/rhcs.yml.sample
  rhcs_edits.txt
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0
