Repository ceph/ceph-ansible, pull requests merged in 2021-01, with the labels that each got.

#6165 [skip ci] library: add no_log to {access,secret}_key params
  library/radosgw_user.py
  library/radosgw_zone.py
Labels: enhancement, modules

#6156 [skip ci] library: remove containerized parameter from cv
  library/ceph_volume.py
Labels: backport-stable-4.0, backport-stable-5.0, enhancement, modules

#6168 [skip ci] rgw: support switching from single-site to multisite
  roles/ceph-handler/tasks/main.yml
  roles/ceph-rgw/tasks/multisite.yml
Labels: backport-stable-4.0, backport-stable-5.0

#6163 [skip ci] Path for ceph config missing in crash template
  roles/ceph-crash/templates/ceph-crash.service.j2
Labels: backport-stable-4.0, backport-stable-5.0, bug

#6175 [skip ci] spec: add module_utils directory
  ceph-ansible.spec.in
Labels: bug, fixes a bz

#6177 ceph-osd: replace sysctl command task by slurp
  roles/ceph-osd/tasks/system_tuning.yml
Labels: enhancement

#6154 [skip ci] switch2container: fix mon quorum check
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Labels: backport-stable-4.0, backport-stable-5.0, fixes a bz

#6143 [skip ci] fs2bs: skip migration when a mix of fs and bs is detected
  infrastructure-playbooks/filestore-to-bluestore.yml
Labels: backport-stable-4.0, backport-stable-5.0, fixes a bz

#6193 [skip ci] tests/library: remove duplicate parameter
  tests/library/test_ceph_dashboard_user.py
Labels: tests

#6191 module_utils: don't add newline to the data
  module_utils/ca_common.py
  tests/module_utils/test_ca_common.py
Labels: bug, modules

#6188 mon: fix cephx disabled deployment
  roles/ceph-mon/tasks/deploy_monitors.yml
Labels: backport-stable-4.0, backport-stable-5.0, fixes a bz

#6196 cephadm-adopt: add grafana group conversion
  infrastructure-playbooks/cephadm-adopt.yml
Labels: bug, fixes a bz

#6208 ceph-defaults: change default ceph container tag
  group_vars/all.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-5.0, bug

#6200 grafana: update container tag to 6.7.4
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  rhcs_edits.txt
  roles/ceph-defaults/defaults/main.yml
  tests/functional/all_daemons/container/group_vars/all
  tests/functional/all_daemons/group_vars/all
  tests/functional/collocation/container/group_vars/all
  tests/functional/collocation/group_vars/all
  tests/functional/docker2podman/group_vars/all
  tests/functional/podman/group_vars/all
Labels: enhancement

#6218 rgw: avoid useless call to ceph-rgw
  roles/ceph-handler/tasks/main.yml
  roles/ceph-rgw/tasks/main.yml
Labels: enhancement

#6189 ceph-mon: add ExecStartPre docker stop to systemd
  roles/ceph-mon/templates/ceph-mon.service.j2
Labels: backport-stable-3.2, backport-stable-4.0, backport-stable-5.0, fixes a bz
