Repository ceph/ceph-ansible, pull requests merged in 2021-11, with the labels that each got.

#6983 [skip ci] update: move a set_fact
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6982 [skip ci] cephadm-adopt: remove logrotate configuration
  infrastructure-playbooks/cephadm-adopt.yml
Labels: bug, backport-stable-6.0

#6995 validate: fix bug when using vault
  roles/ceph-validate/tasks/main.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#7002 [skip ci] adopt: fix ceph_origin and ceph_repository defaults
  infrastructure-playbooks/cephadm-adopt.yml
Labels: backport-stable-5.0, backport-stable-6.0
