Repository ceph/ceph-ansible, pull requests merged in 2021-07, with the labels that each got.

#6656 [skip ci] prometheus: fix prometheus target url
  roles/ceph-prometheus/templates/prometheus.yml.j2
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, bug, fixes a bz

#6655 [skip ci] purge: add monitoring group in final cleanup play
  infrastructure-playbooks/purge-container-cluster.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, fixes a bz

#6625 [skip ci] cephadm_adopt: add any_errors_fatal on play
  infrastructure-playbooks/cephadm-adopt.yml
Labels: backport-stable-5.0, backport-stable-6.0, fixes a bz

#6665 [skip ci] ceph-crash: add install checkpoint
  plugins/callback/installer_checkpoint.py
  site-container.yml.sample
  site.yml.sample
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, enhancement

#6667 [skip ci] dashboard: support dedicated network for the dashboard
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-dashboard/tasks/configure_dashboard_backends.yml
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, fixes a bz

#6673 [skip ci] workflow: add dashboard playbook to ansible-lint
  .github/workflows/ansible-lint.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, enhancement

#6680 [skip ci] dashboard: remove "certificate is valid for" error
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-dashboard/tasks/configure_dashboard.yml
  roles/ceph-dashboard/tasks/configure_dashboard_backends.yml
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6687 [skip ci] cephadm-adopt: set application on ganesha pool
  infrastructure-playbooks/cephadm-adopt.yml
Labels: backport-stable-6.0, fixes a bz

#6689 [skip ci] update: convert straw bucket
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6693 [skip ci] update: followup on pr #6689
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-5.0, backport-stable-6.0

#6700 [skip ci] update: fail the playbook if straw2 conversion failed
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6704 [skip ci] rolling_update: check quorum state before upgrade
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, enhancement, fixes a bz

#6706 [skip ci] cephadm-adopt: enable osd memory autotune for HCI
  infrastructure-playbooks/cephadm-adopt.yml
Labels: backport-stable-6.0, enhancement, fixes a bz

#6696 lib/ceph-volume: support zapping by osd_id
  library/ceph_volume.py
  tests/library/test_ceph_volume.py
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6711 |skip ci] purge: reindent playbook
  infrastructure-playbooks/purge-cluster.yml
  infrastructure-playbooks/purge-container-cluster.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, enhancement

#6721 [skip ci] ceph-nfs: allow overriding NFS_CORE_PARAM
  group_vars/nfss.yml.sample
  roles/ceph-nfs/defaults/main.yml
  roles/ceph-nfs/templates/ganesha.conf.j2
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, feature, fixes a bz

#6720 [skip ci] ceph-mgr: move mgr module list to common
  roles/ceph-mgr/tasks/common.yml
  roles/ceph-mgr/tasks/main.yml
  roles/ceph-mgr/tasks/mgr_modules.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, bug

#6591 common: disable/enable pg_autoscaler
  infrastructure-playbooks/cephadm-adopt.yml
  infrastructure-playbooks/rolling_update.yml
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
  roles/ceph-facts/tasks/facts.yml
  roles/ceph-handler/tasks/handler_osds.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, do-not-close, fixes a bz

#6734 common: fix py2 pool_list from_json when skipped
  infrastructure-playbooks/cephadm-adopt.yml
  infrastructure-playbooks/rolling_update.yml
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
  roles/ceph-handler/tasks/handler_osds.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, bug

#6733 [skip ci] common: remove unnecessary run_once statements
  infrastructure-playbooks/rolling_update.yml
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, enhancement

#6705 [skip ci] multisite: use node fqdn for endpoints when https
  roles/ceph-rgw/tasks/multisite/main.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, fixes a bz

#6748 [skip ci] alertmanager: allow disable dashboard tls verify
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-prometheus/templates/alertmanager.yml.j2
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, fixes a bz

#6728 ceph-mgr: don't install dashboard pkg by default
  group_vars/mgrs.yml.sample
  roles/ceph-mgr/defaults/main.yml
  roles/ceph-mgr/tasks/pre_requisite.yml
Labels: enhancement

#6752 [skip ci] update: check the ceph release
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6759 [skip ci] ceph-defaults: add missing grafana dashboards
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, enhancement

#6763 [skip ci][stable-6.0] ceph-defaults: update grafana dashboards source
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: enhancement

#6764 [skip ci][stable-5.0] ceph-defaults: update grafana dashboards source
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: enhancement
