Repository ceph/ceph-ansible, pull requests merged in 2021-06, with the labels that each got.

#6566 dashboard: fix rgw user creation
  roles/ceph-dashboard/tasks/configure_dashboard.yml
Labels: fixes a bz

#6574 tests: use CentOS 8.4 image
  tests/scripts/vagrant_up.sh
Labels: backport-stable-5.0, backport-stable-6.0

#6577 rolling_update: fix mon+rgw/multisite collocation
  roles/ceph-handler/tasks/main.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6575 [skip ci] cephadm-adopt: fix mgr placement hosts task
  infrastructure-playbooks/cephadm-adopt.yml
Labels: backport-stable-5.0, backport-stable-6.0

#6572 ceph_key: handle error in a better way
  library/ceph_key.py
  roles/ceph-mon/tasks/deploy_monitors.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6596 nfs: do no copy client.bootstrap-rgw when using mds
  roles/ceph-nfs/tasks/pre_requisite_container.yml
Labels: backport-stable-4.0, backport-stable-6.0

#6603 multisite: fix bug during switch2containers
  roles/ceph-facts/tasks/set_radosgw_address.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6618 [skip ci] cephadm-adopt: support rgw multisite adoption
  infrastructure-playbooks/cephadm-adopt.yml
Labels: backport-stable-5.0, backport-stable-6.0

#6573 dashboard: Add new prometheus alert
  roles/ceph-prometheus/files/ceph_dashboard.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6627 [skip ci] switch2container: run ceph-validate role
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, fixes a bz

#6633 [skip ci] cephadm-adopt/rgw: add host target in svc_id
  infrastructure-playbooks/cephadm-adopt.yml
Labels: backport-stable-5.0, backport-stable-6.0

#6615 library: flake8 ceph-ansible modules
  library/ceph_add_users_buckets.py
  library/ceph_crush.py
  library/ceph_crush_rule.py
  library/ceph_dashboard_user.py
  library/ceph_ec_profile.py
  library/ceph_fs.py
  library/ceph_key.py
  library/ceph_mgr_module.py
  library/ceph_osd.py
  library/ceph_osd_flag.py
  library/ceph_pool.py
  library/ceph_volume.py
  library/cephadm_adopt.py
  library/cephadm_bootstrap.py
  library/igw_client.py
  library/igw_gateway.py
  library/igw_lun.py
  library/igw_purge.py
  library/radosgw_realm.py
  library/radosgw_user.py
  library/radosgw_zone.py
  library/radosgw_zonegroup.py
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6628 rhcs: remove ISO install method
  docs/source/installation/non-containerized.rst
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  infrastructure-playbooks/purge-cluster.yml
  infrastructure-playbooks/rolling_update.yml
  roles/ceph-common/tasks/installs/prerequisite_rhcs_iso_install.yml
  roles/ceph-common/tasks/installs/redhat_rhcs_repository.yml
  roles/ceph-common/templates/redhat_storage_repo.j2
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-validate/tasks/check_system.yml
  roles/ceph-validate/tasks/main.yml
Labels: backport-stable-6.0, enhancement, feature

#6640 container: set tcmalloc value by default
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-common/tasks/configure_memory_allocator.yml
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-mds/templates/ceph-mds.service.j2
  roles/ceph-mgr/templates/ceph-mgr.service.j2
  roles/ceph-mon/templates/ceph-mon.service.j2
  roles/ceph-osd/templates/ceph-osd.service.j2
  roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
  roles/ceph-rgw/templates/ceph-radosgw.service.j2
  site.yml.sample
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, enhancement, fixes a bz
