Repository ceph/ceph-ansible, pull requests merged in 2021-08, with the labels that each got.

#6779 [skip ci] rolling_update: get ceph version when mons exist
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, bug

#6773 [skip ci] library: exit on user creation failure
  library/ceph_dashboard_user.py
  tests/library/test_ceph_dashboard_user.py
Labels: backport-stable-5.0, backport-stable-6.0, bug

#6774 [skip ci] osds: use osd pool ls instead of osd dump command
  infrastructure-playbooks/cephadm-adopt.yml
  infrastructure-playbooks/rolling_update.yml
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
  roles/ceph-handler/tasks/handler_osds.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, enhancement

#6778 ceph-defaults: remove radosgw_civetweb_ variables
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-validate/tasks/main.yml
Labels: enhancement

#6777 [skip ci] container: add pids limit parameter
  roles/ceph-crash/templates/ceph-crash.service.j2
  roles/ceph-grafana/templates/grafana-server.service.j2
  roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2
  roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2
  roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2
  roles/ceph-mds/templates/ceph-mds.service.j2
  roles/ceph-mgr/templates/ceph-mgr.service.j2
  roles/ceph-mon/templates/ceph-mon.service.j2
  roles/ceph-nfs/templates/ceph-nfs.service.j2
  roles/ceph-node-exporter/templates/node_exporter.service.j2
  roles/ceph-osd/templates/ceph-osd.service.j2
  roles/ceph-prometheus/templates/alertmanager.service.j2
  roles/ceph-prometheus/templates/prometheus.service.j2
  roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
  roles/ceph-rgw/templates/ceph-radosgw.service.j2
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, fixes a bz

#6788 [skip ci] infra: use dedicated variables for balancer status
  infrastructure-playbooks/cephadm-adopt.yml
  infrastructure-playbooks/rolling_update.yml
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, fixes a bz

#6795 [skip ci] cephadm-adopt: remove nfs pool and namespace
  infrastructure-playbooks/cephadm-adopt.yml
Labels: bug

#6775 [skip ci] adopt: import rgw ssl certificate into kv store
  infrastructure-playbooks/cephadm-adopt.yml
Labels: blocker, fixes a bz, backport-stable-6.0

#6798 [skip ci] dashboard: subj_alt_names fact refactor
  roles/ceph-dashboard/tasks/configure_dashboard.yml
Labels: backport-stable-4.0, backport-stable-5.0, fixes a bz, backport-stable-6.0

#6803 [skip ci] Fixes typo in rgw-add-users-buckets playbook
  infrastructure-playbooks/rgw-add-users-buckets.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6804 add-osd: use container_exec_cmd fact from mon host
  infrastructure-playbooks/add-osd.yml
Labels: fixes a bz

#6810 ceph-dashboard: fix TLS cert openssl generation
  roles/ceph-dashboard/tasks/configure_dashboard.yml
Labels: bug

#6813 switch2container: fix mon quorum check
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Labels: fixes a bz

#6808 common: do not log keyring secret
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-client/tasks/create_users_keys.yml
  roles/ceph-client/tasks/pre_requisite.yml
  roles/ceph-crash/tasks/main.yml
  roles/ceph-defaults/defaults/main.yml
  roles/ceph-iscsi-gw/tasks/common.yml
  roles/ceph-mds/tasks/common.yml
  roles/ceph-mds/tasks/non_containerized.yml
  roles/ceph-mgr/tasks/common.yml
  roles/ceph-mon/tasks/ceph_keys.yml
  roles/ceph-mon/tasks/deploy_monitors.yml
  roles/ceph-nfs/tasks/main.yml
  roles/ceph-nfs/tasks/pre_requisite_container.yml
  roles/ceph-nfs/tasks/pre_requisite_non_container.yml
  roles/ceph-osd/tasks/common.yml
  roles/ceph-osd/tasks/openstack_config.yml
  roles/ceph-rbd-mirror/tasks/common.yml
  roles/ceph-rgw/tasks/common.yml
  roles/ceph-rgw/tasks/pre_requisite.yml
Labels: backport-stable-4.0, backport-stable-5.0, fixes a bz, backport-stable-6.0

#6823 [skip ci] ceph-mon: do not log monitor keyring
  roles/ceph-mon/tasks/deploy_monitors.yml
Labels: enhancement, backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6829 tests: use old build of ceph@master
  tox.ini
Labels: tests

#6827 ceph-volume: hide OSD keyring during creation
  library/ceph_volume.py
  tests/library/test_ceph_volume.py
Labels: enhancement

#6833 ceph-dashboard: fix object gateway integration
  roles/ceph-dashboard/tasks/configure_dashboard.yml
Labels: bug

#6832 [skip ci] update: gather facts only one time
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6814 [skip ci] roles: remove leftover from pr #4319
  roles/ceph-iscsi-gw/tasks/systemd.yml
  roles/ceph-mds/tasks/systemd.yml
  roles/ceph-mgr/tasks/systemd.yml
  roles/ceph-mon/tasks/systemd.yml
  roles/ceph-nfs/tasks/systemd.yml
  roles/ceph-rbd-mirror/tasks/systemd.yml
  roles/ceph-rgw/tasks/systemd.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6797 [skip ci] ceph-container-engine: allow override container_package_name and container_service_name
  roles/ceph-container-engine/tasks/pre_requisites/prerequisites.yml
  roles/ceph-validate/tasks/main.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6815 [skip ci] Vagrantfile: fallback on 'varant_variables.yml.sample'
  Vagrantfile
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6818 [skip ci] containers: introduce target systemd unit
  infrastructure-playbooks/cephadm-adopt.yml
  infrastructure-playbooks/purge-cluster.yml
  roles/ceph-container-common/files/ceph.target
  roles/ceph-container-common/tasks/main.yml
  roles/ceph-crash/templates/ceph-crash.service.j2
  roles/ceph-mds/files/ceph-mds.target
  roles/ceph-mds/tasks/containerized.yml
  roles/ceph-mds/tasks/systemd.yml
  roles/ceph-mds/templates/ceph-mds.service.j2
  roles/ceph-mgr/files/ceph-mgr.target
  roles/ceph-mgr/tasks/start_mgr.yml
  roles/ceph-mgr/tasks/systemd.yml
  roles/ceph-mgr/templates/ceph-mgr.service.j2
  roles/ceph-mon/files/ceph-mon.target
  roles/ceph-mon/tasks/systemd.yml
  roles/ceph-mon/templates/ceph-mon.service.j2
  roles/ceph-osd/files/ceph-osd.target
  roles/ceph-osd/tasks/systemd.yml
  roles/ceph-osd/templates/ceph-osd.service.j2
  roles/ceph-rbd-mirror/files/ceph-rbd-mirror.target
  roles/ceph-rbd-mirror/tasks/systemd.yml
  roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
  roles/ceph-rgw/files/ceph-radosgw.target
  roles/ceph-rgw/tasks/systemd.yml
  roles/ceph-rgw/templates/ceph-radosgw.service.j2
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6850 [skip ci] cephadm-adopt: remove ceph-nfs.target
  infrastructure-playbooks/cephadm-adopt.yml
Labels: enhancement, backport-stable-6.0

#6846 [skip ci] iscsi: don't set default value for trusted_ip_list
  group_vars/iscsigws.yml.sample
  roles/ceph-iscsi-gw/defaults/main.yml
  roles/ceph-iscsi-gw/tasks/common.yml
  roles/ceph-iscsi-gw/templates/iscsi-gateway.cfg.j2
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6857 Revert "tests: use old build of ceph@master"
  tox.ini
Labels: tests

#6856 [skip ci] container: explicitly pull monitoring images
  roles/ceph-container-common/tasks/fetch_image.yml
Labels: bug, backport-stable-4.0, backport-stable-5.0, backport-stable-6.0
