Repository ceph/ceph-ansible, pull requests merged in 2021-04, with the labels that each got.

#6184 container/registry: use password from stdin
  roles/ceph-container-common/tasks/registry.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, enhancement

#6430 osd: fix bug in osd activation (container)
  roles/ceph-osd/tasks/start_osds.yml
Labels: fixes a bz

#6429 [skip ci] switch_to_containers: support iscsigws migration
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, fixes a bz

#6434 docker2podman: skip some role imports from handler
  infrastructure-playbooks/docker-to-podman.yml
  roles/ceph-facts/tasks/container_binary.yml
  roles/ceph-handler/tasks/main.yml
Labels: backport-stable-3.2, backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6442 [skip ci] docker2podman: add documentation/header
  infrastructure-playbooks/docker-to-podman.yml
Labels: backport-stable-3.2, backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6448 [skip ci] rbdmirror: add retries/until when configuring mirroring
  roles/ceph-rbd-mirror/tasks/configure_mirroring.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6450 [skip ci] fs2bs: add a final play
  infrastructure-playbooks/filestore-to-bluestore.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, enhancement

#6456 container/systemd: ensure /var/log/ceph exists
  roles/ceph-iscsi-gw/templates/rbd-target-api.service.j2
  roles/ceph-iscsi-gw/templates/rbd-target-gw.service.j2
  roles/ceph-iscsi-gw/templates/tcmu-runner.service.j2
  roles/ceph-mds/templates/ceph-mds.service.j2
  roles/ceph-mgr/templates/ceph-mgr.service.j2
  roles/ceph-mon/templates/ceph-mon.service.j2
  roles/ceph-nfs/templates/ceph-nfs.service.j2
  roles/ceph-osd/templates/ceph-osd.service.j2
  roles/ceph-rbd-mirror/templates/ceph-rbd-mirror.service.j2
  roles/ceph-rgw/templates/ceph-radosgw.service.j2
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6433 [skip ci] switch-to-containers: only chown corresponding files
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Labels: backport-stable-3.2, backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6449 [skip ci] ceph-rgw-loadbalancer: Fix rgw_ports fact
  roles/ceph-rgw-loadbalancer/tasks/pre_requisite.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6452 Config the monitoring stack components api urls using a VIP
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-dashboard/tasks/configure_dashboard.yml
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6475 [skip ci] docs: update ansible version for master
  docs/source/index.rst
Labels: documentation

#6476 [skip ci] ceph-defaults: update multisite readme reference
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: bug

#6487 [skip ci] cephadm_adopt: create a 'nfs-ganesha' pool
  infrastructure-playbooks/cephadm-adopt.yml
Labels: backport-stable-5.0, backport-stable-6.0

#6493 [skip ci] cephadm_adopt: fix ceph-crash migration
  infrastructure-playbooks/cephadm-adopt.yml
Labels: backport-stable-5.0, backport-stable-6.0

#5936 ceph-osd: allow to use ceph_tcmalloc_max_total_thread_cache for bluestore
  roles/ceph-common/tasks/main.yml
  roles/ceph-osd/templates/ceph-osd.service.j2
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, stale
