Repository ceph/ceph-ansible, pull requests merged in 2021-09, with the labels that each got.

#6869 [skip ci] purge-dashboard: remove cid files
  infrastructure-playbooks/purge-dashboard.yml
Labels: enhancement, backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6864 [skip ci] ceph-defaults: set quay.io as the default registry
  group_vars/all.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: feature, backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6830 [skip ci] purge: add container_binary needed for zap osds
  infrastructure-playbooks/purge-cluster.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6812 tests: rename grafana to monitoring
  tests/conftest.py
  tests/functional/tests/monitoring/test_monitoring.py
Labels: enhancement, do-not-close, tests, backport-stable-6.0

#6887 [skip ci] cephadm-adopt: set cephadm registry login info
  infrastructure-playbooks/cephadm-adopt.yml
Labels: backport-stable-5.0, backport-stable-6.0

#6893 [skip ci] tests: fix container-cephadm job
  tests/functional/cephadm/group_vars/all
Labels: backport-stable-5.0, backport-stable-6.0

#6816 tests: auth_allow_insecure_global_id_reclaim false
  tests/functional/all_daemons/ceph-override.json
  tests/functional/all_daemons/container/group_vars/all
  tests/functional/all_daemons/group_vars/all
  tests/functional/collocation/container/group_vars/all
  tests/functional/collocation/group_vars/all
Labels: tests

#6901 adopt: stop iscsi services in the first place
  infrastructure-playbooks/cephadm-adopt.yml
Labels: backport-stable-5.0, backport-stable-6.0

#6898 [skip ci] cephadm-adopt: add no_log: true
  infrastructure-playbooks/cephadm-adopt.yml
Labels: backport-stable-5.0, backport-stable-6.0

#6899 dashboard: allow disabling of unused features
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-dashboard/tasks/configure_dashboard.yml
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-5.0, backport-stable-6.0
