Repository ceph/ceph-ansible, pull requests merged in 2021-03, with the labels that each got.

#6302 dashboard: add missing parameter in `ceph_cmd`
  roles/ceph-dashboard/tasks/configure_dashboard.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6296 [skip ci] Fix typo and broken link for documenting RGW frontends
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6300 debian/uca: remove the handler notification (backport)
  roles/ceph-common/tasks/installs/debian_uca_repository.yml
  roles/ceph-handler/handlers/main.yml
Labels: backport-stable-4.0

#6209 facts: support device aliases for (dedicated|bluestore_wal)_devices (bp #5584)
  roles/ceph-facts/tasks/facts.yml
Labels: fixes a bz

#6324 [skip ci] Docs: fix some typos
  docs/source/day-2/upgrade.rst
  docs/source/dev/index.rst
  docs/source/index.rst
  docs/source/installation/methods.rst
  docs/source/installation/non-containerized.rst
  docs/source/osds/scenarios.rst
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6213 library: add realm pull to radosgw_realm module
  library/radosgw_realm.py
  roles/ceph-rgw/tasks/multisite/secondary.yml
  tests/library/test_radosgw_realm.py
Labels: enhancement, feature, modules

#6337 config: reset num_osds
  roles/ceph-config/tasks/main.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6332 [skip ci] update: convert legacy grafana-server groupname early
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-5.0, backport-stable-6.0

#6347 adopt: convert legacy grafana-server groupname early
  infrastructure-playbooks/cephadm-adopt.yml
Labels: backport-stable-6.0

#6346 facts: fix nfs/external cluster scenario
  roles/ceph-facts/tasks/facts.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6350 [skip ci] cephadm_adopt: fetch and write ceph minimal config
  infrastructure-playbooks/cephadm-adopt.yml
Labels: backport-stable-5.0, backport-stable-6.0

#6359 [skip ci] rolling_update: unmask monitor service after a failure
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, fixes a bz

#6360 [skip ci] fix 'command -v' tasks
  infrastructure-playbooks/docker-to-podman.yml
  infrastructure-playbooks/purge-cluster.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6368 Make sure the repo url contains the correct arch
  roles/ceph-common/tasks/installs/debian_dev_repository.yml
Labels: backport-stable-6.0, bug, teuthology-impact

#6380 [skip ci] README-MULTISITE: fix typos
  README-MULTISITE.md
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, documentation

#6219 [skip ci] docs: rgw multisite docs with new rgw_instances config
  README-MULTISITE.md
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, documentation, stale

#6379 Peer addition won't be skipped if remote is not in peer
  roles/ceph-rbd-mirror/tasks/configure_mirroring.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6392 update: stop ceph-crash service before upgrading
  infrastructure-playbooks/rolling_update.yml
Labels: bug, fixes a bz

#6306 dashboard: support igw nodes with dedicated subnet
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-dashboard/tasks/configure_dashboard.yml
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0, stale

#6398 [skip ci] update: followup on 07029e1
  infrastructure-playbooks/rolling_update.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6404 common,iscsi: don't use the shaman search endpoint
  roles/ceph-common/tasks/installs/debian_dev_repository.yml
  roles/ceph-common/tasks/installs/redhat_dev_repository.yml
  roles/ceph-iscsi-gw/tasks/non-container/prerequisites.yml
Labels: bug, enhancement

#6403 [skip ci] defaults: add a comment about `igw_network`
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#6402 rgw: supports pg_autoscale_mode option for pool creation
  roles/ceph-rgw/tasks/rgw_create_pools.yml
Labels: backport-stable-5.0, backport-stable-6.0

#6338 nfs: set idmap config for Ceph-NFS
  group_vars/nfss.yml.sample
  roles/ceph-nfs/defaults/main.yml
  roles/ceph-nfs/tasks/start_nfs.yml
  roles/ceph-nfs/templates/ganesha.conf.j2
  roles/ceph-nfs/templates/idmap.conf.j2
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0
