Repository ceph/ceph-ansible, pull requests merged in 2022-02, with the labels that each got.

#7069 [skip ci] Add with_pkg tag on package related tasks
  infrastructure-playbooks/cephadm-adopt.yml
Labels: backport-stable-5.0, backport-stable-6.0

#7058 [skip ci] Remove the remaining packages
  infrastructure-playbooks/purge-cluster.yml
Labels: backport-stable-5.0, backport-stable-6.0

#7065 Grafana server proxy
  roles/ceph-grafana/templates/grafana-server.service.j2
Labels: backport-stable-5.0, backport-stable-6.0

#7081 [skip ci] adopt: check for POOL_APP_NOT_ENABLED warning
  infrastructure-playbooks/cephadm-adopt.yml
Labels: backport-stable-5.0, backport-stable-6.0

#7084 [skip ci] adopt: fix rbd-mirror adoption
  infrastructure-playbooks/cephadm-adopt.yml
Labels: backport-stable-6.0

#7052 ceph-facts: ignore mounted disks on osd auto discovery
  roles/ceph-facts/tasks/devices.yml
Labels: backport-stable-5.0, backport-stable-6.0

#7093 [skip ci] switch2containers: fail if less than 3 monitors
  infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0
