Repository ceph/ceph-ansible, pull requests merged in 2022-04, with the labels that each got.

#7122 validate: drop a check
  roles/ceph-validate/tasks/check_system.yml
Labels: backport-stable-6.0

#7134 ceph-facts: fix ansible templating error for auto osd discovery
  roles/ceph-facts/tasks/devices.yml
Labels: backport-stable-5.0, backport-stable-6.0

#7138 [skip ci] dashboard: allow collecting stats from the host
  roles/ceph-node-exporter/templates/node_exporter.service.j2
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#7128 added AlmaLinux and Rocky for iscsi deploy
  roles/ceph-validate/tasks/check_iscsi.yml
Labels: backport-stable-6.0

#7141 [skip ci] contrib: add a playbook
  infrastructure-playbooks/backup-and-restore-ceph-files.yml
Labels: stale
