Repository ceph/ceph-ansible, pull requests merged in 2022-03, with the labels that each got.

#7101 [skip ci] purge: ceph-crash purge fixes
  infrastructure-playbooks/purge-cluster.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#7080 [skip ci] adopt: various fixes
  group_vars/all.yml.sample
  group_vars/rhcs.yml.sample
  infrastructure-playbooks/cephadm-adopt.yml
  roles/ceph-defaults/defaults/main.yml
Labels: backport-stable-5.0, backport-stable-6.0

#7109 Turn off SELinux separation for containers MON and RGW
  roles/ceph-container-common/tasks/prerequisites.yml
  roles/ceph-mon/templates/ceph-mon.service.j2
  roles/ceph-rgw/templates/ceph-radosgw.service.j2
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0

#7113 [skip ci] Using another user than root for cephadm ssh connections fails
  infrastructure-playbooks/cephadm-adopt.yml
Labels: backport-stable-6.0

#7117 dashboard: always set `dashboard_server_addr`
  roles/ceph-dashboard/tasks/configure_dashboard.yml
Labels: backport-stable-4.0, backport-stable-5.0, backport-stable-6.0
